using Blackbird.Applications.Sdk.Common;
using Blackbird.Applications.Sdk.Common.Dynamic;
using Blackbird.Applications.Sdk.Common.Invocation;
using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.Slack.DataSourceHandlers;

public class EmojiHandler : EnumDataHandler
{
    protected override Dictionary<string, string> EnumValues => new() 
    {
        { "hash", "#️⃣ Hash Key" },
        { "keycap_star", "*️⃣ Keycap: *" },
        { "zero", "0️⃣ Keycap 0" },
        { "one", "1️⃣ Keycap 1" },
        { "two", "2️⃣ Keycap 2" },
        { "three", "3️⃣ Keycap 3" },
        { "four", "4️⃣ Keycap 4" },
        { "five", "5️⃣ Keycap 5" },
        { "six", "6️⃣ Keycap 6" },
        { "seven", "7️⃣ Keycap 7" },
        { "eight", "8️⃣ Keycap 8" },
        { "nine", "9️⃣ Keycap 9" },
        { "copyright", "©️ Copyright Sign" },
        { "registered", "®️ Registered Sign" },
        { "mahjong", "🀄 Mahjong Tile Red Dragon" },
        { "black_joker", "🃏 Playing Card Black Joker" },
        { "a", "🅰️ Negative Squared Latin Capital Letter A" },
        { "b", "🅱️ Negative Squared Latin Capital Letter B" },
        { "o2", "🅾️ Negative Squared Latin Capital Letter O" },
        { "parking", "🅿️ Negative Squared Latin Capital Letter P" },
        { "ab", "🆎 Negative Squared Ab" },
        { "cl", "🆑 Squared Cl" },
        { "cool", "🆒 Squared Cool" },
        { "free", "🆓 Squared Free" },
        { "id", "🆔 Squared Id" },
        { "new", "🆕 Squared New" },
        { "ng", "🆖 Squared Ng" },
        { "ok", "🆗 Squared Ok" },
        { "sos", "🆘 Squared Sos" },
        { "up", "🆙 Squared Up With Exclamation Mark" },
        { "vs", "🆚 Squared Vs" },
        { "flag-ac", "🇦🇨 Ascension Island Flag" },
        { "flag-ad", "🇦🇩 Andorra Flag" },
        { "flag-ae", "🇦🇪 United Arab Emirates Flag" },
        { "flag-af", "🇦🇫 Afghanistan Flag" },
        { "flag-ag", "🇦🇬 Antigua & Barbuda Flag" },
        { "flag-ai", "🇦🇮 Anguilla Flag" },
        { "flag-al", "🇦🇱 Albania Flag" },
        { "flag-am", "🇦🇲 Armenia Flag" },
        { "flag-ao", "🇦🇴 Angola Flag" },
        { "flag-aq", "🇦🇶 Antarctica Flag" },
        { "flag-ar", "🇦🇷 Argentina Flag" },
        { "flag-as", "🇦🇸 American Samoa Flag" },
        { "flag-at", "🇦🇹 Austria Flag" },
        { "flag-au", "🇦🇺 Australia Flag" },
        { "flag-aw", "🇦🇼 Aruba Flag" },
        { "flag-ax", "🇦🇽 Åland Islands Flag" },
        { "flag-az", "🇦🇿 Azerbaijan Flag" },
        { "flag-ba", "🇧🇦 Bosnia & Herzegovina Flag" },
        { "flag-bb", "🇧🇧 Barbados Flag" },
        { "flag-bd", "🇧🇩 Bangladesh Flag" },
        { "flag-be", "🇧🇪 Belgium Flag" },
        { "flag-bf", "🇧🇫 Burkina Faso Flag" },
        { "flag-bg", "🇧🇬 Bulgaria Flag" },
        { "flag-bh", "🇧🇭 Bahrain Flag" },
        { "flag-bi", "🇧🇮 Burundi Flag" },
        { "flag-bj", "🇧🇯 Benin Flag" },
        { "flag-bl", "🇧🇱 St. Barthélemy Flag" },
        { "flag-bm", "🇧🇲 Bermuda Flag" },
        { "flag-bn", "🇧🇳 Brunei Flag" },
        { "flag-bo", "🇧🇴 Bolivia Flag" },
        { "flag-bq", "🇧🇶 Caribbean Netherlands Flag" },
        { "flag-br", "🇧🇷 Brazil Flag" },
        { "flag-bs", "🇧🇸 Bahamas Flag" },
        { "flag-bt", "🇧🇹 Bhutan Flag" },
        { "flag-bv", "🇧🇻 Bouvet Island Flag" },
        { "flag-bw", "🇧🇼 Botswana Flag" },
        { "flag-by", "🇧🇾 Belarus Flag" },
        { "flag-bz", "🇧🇿 Belize Flag" },
        { "flag-ca", "🇨🇦 Canada Flag" },
        { "flag-cc", "🇨🇨 Cocos (Keeling) Islands Flag" },
        { "flag-cd", "🇨🇩 Congo - Kinshasa Flag" },
        { "flag-cf", "🇨🇫 Central African Republic Flag" },
        { "flag-cg", "🇨🇬 Congo - Brazzaville Flag" },
        { "flag-ch", "🇨🇭 Switzerland Flag" },
        { "flag-ci", "🇨🇮 Côte D’Ivoire Flag" },
        { "flag-ck", "🇨🇰 Cook Islands Flag" },
        { "flag-cl", "🇨🇱 Chile Flag" },
        { "flag-cm", "🇨🇲 Cameroon Flag" },
        { "cn", "🇨🇳 China Flag" },
        { "flag-co", "🇨🇴 Colombia Flag" },
        { "flag-cp", "🇨🇵 Clipperton Island Flag" },
        { "flag-cr", "🇨🇷 Costa Rica Flag" },
        { "flag-cu", "🇨🇺 Cuba Flag" },
        { "flag-cv", "🇨🇻 Cape Verde Flag" },
        { "flag-cw", "🇨🇼 Curaçao Flag" },
        { "flag-cx", "🇨🇽 Christmas Island Flag" },
        { "flag-cy", "🇨🇾 Cyprus Flag" },
        { "flag-cz", "🇨🇿 Czechia Flag" },
        { "de", "🇩🇪 Germany Flag" },
        { "flag-dg", "🇩🇬 Diego Garcia Flag" },
        { "flag-dj", "🇩🇯 Djibouti Flag" },
        { "flag-dk", "🇩🇰 Denmark Flag" },
        { "flag-dm", "🇩🇲 Dominica Flag" },
        { "flag-do", "🇩🇴 Dominican Republic Flag" },
        { "flag-dz", "🇩🇿 Algeria Flag" },
        { "flag-ea", "🇪🇦 Ceuta & Melilla Flag" },
        { "flag-ec", "🇪🇨 Ecuador Flag" },
        { "flag-ee", "🇪🇪 Estonia Flag" },
        { "flag-eg", "🇪🇬 Egypt Flag" },
        { "flag-eh", "🇪🇭 Western Sahara Flag" },
        { "flag-er", "🇪🇷 Eritrea Flag" },
        { "es", "🇪🇸 Spain Flag" },
        { "flag-et", "🇪🇹 Ethiopia Flag" },
        { "flag-eu", "🇪🇺 European Union Flag" },
        { "flag-fi", "🇫🇮 Finland Flag" },
        { "flag-fj", "🇫🇯 Fiji Flag" },
        { "flag-fk", "🇫🇰 Falkland Islands Flag" },
        { "flag-fm", "🇫🇲 Micronesia Flag" },
        { "flag-fo", "🇫🇴 Faroe Islands Flag" },
        { "fr", "🇫🇷 France Flag" },
        { "flag-ga", "🇬🇦 Gabon Flag" },
        { "gb", "🇬🇧 United Kingdom Flag" },
        { "flag-gd", "🇬🇩 Grenada Flag" },
        { "flag-ge", "🇬🇪 Georgia Flag" },
        { "flag-gf", "🇬🇫 French Guiana Flag" },
        { "flag-gg", "🇬🇬 Guernsey Flag" },
        { "flag-gh", "🇬🇭 Ghana Flag" },
        { "flag-gi", "🇬🇮 Gibraltar Flag" },
        { "flag-gl", "🇬🇱 Greenland Flag" },
        { "flag-gm", "🇬🇲 Gambia Flag" },
        { "flag-gn", "🇬🇳 Guinea Flag" },
        { "flag-gp", "🇬🇵 Guadeloupe Flag" },
        { "flag-gq", "🇬🇶 Equatorial Guinea Flag" },
        { "flag-gr", "🇬🇷 Greece Flag" },
        { "flag-gs", "🇬🇸 South Georgia & South Sandwich Islands Flag" },
        { "flag-gt", "🇬🇹 Guatemala Flag" },
        { "flag-gu", "🇬🇺 Guam Flag" },
        { "flag-gw", "🇬🇼 Guinea-Bissau Flag" },
        { "flag-gy", "🇬🇾 Guyana Flag" },
        { "flag-hk", "🇭🇰 Hong Kong Sar China Flag" },
        { "flag-hm", "🇭🇲 Heard & Mcdonald Islands Flag" },
        { "flag-hn", "🇭🇳 Honduras Flag" },
        { "flag-hr", "🇭🇷 Croatia Flag" },
        { "flag-ht", "🇭🇹 Haiti Flag" },
        { "flag-hu", "🇭🇺 Hungary Flag" },
        { "flag-ic", "🇮🇨 Canary Islands Flag" },
        { "flag-id", "🇮🇩 Indonesia Flag" },
        { "flag-ie", "🇮🇪 Ireland Flag" },
        { "flag-il", "🇮🇱 Israel Flag" },
        { "flag-im", "🇮🇲 Isle Of Man Flag" },
        { "flag-in", "🇮🇳 India Flag" },
        { "flag-io", "🇮🇴 British Indian Ocean Territory Flag" },
        { "flag-iq", "🇮🇶 Iraq Flag" },
        { "flag-ir", "🇮🇷 Iran Flag" },
        { "flag-is", "🇮🇸 Iceland Flag" },
        { "it", "🇮🇹 Italy Flag" },
        { "flag-je", "🇯🇪 Jersey Flag" },
        { "flag-jm", "🇯🇲 Jamaica Flag" },
        { "flag-jo", "🇯🇴 Jordan Flag" },
        { "jp", "🇯🇵 Japan Flag" },
        { "flag-ke", "🇰🇪 Kenya Flag" },
        { "flag-kg", "🇰🇬 Kyrgyzstan Flag" },
        { "flag-kh", "🇰🇭 Cambodia Flag" },
        { "flag-ki", "🇰🇮 Kiribati Flag" },
        { "flag-km", "🇰🇲 Comoros Flag" },
        { "flag-kn", "🇰🇳 St. Kitts & Nevis Flag" },
        { "flag-kp", "🇰🇵 North Korea Flag" },
        { "kr", "🇰🇷 South Korea Flag" },
        { "flag-kw", "🇰🇼 Kuwait Flag" },
        { "flag-ky", "🇰🇾 Cayman Islands Flag" },
        { "flag-kz", "🇰🇿 Kazakhstan Flag" },
        { "flag-la", "🇱🇦 Laos Flag" },
        { "flag-lb", "🇱🇧 Lebanon Flag" },
        { "flag-lc", "🇱🇨 St. Lucia Flag" },
        { "flag-li", "🇱🇮 Liechtenstein Flag" },
        { "flag-lk", "🇱🇰 Sri Lanka Flag" },
        { "flag-lr", "🇱🇷 Liberia Flag" },
        { "flag-ls", "🇱🇸 Lesotho Flag" },
        { "flag-lt", "🇱🇹 Lithuania Flag" },
        { "flag-lu", "🇱🇺 Luxembourg Flag" },
        { "flag-lv", "🇱🇻 Latvia Flag" },
        { "flag-ly", "🇱🇾 Libya Flag" },
        { "flag-ma", "🇲🇦 Morocco Flag" },
        { "flag-mc", "🇲🇨 Monaco Flag" },
        { "flag-md", "🇲🇩 Moldova Flag" },
        { "flag-me", "🇲🇪 Montenegro Flag" },
        { "flag-mf", "🇲🇫 St. Martin Flag" },
        { "flag-mg", "🇲🇬 Madagascar Flag" },
        { "flag-mh", "🇲🇭 Marshall Islands Flag" },
        { "flag-mk", "🇲🇰 North Macedonia Flag" },
        { "flag-ml", "🇲🇱 Mali Flag" },
        { "flag-mm", "🇲🇲 Myanmar (Burma) Flag" },
        { "flag-mn", "🇲🇳 Mongolia Flag" },
        { "flag-mo", "🇲🇴 Macao Sar China Flag" },
        { "flag-mp", "🇲🇵 Northern Mariana Islands Flag" },
        { "flag-mq", "🇲🇶 Martinique Flag" },
        { "flag-mr", "🇲🇷 Mauritania Flag" },
        { "flag-ms", "🇲🇸 Montserrat Flag" },
        { "flag-mt", "🇲🇹 Malta Flag" },
        { "flag-mu", "🇲🇺 Mauritius Flag" },
        { "flag-mv", "🇲🇻 Maldives Flag" },
        { "flag-mw", "🇲🇼 Malawi Flag" },
        { "flag-mx", "🇲🇽 Mexico Flag" },
        { "flag-my", "🇲🇾 Malaysia Flag" },
        { "flag-mz", "🇲🇿 Mozambique Flag" },
        { "flag-na", "🇳🇦 Namibia Flag" },
        { "flag-nc", "🇳🇨 New Caledonia Flag" },
        { "flag-ne", "🇳🇪 Niger Flag" },
        { "flag-nf", "🇳🇫 Norfolk Island Flag" },
        { "flag-ng", "🇳🇬 Nigeria Flag" },
        { "flag-ni", "🇳🇮 Nicaragua Flag" },
        { "flag-nl", "🇳🇱 Netherlands Flag" },
        { "flag-no", "🇳🇴 Norway Flag" },
        { "flag-np", "🇳🇵 Nepal Flag" },
        { "flag-nr", "🇳🇷 Nauru Flag" },
        { "flag-nu", "🇳🇺 Niue Flag" },
        { "flag-nz", "🇳🇿 New Zealand Flag" },
        { "flag-om", "🇴🇲 Oman Flag" },
        { "flag-pa", "🇵🇦 Panama Flag" },
        { "flag-pe", "🇵🇪 Peru Flag" },
        { "flag-pf", "🇵🇫 French Polynesia Flag" },
        { "flag-pg", "🇵🇬 Papua New Guinea Flag" },
        { "flag-ph", "🇵🇭 Philippines Flag" },
        { "flag-pk", "🇵🇰 Pakistan Flag" },
        { "flag-pl", "🇵🇱 Poland Flag" },
        { "flag-pm", "🇵🇲 St. Pierre & Miquelon Flag" },
        { "flag-pn", "🇵🇳 Pitcairn Islands Flag" },
        { "flag-pr", "🇵🇷 Puerto Rico Flag" },
        { "flag-ps", "🇵🇸 Palestinian Territories Flag" },
        { "flag-pt", "🇵🇹 Portugal Flag" },
        { "flag-pw", "🇵🇼 Palau Flag" },
        { "flag-py", "🇵🇾 Paraguay Flag" },
        { "flag-qa", "🇶🇦 Qatar Flag" },
        { "flag-re", "🇷🇪 Réunion Flag" },
        { "flag-ro", "🇷🇴 Romania Flag" },
        { "flag-rs", "🇷🇸 Serbia Flag" },
        { "ru", "🇷🇺 Russia Flag" },
        { "flag-rw", "🇷🇼 Rwanda Flag" },
        { "flag-sa", "🇸🇦 Saudi Arabia Flag" },
        { "flag-sb", "🇸🇧 Solomon Islands Flag" },
        { "flag-sc", "🇸🇨 Seychelles Flag" },
        { "flag-sd", "🇸🇩 Sudan Flag" },
        { "flag-se", "🇸🇪 Sweden Flag" },
        { "flag-sg", "🇸🇬 Singapore Flag" },
        { "flag-sh", "🇸🇭 St. Helena Flag" },
        { "flag-si", "🇸🇮 Slovenia Flag" },
        { "flag-sj", "🇸🇯 Svalbard & Jan Mayen Flag" },
        { "flag-sk", "🇸🇰 Slovakia Flag" },
        { "flag-sl", "🇸🇱 Sierra Leone Flag" },
        { "flag-sm", "🇸🇲 San Marino Flag" },
        { "flag-sn", "🇸🇳 Senegal Flag" },
        { "flag-so", "🇸🇴 Somalia Flag" },
        { "flag-sr", "🇸🇷 Suriname Flag" },
        { "flag-ss", "🇸🇸 South Sudan Flag" },
        { "flag-st", "🇸🇹 São Tomé & Príncipe Flag" },
        { "flag-sv", "🇸🇻 El Salvador Flag" },
        { "flag-sx", "🇸🇽 Sint Maarten Flag" },
        { "flag-sy", "🇸🇾 Syria Flag" },
        { "flag-sz", "🇸🇿 Eswatini Flag" },
        { "flag-ta", "🇹🇦 Tristan Da Cunha Flag" },
        { "flag-tc", "🇹🇨 Turks & Caicos Islands Flag" },
        { "flag-td", "🇹🇩 Chad Flag" },
        { "flag-tf", "🇹🇫 French Southern Territories Flag" },
        { "flag-tg", "🇹🇬 Togo Flag" },
        { "flag-th", "🇹🇭 Thailand Flag" },
        { "flag-tj", "🇹🇯 Tajikistan Flag" },
        { "flag-tk", "🇹🇰 Tokelau Flag" },
        { "flag-tl", "🇹🇱 Timor-Leste Flag" },
        { "flag-tm", "🇹🇲 Turkmenistan Flag" },
        { "flag-tn", "🇹🇳 Tunisia Flag" },
        { "flag-to", "🇹🇴 Tonga Flag" },
        { "flag-tr", "🇹🇷 Turkey Flag" },
        { "flag-tt", "🇹🇹 Trinidad & Tobago Flag" },
        { "flag-tv", "🇹🇻 Tuvalu Flag" },
        { "flag-tw", "🇹🇼 Taiwan Flag" },
        { "flag-tz", "🇹🇿 Tanzania Flag" },
        { "flag-ua", "🇺🇦 Ukraine Flag" },
        { "flag-ug", "🇺🇬 Uganda Flag" },
        { "flag-um", "🇺🇲 U.S. Outlying Islands Flag" },
        { "flag-un", "🇺🇳 United Nations Flag" },
        { "us", "🇺🇸 United States Flag" },
        { "flag-uy", "🇺🇾 Uruguay Flag" },
        { "flag-uz", "🇺🇿 Uzbekistan Flag" },
        { "flag-va", "🇻🇦 Vatican City Flag" },
        { "flag-vc", "🇻🇨 St. Vincent & Grenadines Flag" },
        { "flag-ve", "🇻🇪 Venezuela Flag" },
        { "flag-vg", "🇻🇬 British Virgin Islands Flag" },
        { "flag-vi", "🇻🇮 U.S. Virgin Islands Flag" },
        { "flag-vn", "🇻🇳 Vietnam Flag" },
        { "flag-vu", "🇻🇺 Vanuatu Flag" },
        { "flag-wf", "🇼🇫 Wallis & Futuna Flag" },
        { "flag-ws", "🇼🇸 Samoa Flag" },
        { "flag-xk", "🇽🇰 Kosovo Flag" },
        { "flag-ye", "🇾🇪 Yemen Flag" },
        { "flag-yt", "🇾🇹 Mayotte Flag" },
        { "flag-za", "🇿🇦 South Africa Flag" },
        { "flag-zm", "🇿🇲 Zambia Flag" },
        { "flag-zw", "🇿🇼 Zimbabwe Flag" },
        { "koko", "🈁 Squared Katakana Koko" },
        { "sa", "🈂️ Squared Katakana Sa" },
        { "u7121", "🈚 Squared Cjk Unified Ideograph-7121" },
        { "u6307", "🈯 Squared Cjk Unified Ideograph-6307" },
        { "u7981", "🈲 Squared Cjk Unified Ideograph-7981" },
        { "u7a7a", "🈳 Squared Cjk Unified Ideograph-7A7A" },
        { "u5408", "🈴 Squared Cjk Unified Ideograph-5408" },
        { "u6e80", "🈵 Squared Cjk Unified Ideograph-6E80" },
        { "u6709", "🈶 Squared Cjk Unified Ideograph-6709" },
        { "u6708", "🈷️ Squared Cjk Unified Ideograph-6708" },
        { "u7533", "🈸 Squared Cjk Unified Ideograph-7533" },
        { "u5272", "🈹 Squared Cjk Unified Ideograph-5272" },
        { "u55b6", "🈺 Squared Cjk Unified Ideograph-55B6" },
        { "ideograph_advantage", "🉐 Circled Ideograph Advantage" },
        { "accept", "🉑 Circled Ideograph Accept" },
        { "cyclone", "🌀 Cyclone" },
        { "foggy", "🌁 Foggy" },
        { "closed_umbrella", "🌂 Closed Umbrella" },
        { "night_with_stars", "🌃 Night With Stars" },
        { "sunrise_over_mountains", "🌄 Sunrise Over Mountains" },
        { "sunrise", "🌅 Sunrise" },
        { "city_sunset", "🌆 Cityscape At Dusk" },
        { "city_sunrise", "🌇 Sunset Over Buildings" },
        { "rainbow", "🌈 Rainbow" },
        { "bridge_at_night", "🌉 Bridge At Night" },
        { "ocean", "🌊 Water Wave" },
        { "volcano", "🌋 Volcano" },
        { "milky_way", "🌌 Milky Way" },
        { "earth_africa", "🌍 Earth Globe Europe-Africa" },
        { "earth_americas", "🌎 Earth Globe Americas" },
        { "earth_asia", "🌏 Earth Globe Asia-Australia" },
        { "globe_with_meridians", "🌐 Globe With Meridians" },
        { "new_moon", "🌑 New Moon Symbol" },
        { "waxing_crescent_moon", "🌒 Waxing Crescent Moon Symbol" },
        { "first_quarter_moon", "🌓 First Quarter Moon Symbol" },
        { "moon", "🌔 Waxing Gibbous Moon Symbol" },
        { "full_moon", "🌕 Full Moon Symbol" },
        { "waning_gibbous_moon", "🌖 Waning Gibbous Moon Symbol" },
        { "last_quarter_moon", "🌗 Last Quarter Moon Symbol" },
        { "waning_crescent_moon", "🌘 Waning Crescent Moon Symbol" },
        { "crescent_moon", "🌙 Crescent Moon" },
        { "new_moon_with_face", "🌚 New Moon With Face" },
        { "first_quarter_moon_with_face", "🌛 First Quarter Moon With Face" },
        { "last_quarter_moon_with_face", "🌜 Last Quarter Moon With Face" },
        { "full_moon_with_face", "🌝 Full Moon With Face" },
        { "sun_with_face", "🌞 Sun With Face" },
        { "star2", "🌟 Glowing Star" },
        { "stars", "🌠 Shooting Star" },
        { "thermometer", "🌡️ Thermometer" },
        { "mostly_sunny", "🌤️ Sun Behind Small Cloud" },
        { "barely_sunny", "🌥️ Sun Behind Large Cloud" },
        { "partly_sunny_rain", "🌦️ Sun Behind Rain Cloud" },
        { "rain_cloud", "🌧️ Cloud With Rain" },
        { "snow_cloud", "🌨️ Cloud With Snow" },
        { "lightning", "🌩️ Cloud With Lightning" },
        { "tornado", "🌪️ Tornado" },
        { "fog", "🌫️ Fog" },
        { "wind_blowing_face", "🌬️ Wind Face" },
        { "hotdog", "🌭 Hot Dog" },
        { "taco", "🌮 Taco" },
        { "burrito", "🌯 Burrito" },
        { "chestnut", "🌰 Chestnut" },
        { "seedling", "🌱 Seedling" },
        { "evergreen_tree", "🌲 Evergreen Tree" },
        { "deciduous_tree", "🌳 Deciduous Tree" },
        { "palm_tree", "🌴 Palm Tree" },
        { "cactus", "🌵 Cactus" },
        { "hot_pepper", "🌶️ Hot Pepper" },
        { "tulip", "🌷 Tulip" },
        { "cherry_blossom", "🌸 Cherry Blossom" },
        { "rose", "🌹 Rose" },
        { "hibiscus", "🌺 Hibiscus" },
        { "sunflower", "🌻 Sunflower" },
        { "blossom", "🌼 Blossom" },
        { "corn", "🌽 Ear Of Maize" },
        { "ear_of_rice", "🌾 Ear Of Rice" },
        { "herb", "🌿 Herb" },
        { "four_leaf_clover", "🍀 Four Leaf Clover" },
        { "maple_leaf", "🍁 Maple Leaf" },
        { "fallen_leaf", "🍂 Fallen Leaf" },
        { "leaves", "🍃 Leaf Fluttering In Wind" },
        { "mushroom", "🍄 Mushroom" },
        { "tomato", "🍅 Tomato" },
        { "eggplant", "🍆 Aubergine" },
        { "grapes", "🍇 Grapes" },
        { "melon", "🍈 Melon" },
        { "watermelon", "🍉 Watermelon" },
        { "tangerine", "🍊 Tangerine" },
        { "lemon", "🍋 Lemon" },
        { "banana", "🍌 Banana" },
        { "pineapple", "🍍 Pineapple" },
        { "apple", "🍎 Red Apple" },
        { "green_apple", "🍏 Green Apple" },
        { "pear", "🍐 Pear" },
        { "peach", "🍑 Peach" },
        { "cherries", "🍒 Cherries" },
        { "strawberry", "🍓 Strawberry" },
        { "hamburger", "🍔 Hamburger" },
        { "pizza", "🍕 Slice Of Pizza" },
        { "meat_on_bone", "🍖 Meat On Bone" },
        { "poultry_leg", "🍗 Poultry Leg" },
        { "rice_cracker", "🍘 Rice Cracker" },
        { "rice_ball", "🍙 Rice Ball" },
        { "rice", "🍚 Cooked Rice" },
        { "curry", "🍛 Curry And Rice" },
        { "ramen", "🍜 Steaming Bowl" },
        { "spaghetti", "🍝 Spaghetti" },
        { "bread", "🍞 Bread" },
        { "fries", "🍟 French Fries" },
        { "sweet_potato", "🍠 Roasted Sweet Potato" },
        { "dango", "🍡 Dango" },
        { "oden", "🍢 Oden" },
        { "sushi", "🍣 Sushi" },
        { "fried_shrimp", "🍤 Fried Shrimp" },
        { "fish_cake", "🍥 Fish Cake With Swirl Design" },
        { "icecream", "🍦 Soft Ice Cream" },
        { "shaved_ice", "🍧 Shaved Ice" },
        { "ice_cream", "🍨 Ice Cream" },
        { "doughnut", "🍩 Doughnut" },
        { "cookie", "🍪 Cookie" },
        { "chocolate_bar", "🍫 Chocolate Bar" },
        { "candy", "🍬 Candy" },
        { "lollipop", "🍭 Lollipop" },
        { "custard", "🍮 Custard" },
        { "honey_pot", "🍯 Honey Pot" },
        { "cake", "🍰 Shortcake" },
        { "bento", "🍱 Bento Box" },
        { "stew", "🍲 Pot Of Food" },
        { "fried_egg", "🍳 Cooking" },
        { "fork_and_knife", "🍴 Fork And Knife" },
        { "tea", "🍵 Teacup Without Handle" },
        { "sake", "🍶 Sake Bottle And Cup" },
        { "wine_glass", "🍷 Wine Glass" },
        { "cocktail", "🍸 Cocktail Glass" },
        { "tropical_drink", "🍹 Tropical Drink" },
        { "beer", "🍺 Beer Mug" },
        { "beers", "🍻 Clinking Beer Mugs" },
        { "baby_bottle", "🍼 Baby Bottle" },
        { "knife_fork_plate", "🍽️ Fork And Knife With Plate" },
        { "champagne", "🍾 Bottle With Popping Cork" },
        { "popcorn", "🍿 Popcorn" },
        { "ribbon", "🎀 Ribbon" },
        { "gift", "🎁 Wrapped Present" },
        { "birthday", "🎂 Birthday Cake" },
        { "jack_o_lantern", "🎃 Jack-O-Lantern" },
        { "christmas_tree", "🎄 Christmas Tree" },
        { "santa", "🎅 Father Christmas" },
        { "fireworks", "🎆 Fireworks" },
        { "sparkler", "🎇 Firework Sparkler" },
        { "balloon", "🎈 Balloon" },
        { "tada", "🎉 Party Popper" },
        { "confetti_ball", "🎊 Confetti Ball" },
        { "tanabata_tree", "🎋 Tanabata Tree" },
        { "crossed_flags", "🎌 Crossed Flags" },
        { "bamboo", "🎍 Pine Decoration" },
        { "dolls", "🎎 Japanese Dolls" },
        { "flags", "🎏 Carp Streamer" },
        { "wind_chime", "🎐 Wind Chime" },
        { "rice_scene", "🎑 Moon Viewing Ceremony" },
        { "school_satchel", "🎒 School Satchel" },
        { "mortar_board", "🎓 Graduation Cap" },
        { "medal", "🎖️ Military Medal" },
        { "reminder_ribbon", "🎗️ Reminder Ribbon" },
        { "studio_microphone", "🎙️ Studio Microphone" },
        { "level_slider", "🎚️ Level Slider" },
        { "control_knobs", "🎛️ Control Knobs" },
        { "film_frames", "🎞️ Film Frames" },
        { "admission_tickets", "🎟️ Admission Tickets" },
        { "carousel_horse", "🎠 Carousel Horse" },
        { "ferris_wheel", "🎡 Ferris Wheel" },
        { "roller_coaster", "🎢 Roller Coaster" },
        { "fishing_pole_and_fish", "🎣 Fishing Pole And Fish" },
        { "microphone", "🎤 Microphone" },
        { "movie_camera", "🎥 Movie Camera" },
        { "cinema", "🎦 Cinema" },
        { "headphones", "🎧 Headphone" },
        { "art", "🎨 Artist Palette" },
        { "tophat", "🎩 Top Hat" },
        { "circus_tent", "🎪 Circus Tent" },
        { "ticket", "🎫 Ticket" },
        { "clapper", "🎬 Clapper Board" },
        { "performing_arts", "🎭 Performing Arts" },
        { "video_game", "🎮 Video Game" },
        { "dart", "🎯 Direct Hit" },
        { "slot_machine", "🎰 Slot Machine" },
        { "8ball", "🎱 Billiards" },
        { "game_die", "🎲 Game Die" },
        { "bowling", "🎳 Bowling" },
        { "flower_playing_cards", "🎴 Flower Playing Cards" },
        { "musical_note", "🎵 Musical Note" },
        { "notes", "🎶 Multiple Musical Notes" },
        { "saxophone", "🎷 Saxophone" },
        { "guitar", "🎸 Guitar" },
        { "musical_keyboard", "🎹 Musical Keyboard" },
        { "trumpet", "🎺 Trumpet" },
        { "violin", "🎻 Violin" },
        { "musical_score", "🎼 Musical Score" },
        { "running_shirt_with_sash", "🎽 Running Shirt With Sash" },
        { "tennis", "🎾 Tennis Racquet And Ball" },
        { "ski", "🎿 Ski And Ski Boot" },
        { "basketball", "🏀 Basketball And Hoop" },
        { "checkered_flag", "🏁 Chequered Flag" },
        { "snowboarder", "🏂 Snowboarder" },
        { "woman-running", "🏃‍♀️ Woman Running" },
        { "man-running", "🏃‍♂️ Man Running" },
        { "runner", "🏃 Runner" },
        { "woman-surfing", "🏄‍♀️ Woman Surfing" },
        { "man-surfing", "🏄‍♂️ Man Surfing" },
        { "surfer", "🏄 Surfer" },
        { "sports_medal", "🏅 Sports Medal" },
        { "trophy", "🏆 Trophy" },
        { "horse_racing", "🏇 Horse Racing" },
        { "football", "🏈 American Football" },
        { "rugby_football", "🏉 Rugby Football" },
        { "woman-swimming", "🏊‍♀️ Woman Swimming" },
        { "man-swimming", "🏊‍♂️ Man Swimming" },
        { "swimmer", "🏊 Swimmer" },
        { "woman-lifting-weights", "🏋️‍♀️ Woman Lifting Weights" },
        { "man-lifting-weights", "🏋️‍♂️ Man Lifting Weights" },
        { "weight_lifter", "🏋️ Person Lifting Weights" },
        { "woman-golfing", "🏌️‍♀️ Woman Golfing" },
        { "man-golfing", "🏌️‍♂️ Man Golfing" },
        { "golfer", "🏌️ Person Golfing" },
        { "racing_motorcycle", "🏍️ Motorcycle" },
        { "racing_car", "🏎️ Racing Car" },
        { "cricket_bat_and_ball", "🏏 Cricket Bat And Ball" },
        { "volleyball", "🏐 Volleyball" },
        { "field_hockey_stick_and_ball", "🏑 Field Hockey Stick And Ball" },
        { "ice_hockey_stick_and_puck", "🏒 Ice Hockey Stick And Puck" },
        { "table_tennis_paddle_and_ball", "🏓 Table Tennis Paddle And Ball" },
        { "snow_capped_mountain", "🏔️ Snow-Capped Mountain" },
        { "camping", "🏕️ Camping" },
        { "beach_with_umbrella", "🏖️ Beach With Umbrella" },
        { "building_construction", "🏗️ Building Construction" },
        { "house_buildings", "🏘️ Houses" },
        { "cityscape", "🏙️ Cityscape" },
        { "derelict_house_building", "🏚️ Derelict House" },
        { "classical_building", "🏛️ Classical Building" },
        { "desert", "🏜️ Desert" },
        { "desert_island", "🏝️ Desert Island" },
        { "national_park", "🏞️ National Park" },
        { "stadium", "🏟️ Stadium" },
        { "house", "🏠 House Building" },
        { "house_with_garden", "🏡 House With Garden" },
        { "office", "🏢 Office Building" },
        { "post_office", "🏣 Japanese Post Office" },
        { "european_post_office", "🏤 European Post Office" },
        { "hospital", "🏥 Hospital" },
        { "bank", "🏦 Bank" },
        { "atm", "🏧 Automated Teller Machine" },
        { "hotel", "🏨 Hotel" },
        { "love_hotel", "🏩 Love Hotel" },
        { "convenience_store", "🏪 Convenience Store" },
        { "school", "🏫 School" },
        { "department_store", "🏬 Department Store" },
        { "factory", "🏭 Factory" },
        { "izakaya_lantern", "🏮 Izakaya Lantern" },
        { "japanese_castle", "🏯 Japanese Castle" },
        { "european_castle", "🏰 European Castle" },
        { "rainbow-flag", "🏳️‍🌈 Rainbow Flag" },
        { "transgender_flag", "🏳️‍⚧️ Transgender Flag" },
        { "waving_white_flag", "🏳️ White Flag" },
        { "pirate_flag", "🏴‍☠️ Pirate Flag" },
        { "flag-england", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England Flag" },
        { "flag-scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland Flag" },
        { "flag-wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales Flag" },
        { "waving_black_flag", "🏴 Waving Black Flag" },
        { "rosette", "🏵️ Rosette" },
        { "label", "🏷️ Label" },
        { "badminton_racquet_and_shuttlecock", "🏸 Badminton Racquet And Shuttlecock" },
        { "bow_and_arrow", "🏹 Bow And Arrow" },
        { "amphora", "🏺 Amphora" },
        { "skin-tone-2", "🏻 Emoji Modifier Fitzpatrick Type-1-2" },
        { "skin-tone-3", "🏼 Emoji Modifier Fitzpatrick Type-3" },
        { "skin-tone-4", "🏽 Emoji Modifier Fitzpatrick Type-4" },
        { "skin-tone-5", "🏾 Emoji Modifier Fitzpatrick Type-5" },
        { "skin-tone-6", "🏿 Emoji Modifier Fitzpatrick Type-6" },
        { "rat", "🐀 Rat" },
        { "mouse2", "🐁 Mouse" },
        { "ox", "🐂 Ox" },
        { "water_buffalo", "🐃 Water Buffalo" },
        { "cow2", "🐄 Cow" },
        { "tiger2", "🐅 Tiger" },
        { "leopard", "🐆 Leopard" },
        { "rabbit2", "🐇 Rabbit" },
        { "black_cat", "🐈‍⬛ Black Cat" },
        { "cat2", "🐈 Cat" },
        { "dragon", "🐉 Dragon" },
        { "crocodile", "🐊 Crocodile" },
        { "whale2", "🐋 Whale" },
        { "snail", "🐌 Snail" },
        { "snake", "🐍 Snake" },
        { "racehorse", "🐎 Horse" },
        { "ram", "🐏 Ram" },
        { "goat", "🐐 Goat" },
        { "sheep", "🐑 Sheep" },
        { "monkey", "🐒 Monkey" },
        { "rooster", "🐓 Rooster" },
        { "chicken", "🐔 Chicken" },
        { "service_dog", "🐕‍🦺 Service Dog" },
        { "dog2", "🐕 Dog" },
        { "pig2", "🐖 Pig" },
        { "boar", "🐗 Boar" },
        { "elephant", "🐘 Elephant" },
        { "octopus", "🐙 Octopus" },
        { "shell", "🐚 Spiral Shell" },
        { "bug", "🐛 Bug" },
        { "ant", "🐜 Ant" },
        { "bee", "🐝 Honeybee" },
        { "ladybug", "🐞 Lady Beetle" },
        { "fish", "🐟 Fish" },
        { "tropical_fish", "🐠 Tropical Fish" },
        { "blowfish", "🐡 Blowfish" },
        { "turtle", "🐢 Turtle" },
        { "hatching_chick", "🐣 Hatching Chick" },
        { "baby_chick", "🐤 Baby Chick" },
        { "hatched_chick", "🐥 Front-Facing Baby Chick" },
        { "black_bird", "🐦‍⬛ Black Bird" },
        { "bird", "🐦 Bird" },
        { "penguin", "🐧 Penguin" },
        { "koala", "🐨 Koala" },
        { "poodle", "🐩 Poodle" },
        { "dromedary_camel", "🐪 Dromedary Camel" },
        { "camel", "🐫 Bactrian Camel" },
        { "dolphin", "🐬 Dolphin" },
        { "mouse", "🐭 Mouse Face" },
        { "cow", "🐮 Cow Face" },
        { "tiger", "🐯 Tiger Face" },
        { "rabbit", "🐰 Rabbit Face" },
        { "cat", "🐱 Cat Face" },
        { "dragon_face", "🐲 Dragon Face" },
        { "whale", "🐳 Spouting Whale" },
        { "horse", "🐴 Horse Face" },
        { "monkey_face", "🐵 Monkey Face" },
        { "dog", "🐶 Dog Face" },
        { "pig", "🐷 Pig Face" },
        { "frog", "🐸 Frog Face" },
        { "hamster", "🐹 Hamster Face" },
        { "wolf", "🐺 Wolf Face" },
        { "polar_bear", "🐻‍❄️ Polar Bear" },
        { "bear", "🐻 Bear Face" },
        { "panda_face", "🐼 Panda Face" },
        { "pig_nose", "🐽 Pig Nose" },
        { "feet", "🐾 Paw Prints" },
        { "chipmunk", "🐿️ Chipmunk" },
        { "eyes", "👀 Eyes" },
        { "eye-in-speech-bubble", "👁️‍🗨️ Eye In Speech Bubble" },
        { "eye", "👁️ Eye" },
        { "ear", "👂 Ear" },
        { "nose", "👃 Nose" },
        { "lips", "👄 Mouth" },
        { "tongue", "👅 Tongue" },
        { "point_up_2", "👆 White Up Pointing Backhand Index" },
        { "point_down", "👇 White Down Pointing Backhand Index" },
        { "point_left", "👈 White Left Pointing Backhand Index" },
        { "point_right", "👉 White Right Pointing Backhand Index" },
        { "facepunch", "👊 Fisted Hand Sign" },
        { "wave", "👋 Waving Hand Sign" },
        { "ok_hand", "👌 Ok Hand Sign" },
        { "+1", "👍 Thumbs Up Sign" },
        { "-1", "👎 Thumbs Down Sign" },
        { "clap", "👏 Clapping Hands Sign" },
        { "open_hands", "👐 Open Hands Sign" },
        { "crown", "👑 Crown" },
        { "womans_hat", "👒 Womans Hat" },
        { "eyeglasses", "👓 Eyeglasses" },
        { "necktie", "👔 Necktie" },
        { "shirt", "👕 T-Shirt" },
        { "jeans", "👖 Jeans" },
        { "dress", "👗 Dress" },
        { "kimono", "👘 Kimono" },
        { "bikini", "👙 Bikini" },
        { "womans_clothes", "👚 Womans Clothes" },
        { "purse", "👛 Purse" },
        { "handbag", "👜 Handbag" },
        { "pouch", "👝 Pouch" },
        { "mans_shoe", "👞 Mans Shoe" },
        { "athletic_shoe", "👟 Athletic Shoe" },
        { "high_heel", "👠 High-Heeled Shoe" },
        { "sandal", "👡 Womans Sandal" },
        { "boot", "👢 Womans Boots" },
        { "footprints", "👣 Footprints" },
        { "bust_in_silhouette", "👤 Bust In Silhouette" },
        { "busts_in_silhouette", "👥 Busts In Silhouette" },
        { "boy", "👦 Boy" },
        { "girl", "👧 Girl" },
        { "male-farmer", "👨‍🌾 Man Farmer" },
        { "male-cook", "👨‍🍳 Man Cook" },
        { "man_feeding_baby", "👨‍🍼 Man Feeding Baby" },
        { "male-student", "👨‍🎓 Man Student" },
        { "male-singer", "👨‍🎤 Man Singer" },
        { "male-artist", "👨‍🎨 Man Artist" },
        { "male-teacher", "👨‍🏫 Man Teacher" },
        { "male-factory-worker", "👨‍🏭 Man Factory Worker" },
        { "man-boy-boy", "👨‍👦‍👦 Family: Man, Boy, Boy" },
        { "man-boy", "👨‍👦 Family: Man, Boy" },
        { "man-girl-boy", "👨‍👧‍👦 Family: Man, Girl, Boy" },
        { "man-girl-girl", "👨‍👧‍👧 Family: Man, Girl, Girl" },
        { "man-girl", "👨‍👧 Family: Man, Girl" },
        { "man-man-boy", "👨‍👨‍👦 Family: Man, Man, Boy" },
        { "man-man-boy-boy", "👨‍👨‍👦‍👦 Family: Man, Man, Boy, Boy" },
        { "man-man-girl", "👨‍👨‍👧 Family: Man, Man, Girl" },
        { "man-man-girl-boy", "👨‍👨‍👧‍👦 Family: Man, Man, Girl, Boy" },
        { "man-man-girl-girl", "👨‍👨‍👧‍👧 Family: Man, Man, Girl, Girl" },
        { "man-woman-boy", "👨‍👩‍👦 Family: Man, Woman, Boy" },
        { "man-woman-boy-boy", "👨‍👩‍👦‍👦 Family: Man, Woman, Boy, Boy" },
        { "man-woman-girl", "👨‍👩‍👧 Family: Man, Woman, Girl" },
        { "man-woman-girl-boy", "👨‍👩‍👧‍👦 Family: Man, Woman, Girl, Boy" },
        { "man-woman-girl-girl", "👨‍👩‍👧‍👧 Family: Man, Woman, Girl, Girl" },
        { "male-technologist", "👨‍💻 Man Technologist" },
        { "male-office-worker", "👨‍💼 Man Office Worker" },
        { "male-mechanic", "👨‍🔧 Man Mechanic" },
        { "male-scientist", "👨‍🔬 Man Scientist" },
        { "male-astronaut", "👨‍🚀 Man Astronaut" },
        { "male-firefighter", "👨‍🚒 Man Firefighter" },
        { "man_with_probing_cane", "👨‍🦯 Man With White Cane" },
        { "red_haired_man", "👨‍🦰 Man: Red Hair" },
        { "curly_haired_man", "👨‍🦱 Man: Curly Hair" },
        { "bald_man", "👨‍🦲 Man: Bald" },
        { "white_haired_man", "👨‍🦳 Man: White Hair" },
        { "man_in_motorized_wheelchair", "👨‍🦼 Man In Motorized Wheelchair" },
        { "man_in_manual_wheelchair", "👨‍🦽 Man In Manual Wheelchair" },
        { "male-doctor", "👨‍⚕️ Man Health Worker" },
        { "male-judge", "👨‍⚖️ Man Judge" },
        { "male-pilot", "👨‍✈️ Man Pilot" },
        { "man-heart-man", "👨‍❤️‍👨 Couple With Heart: Man, Man" },
        { "man-kiss-man", "👨‍❤️‍💋‍👨 Kiss: Man, Man" },
        { "man", "👨 Man" },
        { "female-farmer", "👩‍🌾 Woman Farmer" },
        { "female-cook", "👩‍🍳 Woman Cook" },
        { "woman_feeding_baby", "👩‍🍼 Woman Feeding Baby" },
        { "female-student", "👩‍🎓 Woman Student" },
        { "female-singer", "👩‍🎤 Woman Singer" },
        { "female-artist", "👩‍🎨 Woman Artist" },
        { "female-teacher", "👩‍🏫 Woman Teacher" },
        { "female-factory-worker", "👩‍🏭 Woman Factory Worker" },
        { "woman-boy-boy", "👩‍👦‍👦 Family: Woman, Boy, Boy" },
        { "woman-boy", "👩‍👦 Family: Woman, Boy" },
        { "woman-girl-boy", "👩‍👧‍👦 Family: Woman, Girl, Boy" },
        { "woman-girl-girl", "👩‍👧‍👧 Family: Woman, Girl, Girl" },
        { "woman-girl", "👩‍👧 Family: Woman, Girl" },
        { "woman-woman-boy", "👩‍👩‍👦 Family: Woman, Woman, Boy" },
        { "woman-woman-boy-boy", "👩‍👩‍👦‍👦 Family: Woman, Woman, Boy, Boy" },
        { "woman-woman-girl", "👩‍👩‍👧 Family: Woman, Woman, Girl" },
        { "woman-woman-girl-boy", "👩‍👩‍👧‍👦 Family: Woman, Woman, Girl, Boy" },
        { "woman-woman-girl-girl", "👩‍👩‍👧‍👧 Family: Woman, Woman, Girl, Girl" },
        { "female-technologist", "👩‍💻 Woman Technologist" },
        { "female-office-worker", "👩‍💼 Woman Office Worker" },
        { "female-mechanic", "👩‍🔧 Woman Mechanic" },
        { "female-scientist", "👩‍🔬 Woman Scientist" },
        { "female-astronaut", "👩‍🚀 Woman Astronaut" },
        { "female-firefighter", "👩‍🚒 Woman Firefighter" },
        { "woman_with_probing_cane", "👩‍🦯 Woman With White Cane" },
        { "red_haired_woman", "👩‍🦰 Woman: Red Hair" },
        { "curly_haired_woman", "👩‍🦱 Woman: Curly Hair" },
        { "bald_woman", "👩‍🦲 Woman: Bald" },
        { "white_haired_woman", "👩‍🦳 Woman: White Hair" },
        { "woman_in_motorized_wheelchair", "👩‍🦼 Woman In Motorized Wheelchair" },
        { "woman_in_manual_wheelchair", "👩‍🦽 Woman In Manual Wheelchair" },
        { "female-doctor", "👩‍⚕️ Woman Health Worker" },
        { "female-judge", "👩‍⚖️ Woman Judge" },
        { "female-pilot", "👩‍✈️ Woman Pilot" },
        { "woman-heart-man", "👩‍❤️‍👨 Couple With Heart: Woman, Man" },
        { "woman-heart-woman", "👩‍❤️‍👩 Couple With Heart: Woman, Woman" },
        { "woman-kiss-man", "👩‍❤️‍💋‍👨 Kiss: Woman, Man" },
        { "woman-kiss-woman", "👩‍❤️‍💋‍👩 Kiss: Woman, Woman" },
        { "woman", "👩 Woman" },
        { "family", "👪 Family" },
        { "man_and_woman_holding_hands", "👫 Man And Woman Holding Hands" },
        { "two_men_holding_hands", "👬 Two Men Holding Hands" },
        { "two_women_holding_hands", "👭 Two Women Holding Hands" },
        { "female-police-officer", "👮‍♀️ Woman Police Officer" },
        { "male-police-officer", "👮‍♂️ Man Police Officer" },
        { "cop", "👮 Police Officer" },
        { "women-with-bunny-ears-partying", "👯‍♀️ Women With Bunny Ears" },
        { "men-with-bunny-ears-partying", "👯‍♂️ Men With Bunny Ears" },
        { "dancers", "👯 Woman With Bunny Ears" },
        { "woman_with_veil", "👰‍♀️ Woman With Veil" },
        { "man_with_veil", "👰‍♂️ Man With Veil" },
        { "bride_with_veil", "👰 Bride With Veil" },
        { "blond-haired-woman", "👱‍♀️ Woman: Blond Hair" },
        { "blond-haired-man", "👱‍♂️ Man: Blond Hair" },
        { "person_with_blond_hair", "👱 Person With Blond Hair" },
        { "man_with_gua_pi_mao", "👲 Man With Gua Pi Mao" },
        { "woman-wearing-turban", "👳‍♀️ Woman Wearing Turban" },
        { "man-wearing-turban", "👳‍♂️ Man Wearing Turban" },
        { "man_with_turban", "👳 Man With Turban" },
        { "older_man", "👴 Older Man" },
        { "older_woman", "👵 Older Woman" },
        { "baby", "👶 Baby" },
        { "female-construction-worker", "👷‍♀️ Woman Construction Worker" },
        { "male-construction-worker", "👷‍♂️ Man Construction Worker" },
        { "construction_worker", "👷 Construction Worker" },
        { "princess", "👸 Princess" },
        { "japanese_ogre", "👹 Japanese Ogre" },
        { "japanese_goblin", "👺 Japanese Goblin" },
        { "ghost", "👻 Ghost" },
        { "angel", "👼 Baby Angel" },
        { "alien", "👽 Extraterrestrial Alien" },
        { "space_invader", "👾 Alien Monster" },
        { "imp", "👿 Imp" },
        { "skull", "💀 Skull" },
        { "woman-tipping-hand", "💁‍♀️ Woman Tipping Hand" },
        { "man-tipping-hand", "💁‍♂️ Man Tipping Hand" },
        { "information_desk_person", "💁 Information Desk Person" },
        { "female-guard", "💂‍♀️ Woman Guard" },
        { "male-guard", "💂‍♂️ Man Guard" },
        { "guardsman", "💂 Guardsman" },
        { "dancer", "💃 Dancer" },
        { "lipstick", "💄 Lipstick" },
        { "nail_care", "💅 Nail Polish" },
        { "woman-getting-massage", "💆‍♀️ Woman Getting Massage" },
        { "man-getting-massage", "💆‍♂️ Man Getting Massage" },
        { "massage", "💆 Face Massage" },
        { "woman-getting-haircut", "💇‍♀️ Woman Getting Haircut" },
        { "man-getting-haircut", "💇‍♂️ Man Getting Haircut" },
        { "haircut", "💇 Haircut" },
        { "barber", "💈 Barber Pole" },
        { "syringe", "💉 Syringe" },
        { "pill", "💊 Pill" },
        { "kiss", "💋 Kiss Mark" },
        { "love_letter", "💌 Love Letter" },
        { "ring", "💍 Ring" },
        { "gem", "💎 Gem Stone" },
        { "couplekiss", "💏 Kiss" },
        { "bouquet", "💐 Bouquet" },
        { "couple_with_heart", "💑 Couple With Heart" },
        { "wedding", "💒 Wedding" },
        { "heartbeat", "💓 Beating Heart" },
        { "broken_heart", "💔 Broken Heart" },
        { "two_hearts", "💕 Two Hearts" },
        { "sparkling_heart", "💖 Sparkling Heart" },
        { "heartpulse", "💗 Growing Heart" },
        { "cupid", "💘 Heart With Arrow" },
        { "blue_heart", "💙 Blue Heart" },
        { "green_heart", "💚 Green Heart" },
        { "yellow_heart", "💛 Yellow Heart" },
        { "purple_heart", "💜 Purple Heart" },
        { "gift_heart", "💝 Heart With Ribbon" },
        { "revolving_hearts", "💞 Revolving Hearts" },
        { "heart_decoration", "💟 Heart Decoration" },
        { "diamond_shape_with_a_dot_inside", "💠 Diamond Shape With A Dot Inside" },
        { "bulb", "💡 Electric Light Bulb" },
        { "anger", "💢 Anger Symbol" },
        { "bomb", "💣 Bomb" },
        { "zzz", "💤 Sleeping Symbol" },
        { "boom", "💥 Collision Symbol" },
        { "sweat_drops", "💦 Splashing Sweat Symbol" },
        { "droplet", "💧 Droplet" },
        { "dash", "💨 Dash Symbol" },
        { "hankey", "💩 Pile Of Poo" },
        { "muscle", "💪 Flexed Biceps" },
        { "dizzy", "💫 Dizzy Symbol" },
        { "speech_balloon", "💬 Speech Balloon" },
        { "thought_balloon", "💭 Thought Balloon" },
        { "white_flower", "💮 White Flower" },
        { "100", "💯 Hundred Points Symbol" },
        { "moneybag", "💰 Money Bag" },
        { "currency_exchange", "💱 Currency Exchange" },
        { "heavy_dollar_sign", "💲 Heavy Dollar Sign" },
        { "credit_card", "💳 Credit Card" },
        { "yen", "💴 Banknote With Yen Sign" },
        { "dollar", "💵 Banknote With Dollar Sign" },
        { "euro", "💶 Banknote With Euro Sign" },
        { "pound", "💷 Banknote With Pound Sign" },
        { "money_with_wings", "💸 Money With Wings" },
        { "chart", "💹 Chart With Upwards Trend And Yen Sign" },
        { "seat", "💺 Seat" },
        { "computer", "💻 Personal Computer" },
        { "briefcase", "💼 Briefcase" },
        { "minidisc", "💽 Minidisc" },
        { "floppy_disk", "💾 Floppy Disk" },
        { "cd", "💿 Optical Disc" },
        { "dvd", "📀 Dvd" },
        { "file_folder", "📁 File Folder" },
        { "open_file_folder", "📂 Open File Folder" },
        { "page_with_curl", "📃 Page With Curl" },
        { "page_facing_up", "📄 Page Facing Up" },
        { "date", "📅 Calendar" },
        { "calendar", "📆 Tear-Off Calendar" },
        { "card_index", "📇 Card Index" },
        { "chart_with_upwards_trend", "📈 Chart With Upwards Trend" },
        { "chart_with_downwards_trend", "📉 Chart With Downwards Trend" },
        { "bar_chart", "📊 Bar Chart" },
        { "clipboard", "📋 Clipboard" },
        { "pushpin", "📌 Pushpin" },
        { "round_pushpin", "📍 Round Pushpin" },
        { "paperclip", "📎 Paperclip" },
        { "straight_ruler", "📏 Straight Ruler" },
        { "triangular_ruler", "📐 Triangular Ruler" },
        { "bookmark_tabs", "📑 Bookmark Tabs" },
        { "ledger", "📒 Ledger" },
        { "notebook", "📓 Notebook" },
        { "notebook_with_decorative_cover", "📔 Notebook With Decorative Cover" },
        { "closed_book", "📕 Closed Book" },
        { "book", "📖 Open Book" },
        { "green_book", "📗 Green Book" },
        { "blue_book", "📘 Blue Book" },
        { "orange_book", "📙 Orange Book" },
        { "books", "📚 Books" },
        { "name_badge", "📛 Name Badge" },
        { "scroll", "📜 Scroll" },
        { "memo", "📝 Memo" },
        { "telephone_receiver", "📞 Telephone Receiver" },
        { "pager", "📟 Pager" },
        { "fax", "📠 Fax Machine" },
        { "satellite_antenna", "📡 Satellite Antenna" },
        { "loudspeaker", "📢 Public Address Loudspeaker" },
        { "mega", "📣 Cheering Megaphone" },
        { "outbox_tray", "📤 Outbox Tray" },
        { "inbox_tray", "📥 Inbox Tray" },
        { "package", "📦 Package" },
        { "e-mail", "📧 E-Mail Symbol" },
        { "incoming_envelope", "📨 Incoming Envelope" },
        { "envelope_with_arrow", "📩 Envelope With Downwards Arrow Above" },
        { "mailbox_closed", "📪 Closed Mailbox With Lowered Flag" },
        { "mailbox", "📫 Closed Mailbox With Raised Flag" },
        { "mailbox_with_mail", "📬 Open Mailbox With Raised Flag" },
        { "mailbox_with_no_mail", "📭 Open Mailbox With Lowered Flag" },
        { "postbox", "📮 Postbox" },
        { "postal_horn", "📯 Postal Horn" },
        { "newspaper", "📰 Newspaper" },
        { "iphone", "📱 Mobile Phone" },
        { "calling", "📲 Mobile Phone With Rightwards Arrow At Left" },
        { "vibration_mode", "📳 Vibration Mode" },
        { "mobile_phone_off", "📴 Mobile Phone Off" },
        { "no_mobile_phones", "📵 No Mobile Phones" },
        { "signal_strength", "📶 Antenna With Bars" },
        { "camera", "📷 Camera" },
        { "camera_with_flash", "📸 Camera With Flash" },
        { "video_camera", "📹 Video Camera" },
        { "tv", "📺 Television" },
        { "radio", "📻 Radio" },
        { "vhs", "📼 Videocassette" },
        { "film_projector", "📽️ Film Projector" },
        { "prayer_beads", "📿 Prayer Beads" },
        { "twisted_rightwards_arrows", "🔀 Twisted Rightwards Arrows" },
        { "repeat", "🔁 Clockwise Rightwards And Leftwards Open Circle Arrows" },
        { "repeat_one", "🔂 Clockwise Rightwards And Leftwards Open Circle Arrows With Circled One Overlay" },
        { "arrows_clockwise", "🔃 Clockwise Downwards And Upwards Open Circle Arrows" },
        { "arrows_counterclockwise", "🔄 Anticlockwise Downwards And Upwards Open Circle Arrows" },
        { "low_brightness", "🔅 Low Brightness Symbol" },
        { "high_brightness", "🔆 High Brightness Symbol" },
        { "mute", "🔇 Speaker With Cancellation Stroke" },
        { "speaker", "🔈 Speaker" },
        { "sound", "🔉 Speaker With One Sound Wave" },
        { "loud_sound", "🔊 Speaker With Three Sound Waves" },
        { "battery", "🔋 Battery" },
        { "electric_plug", "🔌 Electric Plug" },
        { "mag", "🔍 Left-Pointing Magnifying Glass" },
        { "mag_right", "🔎 Right-Pointing Magnifying Glass" },
        { "lock_with_ink_pen", "🔏 Lock With Ink Pen" },
        { "closed_lock_with_key", "🔐 Closed Lock With Key" },
        { "key", "🔑 Key" },
        { "lock", "🔒 Lock" },
        { "unlock", "🔓 Open Lock" },
        { "bell", "🔔 Bell" },
        { "no_bell", "🔕 Bell With Cancellation Stroke" },
        { "bookmark", "🔖 Bookmark" },
        { "link", "🔗 Link Symbol" },
        { "radio_button", "🔘 Radio Button" },
        { "back", "🔙 Back With Leftwards Arrow Above" },
        { "end", "🔚 End With Leftwards Arrow Above" },
        { "on", "🔛 On With Exclamation Mark With Left Right Arrow Above" },
        { "soon", "🔜 Soon With Rightwards Arrow Above" },
        { "top", "🔝 Top With Upwards Arrow Above" },
        { "underage", "🔞 No One Under Eighteen Symbol" },
        { "keycap_ten", "🔟 Keycap Ten" },
        { "capital_abcd", "🔠 Input Symbol For Latin Capital Letters" },
        { "abcd", "🔡 Input Symbol For Latin Small Letters" },
        { "1234", "🔢 Input Symbol For Numbers" },
        { "symbols", "🔣 Input Symbol For Symbols" },
        { "abc", "🔤 Input Symbol For Latin Letters" },
        { "fire", "🔥 Fire" },
        { "flashlight", "🔦 Electric Torch" },
        { "wrench", "🔧 Wrench" },
        { "hammer", "🔨 Hammer" },
        { "nut_and_bolt", "🔩 Nut And Bolt" },
        { "hocho", "🔪 Hocho" },
        { "gun", "🔫 Pistol" },
        { "microscope", "🔬 Microscope" },
        { "telescope", "🔭 Telescope" },
        { "crystal_ball", "🔮 Crystal Ball" },
        { "six_pointed_star", "🔯 Six Pointed Star With Middle Dot" },
        { "beginner", "🔰 Japanese Symbol For Beginner" },
        { "trident", "🔱 Trident Emblem" },
        { "black_square_button", "🔲 Black Square Button" },
        { "white_square_button", "🔳 White Square Button" },
        { "red_circle", "🔴 Large Red Circle" },
        { "large_blue_circle", "🔵 Large Blue Circle" },
        { "large_orange_diamond", "🔶 Large Orange Diamond" },
        { "large_blue_diamond", "🔷 Large Blue Diamond" },
        { "small_orange_diamond", "🔸 Small Orange Diamond" },
        { "small_blue_diamond", "🔹 Small Blue Diamond" },
        { "small_red_triangle", "🔺 Up-Pointing Red Triangle" },
        { "small_red_triangle_down", "🔻 Down-Pointing Red Triangle" },
        { "arrow_up_small", "🔼 Up-Pointing Small Red Triangle" },
        { "arrow_down_small", "🔽 Down-Pointing Small Red Triangle" },
        { "om_symbol", "🕉️ Om" },
        { "dove_of_peace", "🕊️ Dove" },
        { "kaaba", "🕋 Kaaba" },
        { "mosque", "🕌 Mosque" },
        { "synagogue", "🕍 Synagogue" },
        { "menorah_with_nine_branches", "🕎 Menorah With Nine Branches" },
        { "clock1", "🕐 Clock Face One Oclock" },
        { "clock2", "🕑 Clock Face Two Oclock" },
        { "clock3", "🕒 Clock Face Three Oclock" },
        { "clock4", "🕓 Clock Face Four Oclock" },
        { "clock5", "🕔 Clock Face Five Oclock" },
        { "clock6", "🕕 Clock Face Six Oclock" },
        { "clock7", "🕖 Clock Face Seven Oclock" },
        { "clock8", "🕗 Clock Face Eight Oclock" },
        { "clock9", "🕘 Clock Face Nine Oclock" },
        { "clock10", "🕙 Clock Face Ten Oclock" },
        { "clock11", "🕚 Clock Face Eleven Oclock" },
        { "clock12", "🕛 Clock Face Twelve Oclock" },
        { "clock130", "🕜 Clock Face One-Thirty" },
        { "clock230", "🕝 Clock Face Two-Thirty" },
        { "clock330", "🕞 Clock Face Three-Thirty" },
        { "clock430", "🕟 Clock Face Four-Thirty" },
        { "clock530", "🕠 Clock Face Five-Thirty" },
        { "clock630", "🕡 Clock Face Six-Thirty" },
        { "clock730", "🕢 Clock Face Seven-Thirty" },
        { "clock830", "🕣 Clock Face Eight-Thirty" },
        { "clock930", "🕤 Clock Face Nine-Thirty" },
        { "clock1030", "🕥 Clock Face Ten-Thirty" },
        { "clock1130", "🕦 Clock Face Eleven-Thirty" },
        { "clock1230", "🕧 Clock Face Twelve-Thirty" },
        { "candle", "🕯️ Candle" },
        { "mantelpiece_clock", "🕰️ Mantelpiece Clock" },
        { "hole", "🕳️ Hole" },
        { "man_in_business_suit_levitating", "🕴️ Person In Suit Levitating" },
        { "female-detective", "🕵️‍♀️ Woman Detective" },
        { "male-detective", "🕵️‍♂️ Man Detective" },
        { "sleuth_or_spy", "🕵️ Detective" },
        { "dark_sunglasses", "🕶️ Sunglasses" },
        { "spider", "🕷️ Spider" },
        { "spider_web", "🕸️ Spider Web" },
        { "joystick", "🕹️ Joystick" },
        { "man_dancing", "🕺 Man Dancing" },
        { "linked_paperclips", "🖇️ Linked Paperclips" },
        { "lower_left_ballpoint_pen", "🖊️ Pen" },
        { "lower_left_fountain_pen", "🖋️ Fountain Pen" },
        { "lower_left_paintbrush", "🖌️ Paintbrush" },
        { "lower_left_crayon", "🖍️ Crayon" },
        { "raised_hand_with_fingers_splayed", "🖐️ Hand With Fingers Splayed" },
        { "middle_finger", "🖕 Reversed Hand With Middle Finger Extended" },
        { "spock-hand", "🖖 Raised Hand With Part Between Middle And Ring Fingers" },
        { "black_heart", "🖤 Black Heart" },
        { "desktop_computer", "🖥️ Desktop Computer" },
        { "printer", "🖨️ Printer" },
        { "three_button_mouse", "🖱️ Computer Mouse" },
        { "trackball", "🖲️ Trackball" },
        { "frame_with_picture", "🖼️ Framed Picture" },
        { "card_index_dividers", "🗂️ Card Index Dividers" },
        { "card_file_box", "🗃️ Card File Box" },
        { "file_cabinet", "🗄️ File Cabinet" },
        { "wastebasket", "🗑️ Wastebasket" },
        { "spiral_note_pad", "🗒️ Spiral Notepad" },
        { "spiral_calendar_pad", "🗓️ Spiral Calendar" },
        { "compression", "🗜️ Clamp" },
        { "old_key", "🗝️ Old Key" },
        { "rolled_up_newspaper", "🗞️ Rolled-Up Newspaper" },
        { "dagger_knife", "🗡️ Dagger" },
        { "speaking_head_in_silhouette", "🗣️ Speaking Head" },
        { "left_speech_bubble", "🗨️ Left Speech Bubble" },
        { "right_anger_bubble", "🗯️ Right Anger Bubble" },
        { "ballot_box_with_ballot", "🗳️ Ballot Box With Ballot" },
        { "world_map", "🗺️ World Map" },
        { "mount_fuji", "🗻 Mount Fuji" },
        { "tokyo_tower", "🗼 Tokyo Tower" },
        { "statue_of_liberty", "🗽 Statue Of Liberty" },
        { "japan", "🗾 Silhouette Of Japan" },
        { "moyai", "🗿 Moyai" },
        { "grinning", "😀 Grinning Face" },
        { "grin", "😁 Grinning Face With Smiling Eyes" },
        { "joy", "😂 Face With Tears Of Joy" },
        { "smiley", "😃 Smiling Face With Open Mouth" },
        { "smile", "😄 Smiling Face With Open Mouth And Smiling Eyes" },
        { "sweat_smile", "😅 Smiling Face With Open Mouth And Cold Sweat" },
        { "laughing", "😆 Smiling Face With Open Mouth And Tightly-Closed Eyes" },
        { "innocent", "😇 Smiling Face With Halo" },
        { "smiling_imp", "😈 Smiling Face With Horns" },
        { "wink", "😉 Winking Face" },
        { "blush", "😊 Smiling Face With Smiling Eyes" },
        { "yum", "😋 Face Savouring Delicious Food" },
        { "relieved", "😌 Relieved Face" },
        { "heart_eyes", "😍 Smiling Face With Heart-Shaped Eyes" },
        { "sunglasses", "😎 Smiling Face With Sunglasses" },
        { "smirk", "😏 Smirking Face" },
        { "neutral_face", "😐 Neutral Face" },
        { "expressionless", "😑 Expressionless Face" },
        { "unamused", "😒 Unamused Face" },
        { "sweat", "😓 Face With Cold Sweat" },
        { "pensive", "😔 Pensive Face" },
        { "confused", "😕 Confused Face" },
        { "confounded", "😖 Confounded Face" },
        { "kissing", "😗 Kissing Face" },
        { "kissing_heart", "😘 Face Throwing A Kiss" },
        { "kissing_smiling_eyes", "😙 Kissing Face With Smiling Eyes" },
        { "kissing_closed_eyes", "😚 Kissing Face With Closed Eyes" },
        { "stuck_out_tongue", "😛 Face With Stuck-Out Tongue" },
        { "stuck_out_tongue_winking_eye", "😜 Face With Stuck-Out Tongue And Winking Eye" },
        { "stuck_out_tongue_closed_eyes", "😝 Face With Stuck-Out Tongue And Tightly-Closed Eyes" },
        { "disappointed", "😞 Disappointed Face" },
        { "worried", "😟 Worried Face" },
        { "angry", "😠 Angry Face" },
        { "rage", "😡 Pouting Face" },
        { "cry", "😢 Crying Face" },
        { "persevere", "😣 Persevering Face" },
        { "triumph", "😤 Face With Look Of Triumph" },
        { "disappointed_relieved", "😥 Disappointed But Relieved Face" },
        { "frowning", "😦 Frowning Face With Open Mouth" },
        { "anguished", "😧 Anguished Face" },
        { "fearful", "😨 Fearful Face" },
        { "weary", "😩 Weary Face" },
        { "sleepy", "😪 Sleepy Face" },
        { "tired_face", "😫 Tired Face" },
        { "grimacing", "😬 Grimacing Face" },
        { "sob", "😭 Loudly Crying Face" },
        { "face_exhaling", "😮‍💨 Face Exhaling" },
        { "open_mouth", "😮 Face With Open Mouth" },
        { "hushed", "😯 Hushed Face" },
        { "cold_sweat", "😰 Face With Open Mouth And Cold Sweat" },
        { "scream", "😱 Face Screaming In Fear" },
        { "astonished", "😲 Astonished Face" },
        { "flushed", "😳 Flushed Face" },
        { "sleeping", "😴 Sleeping Face" },
        { "face_with_spiral_eyes", "😵‍💫 Face With Spiral Eyes" },
        { "dizzy_face", "😵 Dizzy Face" },
        { "face_in_clouds", "😶‍🌫️ Face In Clouds" },
        { "no_mouth", "😶 Face Without Mouth" },
        { "mask", "😷 Face With Medical Mask" },
        { "smile_cat", "😸 Grinning Cat Face With Smiling Eyes" },
        { "joy_cat", "😹 Cat Face With Tears Of Joy" },
        { "smiley_cat", "😺 Smiling Cat Face With Open Mouth" },
        { "heart_eyes_cat", "😻 Smiling Cat Face With Heart-Shaped Eyes" },
        { "smirk_cat", "😼 Cat Face With Wry Smile" },
        { "kissing_cat", "😽 Kissing Cat Face With Closed Eyes" },
        { "pouting_cat", "😾 Pouting Cat Face" },
        { "crying_cat_face", "😿 Crying Cat Face" },
        { "scream_cat", "🙀 Weary Cat Face" },
        { "slightly_frowning_face", "🙁 Slightly Frowning Face" },
        { "slightly_smiling_face", "🙂 Slightly Smiling Face" },
        { "upside_down_face", "🙃 Upside-Down Face" },
        { "face_with_rolling_eyes", "🙄 Face With Rolling Eyes" },
        { "woman-gesturing-no", "🙅‍♀️ Woman Gesturing No" },
        { "man-gesturing-no", "🙅‍♂️ Man Gesturing No" },
        { "no_good", "🙅 Face With No Good Gesture" },
        { "woman-gesturing-ok", "🙆‍♀️ Woman Gesturing Ok" },
        { "man-gesturing-ok", "🙆‍♂️ Man Gesturing Ok" },
        { "ok_woman", "🙆 Face With Ok Gesture" },
        { "woman-bowing", "🙇‍♀️ Woman Bowing" },
        { "man-bowing", "🙇‍♂️ Man Bowing" },
        { "bow", "🙇 Person Bowing Deeply" },
        { "see_no_evil", "🙈 See-No-Evil Monkey" },
        { "hear_no_evil", "🙉 Hear-No-Evil Monkey" },
        { "speak_no_evil", "🙊 Speak-No-Evil Monkey" },
        { "woman-raising-hand", "🙋‍♀️ Woman Raising Hand" },
        { "man-raising-hand", "🙋‍♂️ Man Raising Hand" },
        { "raising_hand", "🙋 Happy Person Raising One Hand" },
        { "raised_hands", "🙌 Person Raising Both Hands In Celebration" },
        { "woman-frowning", "🙍‍♀️ Woman Frowning" },
        { "man-frowning", "🙍‍♂️ Man Frowning" },
        { "person_frowning", "🙍 Person Frowning" },
        { "woman-pouting", "🙎‍♀️ Woman Pouting" },
        { "man-pouting", "🙎‍♂️ Man Pouting" },
        { "person_with_pouting_face", "🙎 Person With Pouting Face" },
        { "pray", "🙏 Person With Folded Hands" },
        { "rocket", "🚀 Rocket" },
        { "helicopter", "🚁 Helicopter" },
        { "steam_locomotive", "🚂 Steam Locomotive" },
        { "railway_car", "🚃 Railway Car" },
        { "bullettrain_side", "🚄 High-Speed Train" },
        { "bullettrain_front", "🚅 High-Speed Train With Bullet Nose" },
        { "train2", "🚆 Train" },
        { "metro", "🚇 Metro" },
        { "light_rail", "🚈 Light Rail" },
        { "station", "🚉 Station" },
        { "tram", "🚊 Tram" },
        { "train", "🚋 Tram Car" },
        { "bus", "🚌 Bus" },
        { "oncoming_bus", "🚍 Oncoming Bus" },
        { "trolleybus", "🚎 Trolleybus" },
        { "busstop", "🚏 Bus Stop" },
        { "minibus", "🚐 Minibus" },
        { "ambulance", "🚑 Ambulance" },
        { "fire_engine", "🚒 Fire Engine" },
        { "police_car", "🚓 Police Car" },
        { "oncoming_police_car", "🚔 Oncoming Police Car" },
        { "taxi", "🚕 Taxi" },
        { "oncoming_taxi", "🚖 Oncoming Taxi" },
        { "car", "🚗 Automobile" },
        { "oncoming_automobile", "🚘 Oncoming Automobile" },
        { "blue_car", "🚙 Recreational Vehicle" },
        { "truck", "🚚 Delivery Truck" },
        { "articulated_lorry", "🚛 Articulated Lorry" },
        { "tractor", "🚜 Tractor" },
        { "monorail", "🚝 Monorail" },
        { "mountain_railway", "🚞 Mountain Railway" },
        { "suspension_railway", "🚟 Suspension Railway" },
        { "mountain_cableway", "🚠 Mountain Cableway" },
        { "aerial_tramway", "🚡 Aerial Tramway" },
        { "ship", "🚢 Ship" },
        { "woman-rowing-boat", "🚣‍♀️ Woman Rowing Boat" },
        { "man-rowing-boat", "🚣‍♂️ Man Rowing Boat" },
        { "rowboat", "🚣 Rowboat" },
        { "speedboat", "🚤 Speedboat" },
        { "traffic_light", "🚥 Horizontal Traffic Light" },
        { "vertical_traffic_light", "🚦 Vertical Traffic Light" },
        { "construction", "🚧 Construction Sign" },
        { "rotating_light", "🚨 Police Cars Revolving Light" },
        { "triangular_flag_on_post", "🚩 Triangular Flag On Post" },
        { "door", "🚪 Door" },
        { "no_entry_sign", "🚫 No Entry Sign" },
        { "smoking", "🚬 Smoking Symbol" },
        { "no_smoking", "🚭 No Smoking Symbol" },
        { "put_litter_in_its_place", "🚮 Put Litter In Its Place Symbol" },
        { "do_not_litter", "🚯 Do Not Litter Symbol" },
        { "potable_water", "🚰 Potable Water Symbol" },
        { "non-potable_water", "🚱 Non-Potable Water Symbol" },
        { "bike", "🚲 Bicycle" },
        { "no_bicycles", "🚳 No Bicycles" },
        { "woman-biking", "🚴‍♀️ Woman Biking" },
        { "man-biking", "🚴‍♂️ Man Biking" },
        { "bicyclist", "🚴 Bicyclist" },
        { "woman-mountain-biking", "🚵‍♀️ Woman Mountain Biking" },
        { "man-mountain-biking", "🚵‍♂️ Man Mountain Biking" },
        { "mountain_bicyclist", "🚵 Mountain Bicyclist" },
        { "woman-walking", "🚶‍♀️ Woman Walking" },
        { "man-walking", "🚶‍♂️ Man Walking" },
        { "walking", "🚶 Pedestrian" },
        { "no_pedestrians", "🚷 No Pedestrians" },
        { "children_crossing", "🚸 Children Crossing" },
        { "mens", "🚹 Mens Symbol" },
        { "womens", "🚺 Womens Symbol" },
        { "restroom", "🚻 Restroom" },
        { "baby_symbol", "🚼 Baby Symbol" },
        { "toilet", "🚽 Toilet" },
        { "wc", "🚾 Water Closet" },
        { "shower", "🚿 Shower" },
        { "bath", "🛀 Bath" },
        { "bathtub", "🛁 Bathtub" },
        { "passport_control", "🛂 Passport Control" },
        { "customs", "🛃 Customs" },
        { "baggage_claim", "🛄 Baggage Claim" },
        { "left_luggage", "🛅 Left Luggage" },
        { "couch_and_lamp", "🛋️ Couch And Lamp" },
        { "sleeping_accommodation", "🛌 Sleeping Accommodation" },
        { "shopping_bags", "🛍️ Shopping Bags" },
        { "bellhop_bell", "🛎️ Bellhop Bell" },
        { "bed", "🛏️ Bed" },
        { "place_of_worship", "🛐 Place Of Worship" },
        { "octagonal_sign", "🛑 Octagonal Sign" },
        { "shopping_trolley", "🛒 Shopping Trolley" },
        { "hindu_temple", "🛕 Hindu Temple" },
        { "hut", "🛖 Hut" },
        { "elevator", "🛗 Elevator" },
        { "wireless", "🛜 Wireless" },
        { "playground_slide", "🛝 Playground Slide" },
        { "wheel", "🛞 Wheel" },
        { "ring_buoy", "🛟 Ring Buoy" },
        { "hammer_and_wrench", "🛠️ Hammer And Wrench" },
        { "shield", "🛡️ Shield" },
        { "oil_drum", "🛢️ Oil Drum" },
        { "motorway", "🛣️ Motorway" },
        { "railway_track", "🛤️ Railway Track" },
        { "motor_boat", "🛥️ Motor Boat" },
        { "small_airplane", "🛩️ Small Airplane" },
        { "airplane_departure", "🛫 Airplane Departure" },
        { "airplane_arriving", "🛬 Airplane Arriving" },
        { "satellite", "🛰️ Satellite" },
        { "passenger_ship", "🛳️ Passenger Ship" },
        { "scooter", "🛴 Scooter" },
        { "motor_scooter", "🛵 Motor Scooter" },
        { "canoe", "🛶 Canoe" },
        { "sled", "🛷 Sled" },
        { "flying_saucer", "🛸 Flying Saucer" },
        { "skateboard", "🛹 Skateboard" },
        { "auto_rickshaw", "🛺 Auto Rickshaw" },
        { "pickup_truck", "🛻 Pickup Truck" },
        { "roller_skate", "🛼 Roller Skate" },
        { "large_orange_circle", "🟠 Large Orange Circle" },
        { "large_yellow_circle", "🟡 Large Yellow Circle" },
        { "large_green_circle", "🟢 Large Green Circle" },
        { "large_purple_circle", "🟣 Large Purple Circle" },
        { "large_brown_circle", "🟤 Large Brown Circle" },
        { "large_red_square", "🟥 Large Red Square" },
        { "large_blue_square", "🟦 Large Blue Square" },
        { "large_orange_square", "🟧 Large Orange Square" },
        { "large_yellow_square", "🟨 Large Yellow Square" },
        { "large_green_square", "🟩 Large Green Square" },
        { "large_purple_square", "🟪 Large Purple Square" },
        { "large_brown_square", "🟫 Large Brown Square" },
        { "heavy_equals_sign", "🟰 Heavy Equals Sign" },
        { "pinched_fingers", "🤌 Pinched Fingers" },
        { "white_heart", "🤍 White Heart" },
        { "brown_heart", "🤎 Brown Heart" },
        { "pinching_hand", "🤏 Pinching Hand" },
        { "zipper_mouth_face", "🤐 Zipper-Mouth Face" },
        { "money_mouth_face", "🤑 Money-Mouth Face" },
        { "face_with_thermometer", "🤒 Face With Thermometer" },
        { "nerd_face", "🤓 Nerd Face" },
        { "thinking_face", "🤔 Thinking Face" },
        { "face_with_head_bandage", "🤕 Face With Head-Bandage" },
        { "robot_face", "🤖 Robot Face" },
        { "hugging_face", "🤗 Hugging Face" },
        { "the_horns", "🤘 Sign Of The Horns" },
        { "call_me_hand", "🤙 Call Me Hand" },
        { "raised_back_of_hand", "🤚 Raised Back Of Hand" },
        { "left-facing_fist", "🤛 Left-Facing Fist" },
        { "right-facing_fist", "🤜 Right-Facing Fist" },
        { "handshake", "🤝 Handshake" },
        { "crossed_fingers", "🤞 Hand With Index And Middle Fingers Crossed" },
        { "i_love_you_hand_sign", "🤟 I Love You Hand Sign" },
        { "face_with_cowboy_hat", "🤠 Face With Cowboy Hat" },
        { "clown_face", "🤡 Clown Face" },
        { "nauseated_face", "🤢 Nauseated Face" },
        { "rolling_on_the_floor_laughing", "🤣 Rolling On The Floor Laughing" },
        { "drooling_face", "🤤 Drooling Face" },
        { "lying_face", "🤥 Lying Face" },
        { "woman-facepalming", "🤦‍♀️ Woman Facepalming" },
        { "man-facepalming", "🤦‍♂️ Man Facepalming" },
        { "face_palm", "🤦 Face Palm" },
        { "sneezing_face", "🤧 Sneezing Face" },
        { "face_with_raised_eyebrow", "🤨 Face With One Eyebrow Raised" },
        { "star-struck", "🤩 Grinning Face With Star Eyes" },
        { "zany_face", "🤪 Grinning Face With One Large And One Small Eye" },
        { "shushing_face", "🤫 Face With Finger Covering Closed Lips" },
        { "face_with_symbols_on_mouth", "🤬 Serious Face With Symbols Covering Mouth" },
        { "face_with_hand_over_mouth", "🤭 Smiling Face With Smiling Eyes And Hand Covering Mouth" },
        { "face_vomiting", "🤮 Face With Open Mouth Vomiting" },
        { "exploding_head", "🤯 Shocked Face With Exploding Head" },
        { "pregnant_woman", "🤰 Pregnant Woman" },
        { "breast-feeding", "🤱 Breast-Feeding" },
        { "palms_up_together", "🤲 Palms Up Together" },
        { "selfie", "🤳 Selfie" },
        { "prince", "🤴 Prince" },
        { "woman_in_tuxedo", "🤵‍♀️ Woman In Tuxedo" },
        { "man_in_tuxedo", "🤵‍♂️ Man In Tuxedo" },
        { "person_in_tuxedo", "🤵 Man In Tuxedo" },
        { "mrs_claus", "🤶 Mother Christmas" },
        { "woman-shrugging", "🤷‍♀️ Woman Shrugging" },
        { "man-shrugging", "🤷‍♂️ Man Shrugging" },
        { "shrug", "🤷 Shrug" },
        { "woman-cartwheeling", "🤸‍♀️ Woman Cartwheeling" },
        { "man-cartwheeling", "🤸‍♂️ Man Cartwheeling" },
        { "person_doing_cartwheel", "🤸 Person Doing Cartwheel" },
        { "woman-juggling", "🤹‍♀️ Woman Juggling" },
        { "man-juggling", "🤹‍♂️ Man Juggling" },
        { "juggling", "🤹 Juggling" },
        { "fencer", "🤺 Fencer" },
        { "woman-wrestling", "🤼‍♀️ Women Wrestling" },
        { "man-wrestling", "🤼‍♂️ Men Wrestling" },
        { "wrestlers", "🤼 Wrestlers" },
        { "woman-playing-water-polo", "🤽‍♀️ Woman Playing Water Polo" },
        { "man-playing-water-polo", "🤽‍♂️ Man Playing Water Polo" },
        { "water_polo", "🤽 Water Polo" },
        { "woman-playing-handball", "🤾‍♀️ Woman Playing Handball" },
        { "man-playing-handball", "🤾‍♂️ Man Playing Handball" },
        { "handball", "🤾 Handball" },
        { "diving_mask", "🤿 Diving Mask" },
        { "wilted_flower", "🥀 Wilted Flower" },
        { "drum_with_drumsticks", "🥁 Drum With Drumsticks" },
        { "clinking_glasses", "🥂 Clinking Glasses" },
        { "tumbler_glass", "🥃 Tumbler Glass" },
        { "spoon", "🥄 Spoon" },
        { "goal_net", "🥅 Goal Net" },
        { "first_place_medal", "🥇 First Place Medal" },
        { "second_place_medal", "🥈 Second Place Medal" },
        { "third_place_medal", "🥉 Third Place Medal" },
        { "boxing_glove", "🥊 Boxing Glove" },
        { "martial_arts_uniform", "🥋 Martial Arts Uniform" },
        { "curling_stone", "🥌 Curling Stone" },
        { "lacrosse", "🥍 Lacrosse Stick And Ball" },
        { "softball", "🥎 Softball" },
        { "flying_disc", "🥏 Flying Disc" },
        { "croissant", "🥐 Croissant" },
        { "avocado", "🥑 Avocado" },
        { "cucumber", "🥒 Cucumber" },
        { "bacon", "🥓 Bacon" },
        { "potato", "🥔 Potato" },
        { "carrot", "🥕 Carrot" },
        { "baguette_bread", "🥖 Baguette Bread" },
        { "green_salad", "🥗 Green Salad" },
        { "shallow_pan_of_food", "🥘 Shallow Pan Of Food" },
        { "stuffed_flatbread", "🥙 Stuffed Flatbread" },
        { "egg", "🥚 Egg" },
        { "glass_of_milk", "🥛 Glass Of Milk" },
        { "peanuts", "🥜 Peanuts" },
        { "kiwifruit", "🥝 Kiwifruit" },
        { "pancakes", "🥞 Pancakes" },
        { "dumpling", "🥟 Dumpling" },
        { "fortune_cookie", "🥠 Fortune Cookie" },
        { "takeout_box", "🥡 Takeout Box" },
        { "chopsticks", "🥢 Chopsticks" },
        { "bowl_with_spoon", "🥣 Bowl With Spoon" },
        { "cup_with_straw", "🥤 Cup With Straw" },
        { "coconut", "🥥 Coconut" },
        { "broccoli", "🥦 Broccoli" },
        { "pie", "🥧 Pie" },
        { "pretzel", "🥨 Pretzel" },
        { "cut_of_meat", "🥩 Cut Of Meat" },
        { "sandwich", "🥪 Sandwich" },
        { "canned_food", "🥫 Canned Food" },
        { "leafy_green", "🥬 Leafy Green" },
        { "mango", "🥭 Mango" },
        { "moon_cake", "🥮 Moon Cake" },
        { "bagel", "🥯 Bagel" },
        { "smiling_face_with_3_hearts", "🥰 Smiling Face With Smiling Eyes And Three Hearts" },
        { "yawning_face", "🥱 Yawning Face" },
        { "smiling_face_with_tear", "🥲 Smiling Face With Tear" },
        { "partying_face", "🥳 Face With Party Horn And Party Hat" },
        { "woozy_face", "🥴 Face With Uneven Eyes And Wavy Mouth" },
        { "hot_face", "🥵 Overheated Face" },
        { "cold_face", "🥶 Freezing Face" },
        { "ninja", "🥷 Ninja" },
        { "disguised_face", "🥸 Disguised Face" },
        { "face_holding_back_tears", "🥹 Face Holding Back Tears" },
        { "pleading_face", "🥺 Face With Pleading Eyes" },
        { "sari", "🥻 Sari" },
        { "lab_coat", "🥼 Lab Coat" },
        { "goggles", "🥽 Goggles" },
        { "hiking_boot", "🥾 Hiking Boot" },
        { "womans_flat_shoe", "🥿 Flat Shoe" },
        { "crab", "🦀 Crab" },
        { "lion_face", "🦁 Lion Face" },
        { "scorpion", "🦂 Scorpion" },
        { "turkey", "🦃 Turkey" },
        { "unicorn_face", "🦄 Unicorn Face" },
        { "eagle", "🦅 Eagle" },
        { "duck", "🦆 Duck" },
        { "bat", "🦇 Bat" },
        { "shark", "🦈 Shark" },
        { "owl", "🦉 Owl" },
        { "fox_face", "🦊 Fox Face" },
        { "butterfly", "🦋 Butterfly" },
        { "deer", "🦌 Deer" },
        { "gorilla", "🦍 Gorilla" },
        { "lizard", "🦎 Lizard" },
        { "rhinoceros", "🦏 Rhinoceros" },
        { "shrimp", "🦐 Shrimp" },
        { "squid", "🦑 Squid" },
        { "giraffe_face", "🦒 Giraffe Face" },
        { "zebra_face", "🦓 Zebra Face" },
        { "hedgehog", "🦔 Hedgehog" },
        { "sauropod", "🦕 Sauropod" },
        { "t-rex", "🦖 T-Rex" },
        { "cricket", "🦗 Cricket" },
        { "kangaroo", "🦘 Kangaroo" },
        { "llama", "🦙 Llama" },
        { "peacock", "🦚 Peacock" },
        { "hippopotamus", "🦛 Hippopotamus" },
        { "parrot", "🦜 Parrot" },
        { "raccoon", "🦝 Raccoon" },
        { "lobster", "🦞 Lobster" },
        { "mosquito", "🦟 Mosquito" },
        { "microbe", "🦠 Microbe" },
        { "badger", "🦡 Badger" },
        { "swan", "🦢 Swan" },
        { "mammoth", "🦣 Mammoth" },
        { "dodo", "🦤 Dodo" },
        { "sloth", "🦥 Sloth" },
        { "otter", "🦦 Otter" },
        { "orangutan", "🦧 Orangutan" },
        { "skunk", "🦨 Skunk" },
        { "flamingo", "🦩 Flamingo" },
        { "oyster", "🦪 Oyster" },
        { "beaver", "🦫 Beaver" },
        { "bison", "🦬 Bison" },
        { "seal", "🦭 Seal" },
        { "guide_dog", "🦮 Guide Dog" },
        { "probing_cane", "🦯 Probing Cane" },
        { "bone", "🦴 Bone" },
        { "leg", "🦵 Leg" },
        { "foot", "🦶 Foot" },
        { "tooth", "🦷 Tooth" },
        { "female_superhero", "🦸‍♀️ Woman Superhero" },
        { "male_superhero", "🦸‍♂️ Man Superhero" },
        { "superhero", "🦸 Superhero" },
        { "female_supervillain", "🦹‍♀️ Woman Supervillain" },
        { "male_supervillain", "🦹‍♂️ Man Supervillain" },
        { "supervillain", "🦹 Supervillain" },
        { "safety_vest", "🦺 Safety Vest" },
        { "ear_with_hearing_aid", "🦻 Ear With Hearing Aid" },
        { "motorized_wheelchair", "🦼 Motorized Wheelchair" },
        { "manual_wheelchair", "🦽 Manual Wheelchair" },
        { "mechanical_arm", "🦾 Mechanical Arm" },
        { "mechanical_leg", "🦿 Mechanical Leg" },
        { "cheese_wedge", "🧀 Cheese Wedge" },
        { "cupcake", "🧁 Cupcake" },
        { "salt", "🧂 Salt Shaker" },
        { "beverage_box", "🧃 Beverage Box" },
        { "garlic", "🧄 Garlic" },
        { "onion", "🧅 Onion" },
        { "falafel", "🧆 Falafel" },
        { "waffle", "🧇 Waffle" },
        { "butter", "🧈 Butter" },
        { "mate_drink", "🧉 Mate Drink" },
        { "ice_cube", "🧊 Ice Cube" },
        { "bubble_tea", "🧋 Bubble Tea" },
        { "troll", "🧌 Troll" },
        { "woman_standing", "🧍‍♀️ Woman Standing" },
        { "man_standing", "🧍‍♂️ Man Standing" },
        { "standing_person", "🧍 Standing Person" },
        { "woman_kneeling", "🧎‍♀️ Woman Kneeling" },
        { "man_kneeling", "🧎‍♂️ Man Kneeling" },
        { "kneeling_person", "🧎 Kneeling Person" },
        { "deaf_woman", "🧏‍♀️ Deaf Woman" },
        { "deaf_man", "🧏‍♂️ Deaf Man" },
        { "deaf_person", "🧏 Deaf Person" },
        { "face_with_monocle", "🧐 Face With Monocle" },
        { "farmer", "🧑‍🌾 Farmer" },
        { "cook", "🧑‍🍳 Cook" },
        { "person_feeding_baby", "🧑‍🍼 Person Feeding Baby" },
        { "mx_claus", "🧑‍🎄 Mx Claus" },
        { "student", "🧑‍🎓 Student" },
        { "singer", "🧑‍🎤 Singer" },
        { "artist", "🧑‍🎨 Artist" },
        { "teacher", "🧑‍🏫 Teacher" },
        { "factory_worker", "🧑‍🏭 Factory Worker" },
        { "technologist", "🧑‍💻 Technologist" },
        { "office_worker", "🧑‍💼 Office Worker" },
        { "mechanic", "🧑‍🔧 Mechanic" },
        { "scientist", "🧑‍🔬 Scientist" },
        { "astronaut", "🧑‍🚀 Astronaut" },
        { "firefighter", "🧑‍🚒 Firefighter" },
        { "people_holding_hands", "🧑‍🤝‍🧑 People Holding Hands" },
        { "person_with_probing_cane", "🧑‍🦯 Person With White Cane" },
        { "red_haired_person", "🧑‍🦰 Person: Red Hair" },
        { "curly_haired_person", "🧑‍🦱 Person: Curly Hair" },
        { "bald_person", "🧑‍🦲 Person: Bald" },
        { "white_haired_person", "🧑‍🦳 Person: White Hair" },
        { "person_in_motorized_wheelchair", "🧑‍🦼 Person In Motorized Wheelchair" },
        { "person_in_manual_wheelchair", "🧑‍🦽 Person In Manual Wheelchair" },
        { "health_worker", "🧑‍⚕️ Health Worker" },
        { "judge", "🧑‍⚖️ Judge" },
        { "pilot", "🧑‍✈️ Pilot" },
        { "adult", "🧑 Adult" },
        { "child", "🧒 Child" },
        { "older_adult", "🧓 Older Adult" },
        { "woman_with_beard", "🧔‍♀️ Woman: Beard" },
        { "man_with_beard", "🧔‍♂️ Man: Beard" },
        { "bearded_person", "🧔 Bearded Person" },
        { "person_with_headscarf", "🧕 Person With Headscarf" },
        { "woman_in_steamy_room", "🧖‍♀️ Woman In Steamy Room" },
        { "man_in_steamy_room", "🧖‍♂️ Man In Steamy Room" },
        { "person_in_steamy_room", "🧖 Person In Steamy Room" },
        { "woman_climbing", "🧗‍♀️ Woman Climbing" },
        { "man_climbing", "🧗‍♂️ Man Climbing" },
        { "person_climbing", "🧗 Person Climbing" },
        { "woman_in_lotus_position", "🧘‍♀️ Woman In Lotus Position" },
        { "man_in_lotus_position", "🧘‍♂️ Man In Lotus Position" },
        { "person_in_lotus_position", "🧘 Person In Lotus Position" },
        { "female_mage", "🧙‍♀️ Woman Mage" },
        { "male_mage", "🧙‍♂️ Man Mage" },
        { "mage", "🧙 Mage" },
        { "female_fairy", "🧚‍♀️ Woman Fairy" },
        { "male_fairy", "🧚‍♂️ Man Fairy" },
        { "fairy", "🧚 Fairy" },
        { "female_vampire", "🧛‍♀️ Woman Vampire" },
        { "male_vampire", "🧛‍♂️ Man Vampire" },
        { "vampire", "🧛 Vampire" },
        { "mermaid", "🧜‍♀️ Mermaid" },
        { "merman", "🧜‍♂️ Merman" },
        { "merperson", "🧜 Merperson" },
        { "female_elf", "🧝‍♀️ Woman Elf" },
        { "male_elf", "🧝‍♂️ Man Elf" },
        { "elf", "🧝 Elf" },
        { "female_genie", "🧞‍♀️ Woman Genie" },
        { "male_genie", "🧞‍♂️ Man Genie" },
        { "genie", "🧞 Genie" },
        { "female_zombie", "🧟‍♀️ Woman Zombie" },
        { "male_zombie", "🧟‍♂️ Man Zombie" },
        { "zombie", "🧟 Zombie" },
        { "brain", "🧠 Brain" },
        { "orange_heart", "🧡 Orange Heart" },
        { "billed_cap", "🧢 Billed Cap" },
        { "scarf", "🧣 Scarf" },
        { "gloves", "🧤 Gloves" },
        { "coat", "🧥 Coat" },
        { "socks", "🧦 Socks" },
        { "red_envelope", "🧧 Red Gift Envelope" },
        { "firecracker", "🧨 Firecracker" },
        { "jigsaw", "🧩 Jigsaw Puzzle Piece" },
        { "test_tube", "🧪 Test Tube" },
        { "petri_dish", "🧫 Petri Dish" },
        { "dna", "🧬 Dna Double Helix" },
        { "compass", "🧭 Compass" },
        { "abacus", "🧮 Abacus" },
        { "fire_extinguisher", "🧯 Fire Extinguisher" },
        { "toolbox", "🧰 Toolbox" },
        { "bricks", "🧱 Brick" },
        { "magnet", "🧲 Magnet" },
        { "luggage", "🧳 Luggage" },
        { "lotion_bottle", "🧴 Lotion Bottle" },
        { "thread", "🧵 Spool Of Thread" },
        { "yarn", "🧶 Ball Of Yarn" },
        { "safety_pin", "🧷 Safety Pin" },
        { "teddy_bear", "🧸 Teddy Bear" },
        { "broom", "🧹 Broom" },
        { "basket", "🧺 Basket" },
        { "roll_of_paper", "🧻 Roll Of Paper" },
        { "soap", "🧼 Bar Of Soap" },
        { "sponge", "🧽 Sponge" },
        { "receipt", "🧾 Receipt" },
        { "nazar_amulet", "🧿 Nazar Amulet" },
        { "ballet_shoes", "🩰 Ballet Shoes" },
        { "one-piece_swimsuit", "🩱 One-Piece Swimsuit" },
        { "briefs", "🩲 Briefs" },
        { "shorts", "🩳 Shorts" },
        { "thong_sandal", "🩴 Thong Sandal" },
        { "light_blue_heart", "🩵 Light Blue Heart" },
        { "grey_heart", "🩶 Grey Heart" },
        { "pink_heart", "🩷 Pink Heart" },
        { "drop_of_blood", "🩸 Drop Of Blood" },
        { "adhesive_bandage", "🩹 Adhesive Bandage" },
        { "stethoscope", "🩺 Stethoscope" },
        { "x-ray", "🩻 X-Ray" },
        { "crutch", "🩼 Crutch" },
        { "yo-yo", "🪀 Yo-Yo" },
        { "kite", "🪁 Kite" },
        { "parachute", "🪂 Parachute" },
        { "boomerang", "🪃 Boomerang" },
        { "magic_wand", "🪄 Magic Wand" },
        { "pinata", "🪅 Pinata" },
        { "nesting_dolls", "🪆 Nesting Dolls" },
        { "maracas", "🪇 Maracas" },
        { "flute", "🪈 Flute" },
        { "ringed_planet", "🪐 Ringed Planet" },
        { "chair", "🪑 Chair" },
        { "razor", "🪒 Razor" },
        { "axe", "🪓 Axe" },
        { "diya_lamp", "🪔 Diya Lamp" },
        { "banjo", "🪕 Banjo" },
        { "military_helmet", "🪖 Military Helmet" },
        { "accordion", "🪗 Accordion" },
        { "long_drum", "🪘 Long Drum" },
        { "coin", "🪙 Coin" },
        { "carpentry_saw", "🪚 Carpentry Saw" },
        { "screwdriver", "🪛 Screwdriver" },
        { "ladder", "🪜 Ladder" },
        { "hook", "🪝 Hook" },
        { "mirror", "🪞 Mirror" },
        { "window", "🪟 Window" },
        { "plunger", "🪠 Plunger" },
        { "sewing_needle", "🪡 Sewing Needle" },
        { "knot", "🪢 Knot" },
        { "bucket", "🪣 Bucket" },
        { "mouse_trap", "🪤 Mouse Trap" },
        { "toothbrush", "🪥 Toothbrush" },
        { "headstone", "🪦 Headstone" },
        { "placard", "🪧 Placard" },
        { "rock", "🪨 Rock" },
        { "mirror_ball", "🪩 Mirror Ball" },
        { "identification_card", "🪪 Identification Card" },
        { "low_battery", "🪫 Low Battery" },
        { "hamsa", "🪬 Hamsa" },
        { "folding_hand_fan", "🪭 Folding Hand Fan" },
        { "hair_pick", "🪮 Hair Pick" },
        { "khanda", "🪯 Khanda" },
        { "fly", "🪰 Fly" },
        { "worm", "🪱 Worm" },
        { "beetle", "🪲 Beetle" },
        { "cockroach", "🪳 Cockroach" },
        { "potted_plant", "🪴 Potted Plant" },
        { "wood", "🪵 Wood" },
        { "feather", "🪶 Feather" },
        { "lotus", "🪷 Lotus" },
        { "coral", "🪸 Coral" },
        { "empty_nest", "🪹 Empty Nest" },
        { "nest_with_eggs", "🪺 Nest With Eggs" },
        { "hyacinth", "🪻 Hyacinth" },
        { "jellyfish", "🪼 Jellyfish" },
        { "wing", "🪽 Wing" },
        { "goose", "🪿 Goose" },
        { "anatomical_heart", "🫀 Anatomical Heart" },
        { "lungs", "🫁 Lungs" },
        { "people_hugging", "🫂 People Hugging" },
        { "pregnant_man", "🫃 Pregnant Man" },
        { "pregnant_person", "🫄 Pregnant Person" },
        { "person_with_crown", "🫅 Person With Crown" },
        { "moose", "🫎 Moose" },
        { "donkey", "🫏 Donkey" },
        { "blueberries", "🫐 Blueberries" },
        { "bell_pepper", "🫑 Bell Pepper" },
        { "olive", "🫒 Olive" },
        { "flatbread", "🫓 Flatbread" },
        { "tamale", "🫔 Tamale" },
        { "fondue", "🫕 Fondue" },
        { "teapot", "🫖 Teapot" },
        { "pouring_liquid", "🫗 Pouring Liquid" },
        { "beans", "🫘 Beans" },
        { "jar", "🫙 Jar" },
        { "ginger_root", "🫚 Ginger Root" },
        { "pea_pod", "🫛 Pea Pod" },
        { "melting_face", "🫠 Melting Face" },
        { "saluting_face", "🫡 Saluting Face" },
        { "face_with_open_eyes_and_hand_over_mouth", "🫢 Face With Open Eyes And Hand Over Mouth" },
        { "face_with_peeking_eye", "🫣 Face With Peeking Eye" },
        { "face_with_diagonal_mouth", "🫤 Face With Diagonal Mouth" },
        { "dotted_line_face", "🫥 Dotted Line Face" },
        { "biting_lip", "🫦 Biting Lip" },
        { "bubbles", "🫧 Bubbles" },
        { "shaking_face", "🫨 Shaking Face" },
        { "hand_with_index_finger_and_thumb_crossed", "🫰 Hand With Index Finger And Thumb Crossed" },
        { "rightwards_hand", "🫱 Rightwards Hand" },
        { "leftwards_hand", "🫲 Leftwards Hand" },
        { "palm_down_hand", "🫳 Palm Down Hand" },
        { "palm_up_hand", "🫴 Palm Up Hand" },
        { "index_pointing_at_the_viewer", "🫵 Index Pointing At The Viewer" },
        { "heart_hands", "🫶 Heart Hands" },
        { "leftwards_pushing_hand", "🫷 Leftwards Pushing Hand" },
        { "rightwards_pushing_hand", "🫸 Rightwards Pushing Hand" },
        { "bangbang", "‼️ Double Exclamation Mark" },
        { "interrobang", "⁉️ Exclamation Question Mark" },
        { "tm", "™️ Trade Mark Sign" },
        { "information_source", "ℹ️ Information Source" },
        { "left_right_arrow", "↔️ Left Right Arrow" },
        { "arrow_up_down", "↕️ Up Down Arrow" },
        { "arrow_upper_left", "↖️ North West Arrow" },
        { "arrow_upper_right", "↗️ North East Arrow" },
        { "arrow_lower_right", "↘️ South East Arrow" },
        { "arrow_lower_left", "↙️ South West Arrow" },
        { "leftwards_arrow_with_hook", "↩️ Leftwards Arrow With Hook" },
        { "arrow_right_hook", "↪️ Rightwards Arrow With Hook" },
        { "watch", "⌚ Watch" },
        { "hourglass", "⌛ Hourglass" },
        { "keyboard", "⌨️ Keyboard" },
        { "eject", "⏏️ Eject Button" },
        { "fast_forward", "⏩ Black Right-Pointing Double Triangle" },
        { "rewind", "⏪ Black Left-Pointing Double Triangle" },
        { "arrow_double_up", "⏫ Black Up-Pointing Double Triangle" },
        { "arrow_double_down", "⏬ Black Down-Pointing Double Triangle" },
        { "black_right_pointing_double_triangle_with_vertical_bar", "⏭️ Next Track Button" },
        { "black_left_pointing_double_triangle_with_vertical_bar", "⏮️ Last Track Button" },
        { "black_right_pointing_triangle_with_double_vertical_bar", "⏯️ Play Or Pause Button" },
        { "alarm_clock", "⏰ Alarm Clock" },
        { "stopwatch", "⏱️ Stopwatch" },
        { "timer_clock", "⏲️ Timer Clock" },
        { "hourglass_flowing_sand", "⏳ Hourglass With Flowing Sand" },
        { "double_vertical_bar", "⏸️ Pause Button" },
        { "black_square_for_stop", "⏹️ Stop Button" },
        { "black_circle_for_record", "⏺️ Record Button" },
        { "m", "Ⓜ️ Circled Latin Capital Letter M" },
        { "black_small_square", "▪️ Black Small Square" },
        { "white_small_square", "▫️ White Small Square" },
        { "arrow_forward", "▶️ Black Right-Pointing Triangle" },
        { "arrow_backward", "◀️ Black Left-Pointing Triangle" },
        { "white_medium_square", "◻️ White Medium Square" },
        { "black_medium_square", "◼️ Black Medium Square" },
        { "white_medium_small_square", "◽ White Medium Small Square" },
        { "black_medium_small_square", "◾ Black Medium Small Square" },
        { "sunny", "☀️ Black Sun With Rays" },
        { "cloud", "☁️ Cloud" },
        { "umbrella", "☂️ Umbrella" },
        { "snowman", "☃️ Snowman" },
        { "comet", "☄️ Comet" },
        { "phone", "☎️ Black Telephone" },
        { "ballot_box_with_check", "☑️ Ballot Box With Check" },
        { "umbrella_with_rain_drops", "☔ Umbrella With Rain Drops" },
        { "coffee", "☕ Hot Beverage" },
        { "shamrock", "☘️ Shamrock" },
        { "point_up", "☝️ White Up Pointing Index" },
        { "skull_and_crossbones", "☠️ Skull And Crossbones" },
        { "radioactive_sign", "☢️ Radioactive" },
        { "biohazard_sign", "☣️ Biohazard" },
        { "orthodox_cross", "☦️ Orthodox Cross" },
        { "star_and_crescent", "☪️ Star And Crescent" },
        { "peace_symbol", "☮️ Peace Symbol" },
        { "yin_yang", "☯️ Yin Yang" },
        { "wheel_of_dharma", "☸️ Wheel Of Dharma" },
        { "white_frowning_face", "☹️ Frowning Face" },
        { "relaxed", "☺️ White Smiling Face" },
        { "female_sign", "♀️ Female Sign" },
        { "male_sign", "♂️ Male Sign" },
        { "aries", "♈ Aries" },
        { "taurus", "♉ Taurus" },
        { "gemini", "♊ Gemini" },
        { "cancer", "♋ Cancer" },
        { "leo", "♌ Leo" },
        { "virgo", "♍ Virgo" },
        { "libra", "♎ Libra" },
        { "scorpius", "♏ Scorpius" },
        { "sagittarius", "♐ Sagittarius" },
        { "capricorn", "♑ Capricorn" },
        { "aquarius", "♒ Aquarius" },
        { "pisces", "♓ Pisces" },
        { "chess_pawn", "♟️ Chess Pawn" },
        { "spades", "♠️ Black Spade Suit" },
        { "clubs", "♣️ Black Club Suit" },
        { "hearts", "♥️ Black Heart Suit" },
        { "diamonds", "♦️ Black Diamond Suit" },
        { "hotsprings", "♨️ Hot Springs" },
        { "recycle", "♻️ Black Universal Recycling Symbol" },
        { "infinity", "♾️ Infinity" },
        { "wheelchair", "♿ Wheelchair Symbol" },
        { "hammer_and_pick", "⚒️ Hammer And Pick" },
        { "anchor", "⚓ Anchor" },
        { "crossed_swords", "⚔️ Crossed Swords" },
        { "medical_symbol", "⚕️ Medical Symbol" },
        { "scales", "⚖️ Balance Scale" },
        { "alembic", "⚗️ Alembic" },
        { "gear", "⚙️ Gear" },
        { "atom_symbol", "⚛️ Atom Symbol" },
        { "fleur_de_lis", "⚜️ Fleur-De-Lis" },
        { "warning", "⚠️ Warning Sign" },
        { "zap", "⚡ High Voltage Sign" },
        { "transgender_symbol", "⚧️ Transgender Symbol" },
        { "white_circle", "⚪ Medium White Circle" },
        { "black_circle", "⚫ Medium Black Circle" },
        { "coffin", "⚰️ Coffin" },
        { "funeral_urn", "⚱️ Funeral Urn" },
        { "soccer", "⚽ Soccer Ball" },
        { "baseball", "⚾ Baseball" },
        { "snowman_without_snow", "⛄ Snowman Without Snow" },
        { "partly_sunny", "⛅ Sun Behind Cloud" },
        { "thunder_cloud_and_rain", "⛈️ Cloud With Lightning And Rain" },
        { "ophiuchus", "⛎ Ophiuchus" },
        { "pick", "⛏️ Pick" },
        { "helmet_with_white_cross", "⛑️ Rescue Worker’S Helmet" },
        { "chains", "⛓️ Chains" },
        { "no_entry", "⛔ No Entry" },
        { "shinto_shrine", "⛩️ Shinto Shrine" },
        { "church", "⛪ Church" },
        { "mountain", "⛰️ Mountain" },
        { "umbrella_on_ground", "⛱️ Umbrella On Ground" },
        { "fountain", "⛲ Fountain" },
        { "golf", "⛳ Flag In Hole" },
        { "ferry", "⛴️ Ferry" },
        { "boat", "⛵ Sailboat" },
        { "skier", "⛷️ Skier" },
        { "ice_skate", "⛸️ Ice Skate" },
        { "woman-bouncing-ball", "⛹️‍♀️ Woman Bouncing Ball" },
        { "man-bouncing-ball", "⛹️‍♂️ Man Bouncing Ball" },
        { "person_with_ball", "⛹️ Person Bouncing Ball" },
        { "tent", "⛺ Tent" },
        { "fuelpump", "⛽ Fuel Pump" },
        { "scissors", "✂️ Black Scissors" },
        { "white_check_mark", "✅ White Heavy Check Mark" },
        { "airplane", "✈️ Airplane" },
        { "email", "✉️ Envelope" },
        { "fist", "✊ Raised Fist" },
        { "hand", "✋ Raised Hand" },
        { "v", "✌️ Victory Hand" },
        { "writing_hand", "✍️ Writing Hand" },
        { "pencil2", "✏️ Pencil" },
        { "black_nib", "✒️ Black Nib" },
        { "heavy_check_mark", "✔️ Heavy Check Mark" },
        { "heavy_multiplication_x", "✖️ Heavy Multiplication X" },
        { "latin_cross", "✝️ Latin Cross" },
        { "star_of_david", "✡️ Star Of David" },
        { "sparkles", "✨ Sparkles" },
        { "eight_spoked_asterisk", "✳️ Eight Spoked Asterisk" },
        { "eight_pointed_black_star", "✴️ Eight Pointed Black Star" },
        { "snowflake", "❄️ Snowflake" },
        { "sparkle", "❇️ Sparkle" },
        { "x", "❌ Cross Mark" },
        { "negative_squared_cross_mark", "❎ Negative Squared Cross Mark" },
        { "question", "❓ Black Question Mark Ornament" },
        { "grey_question", "❔ White Question Mark Ornament" },
        { "grey_exclamation", "❕ White Exclamation Mark Ornament" },
        { "exclamation", "❗ Heavy Exclamation Mark Symbol" },
        { "heavy_heart_exclamation_mark_ornament", "❣️ Heart Exclamation" },
        { "heart_on_fire", "❤️‍🔥 Heart On Fire" },
        { "mending_heart", "❤️‍🩹 Mending Heart" },
        { "heart", "❤️ Heavy Black Heart" },
        { "heavy_plus_sign", "➕ Heavy Plus Sign" },
        { "heavy_minus_sign", "➖ Heavy Minus Sign" },
        { "heavy_division_sign", "➗ Heavy Division Sign" },
        { "arrow_right", "➡️ Black Rightwards Arrow" },
        { "curly_loop", "➰ Curly Loop" },
        { "loop", "➿ Double Curly Loop" },
        { "arrow_heading_up", "⤴️ Arrow Pointing Rightwards Then Curving Upwards" },
        { "arrow_heading_down", "⤵️ Arrow Pointing Rightwards Then Curving Downwards" },
        { "arrow_left", "⬅️ Leftwards Black Arrow" },
        { "arrow_up", "⬆️ Upwards Black Arrow" },
        { "arrow_down", "⬇️ Downwards Black Arrow" },
        { "black_large_square", "⬛ Black Large Square" },
        { "white_large_square", "⬜ White Large Square" },
        { "star", "⭐ White Medium Star" },
        { "o", "⭕ Heavy Large Circle" },
        { "wavy_dash", "〰️ Wavy Dash" },
        { "part_alternation_mark", "〽️ Part Alternation Mark" },
        { "congratulations", "㊗️ Circled Ideograph Congratulation" },
        { "secret", "㊙️ Circled Ideograph Secret" },
    };
}