using Blackbird.Applications.Sdk.Common;
using Blackbird.Applications.Sdk.Common.Dynamic;
using Blackbird.Applications.Sdk.Common.Invocation;
using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.Slack.DataSourceHandlers;

public class EmojiHandler : IDataSourceHandler
{

    public Dictionary<string, string> GetData(DataSourceContext context)
    {
        var data = new Dictionary<string, string> {            
            { "bird", "🐦 Bird" },
            { "white_check_mark", "✅ White heavy check mark" },
            { "eyes", "👀 Eyes" },
            { "raised_hands", "🙌 Person raising both hands in celebration" },
            { "joy", "😂 Face with tears of joy" },
            { "slightly_smiling_face", "🙂 Slightly smiling face" },
            { "smiley", "😃 Smiling face with open mouth" },
            { "wave", "👋 Waving hand sign" },
            { "ok_hand", "👌 Ok hand sign" },
            { "+1", "👍 Thumbs up sign" },
            { "-1", "👎 Thumbs down sign" },
            { "clap", "👏 Clapping hands sign" },
            { "hash", "#️⃣ Hash key" },
            { "keycap_star", "*️⃣ Keycap: *" },
            { "zero", "0️⃣ Keycap 0" },
            { "one", "1️⃣ Keycap 1" },
            { "two", "2️⃣ Keycap 2" },
            { "three", "3️⃣ Keycap 3" },
            { "four", "4️⃣ Keycap 4" },
            { "five", "5️⃣ Keycap 5" },
            { "six", "6️⃣ Keycap 6" },
            { "seven", "7️⃣ Keycap 7" },
            { "eight", "8️⃣ Keycap 8" },
            { "nine", "9️⃣ Keycap 9" },
            { "copyright", "©️ Copyright sign" },
            { "registered", "®️ Registered sign" },
            { "mahjong", "🀄 Mahjong tile red dragon" },
            { "black_joker", "🃏 Playing card black joker" },
            { "a", "🅰️ Negative squared latin capital letter a" },
            { "b", "🅱️ Negative squared latin capital letter b" },
            { "o2", "🅾️ Negative squared latin capital letter o" },
            { "parking", "🅿️ Negative squared latin capital letter p" },
            { "ab", "🆎 Negative squared ab" },
            { "cl", "🆑 Squared cl" },
            { "cool", "🆒 Squared cool" },
            { "free", "🆓 Squared free" },
            { "id", "🆔 Squared id" },
            { "new", "🆕 Squared new" },
            { "ng", "🆖 Squared ng" },
            { "ok", "🆗 Squared ok" },
            { "sos", "🆘 Squared sos" },
            { "up", "🆙 Squared up with exclamation mark" },
            { "vs", "🆚 Squared vs" },
            { "flag-ac", "🇦🇨 Ascension island flag" },
            { "flag-ad", "🇦🇩 Andorra flag" },
            { "flag-ae", "🇦🇪 United arab emirates flag" },
            { "flag-af", "🇦🇫 Afghanistan flag" },
            { "flag-ag", "🇦🇬 Antigua & barbuda flag" },
            { "flag-ai", "🇦🇮 Anguilla flag" },
            { "flag-al", "🇦🇱 Albania flag" },
            { "flag-am", "🇦🇲 Armenia flag" },
            { "flag-ao", "🇦🇴 Angola flag" },
            { "flag-aq", "🇦🇶 Antarctica flag" },
            { "flag-ar", "🇦🇷 Argentina flag" },
            { "flag-as", "🇦🇸 American samoa flag" },
            { "flag-at", "🇦🇹 Austria flag" },
            { "flag-au", "🇦🇺 Australia flag" },
            { "flag-aw", "🇦🇼 Aruba flag" },
            { "flag-ax", "🇦🇽 Åland islands flag" },
            { "flag-az", "🇦🇿 Azerbaijan flag" },
            { "flag-ba", "🇧🇦 Bosnia & herzegovina flag" },
            { "flag-bb", "🇧🇧 Barbados flag" },
            { "flag-bd", "🇧🇩 Bangladesh flag" },
            { "flag-be", "🇧🇪 Belgium flag" },
            { "flag-bf", "🇧🇫 Burkina faso flag" },
            { "flag-bg", "🇧🇬 Bulgaria flag" },
            { "flag-bh", "🇧🇭 Bahrain flag" },
            { "flag-bi", "🇧🇮 Burundi flag" },
            { "flag-bj", "🇧🇯 Benin flag" },
            { "flag-bl", "🇧🇱 St. barthélemy flag" },
            { "flag-bm", "🇧🇲 Bermuda flag" },
            { "flag-bn", "🇧🇳 Brunei flag" },
            { "flag-bo", "🇧🇴 Bolivia flag" },
            { "flag-bq", "🇧🇶 Caribbean netherlands flag" },
            { "flag-br", "🇧🇷 Brazil flag" },
            { "flag-bs", "🇧🇸 Bahamas flag" },
            { "flag-bt", "🇧🇹 Bhutan flag" },
            { "flag-bv", "🇧🇻 Bouvet island flag" },
            { "flag-bw", "🇧🇼 Botswana flag" },
            { "flag-by", "🇧🇾 Belarus flag" },
            { "flag-bz", "🇧🇿 Belize flag" },
            { "flag-ca", "🇨🇦 Canada flag" },
            { "flag-cc", "🇨🇨 Cocos (keeling) islands flag" },
            { "flag-cd", "🇨🇩 Congo - kinshasa flag" },
            { "flag-cf", "🇨🇫 Central african republic flag" },
            { "flag-cg", "🇨🇬 Congo - brazzaville flag" },
            { "flag-ch", "🇨🇭 Switzerland flag" },
            { "flag-ci", "🇨🇮 Côte d’ivoire flag" },
            { "flag-ck", "🇨🇰 Cook islands flag" },
            { "flag-cl", "🇨🇱 Chile flag" },
            { "flag-cm", "🇨🇲 Cameroon flag" },
            { "cn", "🇨🇳 China flag" },
            { "flag-co", "🇨🇴 Colombia flag" },
            { "flag-cp", "🇨🇵 Clipperton island flag" },
            { "flag-cr", "🇨🇷 Costa rica flag" },
            { "flag-cu", "🇨🇺 Cuba flag" },
            { "flag-cv", "🇨🇻 Cape verde flag" },
            { "flag-cw", "🇨🇼 Curaçao flag" },
            { "flag-cx", "🇨🇽 Christmas island flag" },
            { "flag-cy", "🇨🇾 Cyprus flag" },
            { "flag-cz", "🇨🇿 Czechia flag" },
            { "de", "🇩🇪 Germany flag" },
            { "flag-dg", "🇩🇬 Diego garcia flag" },
            { "flag-dj", "🇩🇯 Djibouti flag" },
            { "flag-dk", "🇩🇰 Denmark flag" },
            { "flag-dm", "🇩🇲 Dominica flag" },
            { "flag-do", "🇩🇴 Dominican republic flag" },
            { "flag-dz", "🇩🇿 Algeria flag" },
            { "flag-ea", "🇪🇦 Ceuta & melilla flag" },
            { "flag-ec", "🇪🇨 Ecuador flag" },
            { "flag-ee", "🇪🇪 Estonia flag" },
            { "flag-eg", "🇪🇬 Egypt flag" },
            { "flag-eh", "🇪🇭 Western sahara flag" },
            { "flag-er", "🇪🇷 Eritrea flag" },
            { "es", "🇪🇸 Spain flag" },
            { "flag-et", "🇪🇹 Ethiopia flag" },
            { "flag-eu", "🇪🇺 European union flag" },
            { "flag-fi", "🇫🇮 Finland flag" },
            { "flag-fj", "🇫🇯 Fiji flag" },
            { "flag-fk", "🇫🇰 Falkland islands flag" },
            { "flag-fm", "🇫🇲 Micronesia flag" },
            { "flag-fo", "🇫🇴 Faroe islands flag" },
            { "fr", "🇫🇷 France flag" },
            { "flag-ga", "🇬🇦 Gabon flag" },
            { "gb", "🇬🇧 United kingdom flag" },
            { "flag-gd", "🇬🇩 Grenada flag" },
            { "flag-ge", "🇬🇪 Georgia flag" },
            { "flag-gf", "🇬🇫 French guiana flag" },
            { "flag-gg", "🇬🇬 Guernsey flag" },
            { "flag-gh", "🇬🇭 Ghana flag" },
            { "flag-gi", "🇬🇮 Gibraltar flag" },
            { "flag-gl", "🇬🇱 Greenland flag" },
            { "flag-gm", "🇬🇲 Gambia flag" },
            { "flag-gn", "🇬🇳 Guinea flag" },
            { "flag-gp", "🇬🇵 Guadeloupe flag" },
            { "flag-gq", "🇬🇶 Equatorial guinea flag" },
            { "flag-gr", "🇬🇷 Greece flag" },
            { "flag-gs", "🇬🇸 South georgia & south sandwich islands flag" },
            { "flag-gt", "🇬🇹 Guatemala flag" },
            { "flag-gu", "🇬🇺 Guam flag" },
            { "flag-gw", "🇬🇼 Guinea-bissau flag" },
            { "flag-gy", "🇬🇾 Guyana flag" },
            { "flag-hk", "🇭🇰 Hong kong sar china flag" },
            { "flag-hm", "🇭🇲 Heard & mcdonald islands flag" },
            { "flag-hn", "🇭🇳 Honduras flag" },
            { "flag-hr", "🇭🇷 Croatia flag" },
            { "flag-ht", "🇭🇹 Haiti flag" },
            { "flag-hu", "🇭🇺 Hungary flag" },
            { "flag-ic", "🇮🇨 Canary islands flag" },
            { "flag-id", "🇮🇩 Indonesia flag" },
            { "flag-ie", "🇮🇪 Ireland flag" },
            { "flag-il", "🇮🇱 Israel flag" },
            { "flag-im", "🇮🇲 Isle of man flag" },
            { "flag-in", "🇮🇳 India flag" },
            { "flag-io", "🇮🇴 British indian ocean territory flag" },
            { "flag-iq", "🇮🇶 Iraq flag" },
            { "flag-ir", "🇮🇷 Iran flag" },
            { "flag-is", "🇮🇸 Iceland flag" },
            { "it", "🇮🇹 Italy flag" },
            { "flag-je", "🇯🇪 Jersey flag" },
            { "flag-jm", "🇯🇲 Jamaica flag" },
            { "flag-jo", "🇯🇴 Jordan flag" },
            { "jp", "🇯🇵 Japan flag" },
            { "flag-ke", "🇰🇪 Kenya flag" },
            { "flag-kg", "🇰🇬 Kyrgyzstan flag" },
            { "flag-kh", "🇰🇭 Cambodia flag" },
            { "flag-ki", "🇰🇮 Kiribati flag" },
            { "flag-km", "🇰🇲 Comoros flag" },
            { "flag-kn", "🇰🇳 St. kitts & nevis flag" },
            { "flag-kp", "🇰🇵 North korea flag" },
            { "kr", "🇰🇷 South korea flag" },
            { "flag-kw", "🇰🇼 Kuwait flag" },
            { "flag-ky", "🇰🇾 Cayman islands flag" },
            { "flag-kz", "🇰🇿 Kazakhstan flag" },
            { "flag-la", "🇱🇦 Laos flag" },
            { "flag-lb", "🇱🇧 Lebanon flag" },
            { "flag-lc", "🇱🇨 St. lucia flag" },
            { "flag-li", "🇱🇮 Liechtenstein flag" },
            { "flag-lk", "🇱🇰 Sri lanka flag" },
            { "flag-lr", "🇱🇷 Liberia flag" },
            { "flag-ls", "🇱🇸 Lesotho flag" },
            { "flag-lt", "🇱🇹 Lithuania flag" },
            { "flag-lu", "🇱🇺 Luxembourg flag" },
            { "flag-lv", "🇱🇻 Latvia flag" },
            { "flag-ly", "🇱🇾 Libya flag" },
            { "flag-ma", "🇲🇦 Morocco flag" },
            { "flag-mc", "🇲🇨 Monaco flag" },
            { "flag-md", "🇲🇩 Moldova flag" },
            { "flag-me", "🇲🇪 Montenegro flag" },
            { "flag-mf", "🇲🇫 St. martin flag" },
            { "flag-mg", "🇲🇬 Madagascar flag" },
            { "flag-mh", "🇲🇭 Marshall islands flag" },
            { "flag-mk", "🇲🇰 North macedonia flag" },
            { "flag-ml", "🇲🇱 Mali flag" },
            { "flag-mm", "🇲🇲 Myanmar (burma) flag" },
            { "flag-mn", "🇲🇳 Mongolia flag" },
            { "flag-mo", "🇲🇴 Macao sar china flag" },
            { "flag-mp", "🇲🇵 Northern mariana islands flag" },
            { "flag-mq", "🇲🇶 Martinique flag" },
            { "flag-mr", "🇲🇷 Mauritania flag" },
            { "flag-ms", "🇲🇸 Montserrat flag" },
            { "flag-mt", "🇲🇹 Malta flag" },
            { "flag-mu", "🇲🇺 Mauritius flag" },
            { "flag-mv", "🇲🇻 Maldives flag" },
            { "flag-mw", "🇲🇼 Malawi flag" },
            { "flag-mx", "🇲🇽 Mexico flag" },
            { "flag-my", "🇲🇾 Malaysia flag" },
            { "flag-mz", "🇲🇿 Mozambique flag" },
            { "flag-na", "🇳🇦 Namibia flag" },
            { "flag-nc", "🇳🇨 New caledonia flag" },
            { "flag-ne", "🇳🇪 Niger flag" },
            { "flag-nf", "🇳🇫 Norfolk island flag" },
            { "flag-ng", "🇳🇬 Nigeria flag" },
            { "flag-ni", "🇳🇮 Nicaragua flag" },
            { "flag-nl", "🇳🇱 Netherlands flag" },
            { "flag-no", "🇳🇴 Norway flag" },
            { "flag-np", "🇳🇵 Nepal flag" },
            { "flag-nr", "🇳🇷 Nauru flag" },
            { "flag-nu", "🇳🇺 Niue flag" },
            { "flag-nz", "🇳🇿 New zealand flag" },
            { "flag-om", "🇴🇲 Oman flag" },
            { "flag-pa", "🇵🇦 Panama flag" },
            { "flag-pe", "🇵🇪 Peru flag" },
            { "flag-pf", "🇵🇫 French polynesia flag" },
            { "flag-pg", "🇵🇬 Papua new guinea flag" },
            { "flag-ph", "🇵🇭 Philippines flag" },
            { "flag-pk", "🇵🇰 Pakistan flag" },
            { "flag-pl", "🇵🇱 Poland flag" },
            { "flag-pm", "🇵🇲 St. pierre & miquelon flag" },
            { "flag-pn", "🇵🇳 Pitcairn islands flag" },
            { "flag-pr", "🇵🇷 Puerto rico flag" },
            { "flag-ps", "🇵🇸 Palestinian territories flag" },
            { "flag-pt", "🇵🇹 Portugal flag" },
            { "flag-pw", "🇵🇼 Palau flag" },
            { "flag-py", "🇵🇾 Paraguay flag" },
            { "flag-qa", "🇶🇦 Qatar flag" },
            { "flag-re", "🇷🇪 Réunion flag" },
            { "flag-ro", "🇷🇴 Romania flag" },
            { "flag-rs", "🇷🇸 Serbia flag" },
            { "ru", "🇷🇺 Russia flag" },
            { "flag-rw", "🇷🇼 Rwanda flag" },
            { "flag-sa", "🇸🇦 Saudi arabia flag" },
            { "flag-sb", "🇸🇧 Solomon islands flag" },
            { "flag-sc", "🇸🇨 Seychelles flag" },
            { "flag-sd", "🇸🇩 Sudan flag" },
            { "flag-se", "🇸🇪 Sweden flag" },
            { "flag-sg", "🇸🇬 Singapore flag" },
            { "flag-sh", "🇸🇭 St. helena flag" },
            { "flag-si", "🇸🇮 Slovenia flag" },
            { "flag-sj", "🇸🇯 Svalbard & jan mayen flag" },
            { "flag-sk", "🇸🇰 Slovakia flag" },
            { "flag-sl", "🇸🇱 Sierra leone flag" },
            { "flag-sm", "🇸🇲 San marino flag" },
            { "flag-sn", "🇸🇳 Senegal flag" },
            { "flag-so", "🇸🇴 Somalia flag" },
            { "flag-sr", "🇸🇷 Suriname flag" },
            { "flag-ss", "🇸🇸 South sudan flag" },
            { "flag-st", "🇸🇹 São tomé & príncipe flag" },
            { "flag-sv", "🇸🇻 El salvador flag" },
            { "flag-sx", "🇸🇽 Sint maarten flag" },
            { "flag-sy", "🇸🇾 Syria flag" },
            { "flag-sz", "🇸🇿 Eswatini flag" },
            { "flag-ta", "🇹🇦 Tristan da cunha flag" },
            { "flag-tc", "🇹🇨 Turks & caicos islands flag" },
            { "flag-td", "🇹🇩 Chad flag" },
            { "flag-tf", "🇹🇫 French southern territories flag" },
            { "flag-tg", "🇹🇬 Togo flag" },
            { "flag-th", "🇹🇭 Thailand flag" },
            { "flag-tj", "🇹🇯 Tajikistan flag" },
            { "flag-tk", "🇹🇰 Tokelau flag" },
            { "flag-tl", "🇹🇱 Timor-leste flag" },
            { "flag-tm", "🇹🇲 Turkmenistan flag" },
            { "flag-tn", "🇹🇳 Tunisia flag" },
            { "flag-to", "🇹🇴 Tonga flag" },
            { "flag-tr", "🇹🇷 Turkey flag" },
            { "flag-tt", "🇹🇹 Trinidad & tobago flag" },
            { "flag-tv", "🇹🇻 Tuvalu flag" },
            { "flag-tw", "🇹🇼 Taiwan flag" },
            { "flag-tz", "🇹🇿 Tanzania flag" },
            { "flag-ua", "🇺🇦 Ukraine flag" },
            { "flag-ug", "🇺🇬 Uganda flag" },
            { "flag-um", "🇺🇲 U.s. outlying islands flag" },
            { "flag-un", "🇺🇳 United nations flag" },
            { "us", "🇺🇸 United states flag" },
            { "flag-uy", "🇺🇾 Uruguay flag" },
            { "flag-uz", "🇺🇿 Uzbekistan flag" },
            { "flag-va", "🇻🇦 Vatican city flag" },
            { "flag-vc", "🇻🇨 St. vincent & grenadines flag" },
            { "flag-ve", "🇻🇪 Venezuela flag" },
            { "flag-vg", "🇻🇬 British virgin islands flag" },
            { "flag-vi", "🇻🇮 U.s. virgin islands flag" },
            { "flag-vn", "🇻🇳 Vietnam flag" },
            { "flag-vu", "🇻🇺 Vanuatu flag" },
            { "flag-wf", "🇼🇫 Wallis & futuna flag" },
            { "flag-ws", "🇼🇸 Samoa flag" },
            { "flag-xk", "🇽🇰 Kosovo flag" },
            { "flag-ye", "🇾🇪 Yemen flag" },
            { "flag-yt", "🇾🇹 Mayotte flag" },
            { "flag-za", "🇿🇦 South africa flag" },
            { "flag-zm", "🇿🇲 Zambia flag" },
            { "flag-zw", "🇿🇼 Zimbabwe flag" },
            { "koko", "🈁 Squared katakana koko" },
            { "sa", "🈂️ Squared katakana sa" },
            { "u7121", "🈚 Squared cjk unified ideograph-7121" },
            { "u6307", "🈯 Squared cjk unified ideograph-6307" },
            { "u7981", "🈲 Squared cjk unified ideograph-7981" },
            { "u7a7a", "🈳 Squared cjk unified ideograph-7a7a" },
            { "u5408", "🈴 Squared cjk unified ideograph-5408" },
            { "u6e80", "🈵 Squared cjk unified ideograph-6e80" },
            { "u6709", "🈶 Squared cjk unified ideograph-6709" },
            { "u6708", "🈷️ Squared cjk unified ideograph-6708" },
            { "u7533", "🈸 Squared cjk unified ideograph-7533" },
            { "u5272", "🈹 Squared cjk unified ideograph-5272" },
            { "u55b6", "🈺 Squared cjk unified ideograph-55b6" },
            { "ideograph_advantage", "🉐 Circled ideograph advantage" },
            { "accept", "🉑 Circled ideograph accept" },
            { "cyclone", "🌀 Cyclone" },
            { "foggy", "🌁 Foggy" },
            { "closed_umbrella", "🌂 Closed umbrella" },
            { "night_with_stars", "🌃 Night with stars" },
            { "sunrise_over_mountains", "🌄 Sunrise over mountains" },
            { "sunrise", "🌅 Sunrise" },
            { "city_sunset", "🌆 Cityscape at dusk" },
            { "city_sunrise", "🌇 Sunset over buildings" },
            { "rainbow", "🌈 Rainbow" },
            { "bridge_at_night", "🌉 Bridge at night" },
            { "ocean", "🌊 Water wave" },
            { "volcano", "🌋 Volcano" },
            { "milky_way", "🌌 Milky way" },
            { "earth_africa", "🌍 Earth globe europe-africa" },
            { "earth_americas", "🌎 Earth globe americas" },
            { "earth_asia", "🌏 Earth globe asia-australia" },
            { "globe_with_meridians", "🌐 Globe with meridians" },
            { "new_moon", "🌑 New moon symbol" },
            { "waxing_crescent_moon", "🌒 Waxing crescent moon symbol" },
            { "first_quarter_moon", "🌓 First quarter moon symbol" },
            { "moon", "🌔 Waxing gibbous moon symbol" },
            { "full_moon", "🌕 Full moon symbol" },
            { "waning_gibbous_moon", "🌖 Waning gibbous moon symbol" },
            { "last_quarter_moon", "🌗 Last quarter moon symbol" },
            { "waning_crescent_moon", "🌘 Waning crescent moon symbol" },
            { "crescent_moon", "🌙 Crescent moon" },
            { "new_moon_with_face", "🌚 New moon with face" },
            { "first_quarter_moon_with_face", "🌛 First quarter moon with face" },
            { "last_quarter_moon_with_face", "🌜 Last quarter moon with face" },
            { "full_moon_with_face", "🌝 Full moon with face" },
            { "sun_with_face", "🌞 Sun with face" },
            { "star2", "🌟 Glowing star" },
            { "stars", "🌠 Shooting star" },
            { "thermometer", "🌡️ Thermometer" },
            { "mostly_sunny", "🌤️ Sun behind small cloud" },
            { "barely_sunny", "🌥️ Sun behind large cloud" },
            { "partly_sunny_rain", "🌦️ Sun behind rain cloud" },
            { "rain_cloud", "🌧️ Cloud with rain" },
            { "snow_cloud", "🌨️ Cloud with snow" },
            { "lightning", "🌩️ Cloud with lightning" },
            { "tornado", "🌪️ Tornado" },
            { "fog", "🌫️ Fog" },
            { "wind_blowing_face", "🌬️ Wind face" },
            { "hotdog", "🌭 Hot dog" },
            { "taco", "🌮 Taco" },
            { "burrito", "🌯 Burrito" },
            { "chestnut", "🌰 Chestnut" },
            { "seedling", "🌱 Seedling" },
            { "evergreen_tree", "🌲 Evergreen tree" },
            { "deciduous_tree", "🌳 Deciduous tree" },
            { "palm_tree", "🌴 Palm tree" },
            { "cactus", "🌵 Cactus" },
            { "hot_pepper", "🌶️ Hot pepper" },
            { "tulip", "🌷 Tulip" },
            { "cherry_blossom", "🌸 Cherry blossom" },
            { "rose", "🌹 Rose" },
            { "hibiscus", "🌺 Hibiscus" },
            { "sunflower", "🌻 Sunflower" },
            { "blossom", "🌼 Blossom" },
            { "corn", "🌽 Ear of maize" },
            { "ear_of_rice", "🌾 Ear of rice" },
            { "herb", "🌿 Herb" },
            { "four_leaf_clover", "🍀 Four leaf clover" },
            { "maple_leaf", "🍁 Maple leaf" },
            { "fallen_leaf", "🍂 Fallen leaf" },
            { "leaves", "🍃 Leaf fluttering in wind" },
            { "mushroom", "🍄 Mushroom" },
            { "tomato", "🍅 Tomato" },
            { "eggplant", "🍆 Aubergine" },
            { "grapes", "🍇 Grapes" },
            { "melon", "🍈 Melon" },
            { "watermelon", "🍉 Watermelon" },
            { "tangerine", "🍊 Tangerine" },
            { "lemon", "🍋 Lemon" },
            { "banana", "🍌 Banana" },
            { "pineapple", "🍍 Pineapple" },
            { "apple", "🍎 Red apple" },
            { "green_apple", "🍏 Green apple" },
            { "pear", "🍐 Pear" },
            { "peach", "🍑 Peach" },
            { "cherries", "🍒 Cherries" },
            { "strawberry", "🍓 Strawberry" },
            { "hamburger", "🍔 Hamburger" },
            { "pizza", "🍕 Slice of pizza" },
            { "meat_on_bone", "🍖 Meat on bone" },
            { "poultry_leg", "🍗 Poultry leg" },
            { "rice_cracker", "🍘 Rice cracker" },
            { "rice_ball", "🍙 Rice ball" },
            { "rice", "🍚 Cooked rice" },
            { "curry", "🍛 Curry and rice" },
            { "ramen", "🍜 Steaming bowl" },
            { "spaghetti", "🍝 Spaghetti" },
            { "bread", "🍞 Bread" },
            { "fries", "🍟 French fries" },
            { "sweet_potato", "🍠 Roasted sweet potato" },
            { "dango", "🍡 Dango" },
            { "oden", "🍢 Oden" },
            { "sushi", "🍣 Sushi" },
            { "fried_shrimp", "🍤 Fried shrimp" },
            { "fish_cake", "🍥 Fish cake with swirl design" },
            { "icecream", "🍦 Soft ice cream" },
            { "shaved_ice", "🍧 Shaved ice" },
            { "ice_cream", "🍨 Ice cream" },
            { "doughnut", "🍩 Doughnut" },
            { "cookie", "🍪 Cookie" },
            { "chocolate_bar", "🍫 Chocolate bar" },
            { "candy", "🍬 Candy" },
            { "lollipop", "🍭 Lollipop" },
            { "custard", "🍮 Custard" },
            { "honey_pot", "🍯 Honey pot" },
            { "cake", "🍰 Shortcake" },
            { "bento", "🍱 Bento box" },
            { "stew", "🍲 Pot of food" },
            { "fried_egg", "🍳 Cooking" },
            { "fork_and_knife", "🍴 Fork and knife" },
            { "tea", "🍵 Teacup without handle" },
            { "sake", "🍶 Sake bottle and cup" },
            { "wine_glass", "🍷 Wine glass" },
            { "cocktail", "🍸 Cocktail glass" },
            { "tropical_drink", "🍹 Tropical drink" },
            { "beer", "🍺 Beer mug" },
            { "beers", "🍻 Clinking beer mugs" },
            { "baby_bottle", "🍼 Baby bottle" },
            { "knife_fork_plate", "🍽️ Fork and knife with plate" },
            { "champagne", "🍾 Bottle with popping cork" },
            { "popcorn", "🍿 Popcorn" },
            { "ribbon", "🎀 Ribbon" },
            { "gift", "🎁 Wrapped present" },
            { "birthday", "🎂 Birthday cake" },
            { "jack_o_lantern", "🎃 Jack-o-lantern" },
            { "christmas_tree", "🎄 Christmas tree" },
            { "santa", "🎅 Father christmas" },
            { "fireworks", "🎆 Fireworks" },
            { "sparkler", "🎇 Firework sparkler" },
            { "balloon", "🎈 Balloon" },
            { "tada", "🎉 Party popper" },
            { "confetti_ball", "🎊 Confetti ball" },
            { "tanabata_tree", "🎋 Tanabata tree" },
            { "crossed_flags", "🎌 Crossed flags" },
            { "bamboo", "🎍 Pine decoration" },
            { "dolls", "🎎 Japanese dolls" },
            { "flags", "🎏 Carp streamer" },
            { "wind_chime", "🎐 Wind chime" },
            { "rice_scene", "🎑 Moon viewing ceremony" },
            { "school_satchel", "🎒 School satchel" },
            { "mortar_board", "🎓 Graduation cap" },
            { "medal", "🎖️ Military medal" },
            { "reminder_ribbon", "🎗️ Reminder ribbon" },
            { "studio_microphone", "🎙️ Studio microphone" },
            { "level_slider", "🎚️ Level slider" },
            { "control_knobs", "🎛️ Control knobs" },
            { "film_frames", "🎞️ Film frames" },
            { "admission_tickets", "🎟️ Admission tickets" },
            { "carousel_horse", "🎠 Carousel horse" },
            { "ferris_wheel", "🎡 Ferris wheel" },
            { "roller_coaster", "🎢 Roller coaster" },
            { "fishing_pole_and_fish", "🎣 Fishing pole and fish" },
            { "microphone", "🎤 Microphone" },
            { "movie_camera", "🎥 Movie camera" },
            { "cinema", "🎦 Cinema" },
            { "headphones", "🎧 Headphone" },
            { "art", "🎨 Artist palette" },
            { "tophat", "🎩 Top hat" },
            { "circus_tent", "🎪 Circus tent" },
            { "ticket", "🎫 Ticket" },
            { "clapper", "🎬 Clapper board" },
            { "performing_arts", "🎭 Performing arts" },
            { "video_game", "🎮 Video game" },
            { "dart", "🎯 Direct hit" },
            { "slot_machine", "🎰 Slot machine" },
            { "8ball", "🎱 Billiards" },
            { "game_die", "🎲 Game die" },
            { "bowling", "🎳 Bowling" },
            { "flower_playing_cards", "🎴 Flower playing cards" },
            { "musical_note", "🎵 Musical note" },
            { "notes", "🎶 Multiple musical notes" },
            { "saxophone", "🎷 Saxophone" },
            { "guitar", "🎸 Guitar" },
            { "musical_keyboard", "🎹 Musical keyboard" },
            { "trumpet", "🎺 Trumpet" },
            { "violin", "🎻 Violin" },
            { "musical_score", "🎼 Musical score" },
            { "running_shirt_with_sash", "🎽 Running shirt with sash" },
            { "tennis", "🎾 Tennis racquet and ball" },
            { "ski", "🎿 Ski and ski boot" },
            { "basketball", "🏀 Basketball and hoop" },
            { "checkered_flag", "🏁 Chequered flag" },
            { "snowboarder", "🏂 Snowboarder" },
            { "woman-running", "🏃‍♀️ Woman running" },
            { "man-running", "🏃‍♂️ Man running" },
            { "runner", "🏃 Runner" },
            { "woman-surfing", "🏄‍♀️ Woman surfing" },
            { "man-surfing", "🏄‍♂️ Man surfing" },
            { "surfer", "🏄 Surfer" },
            { "sports_medal", "🏅 Sports medal" },
            { "trophy", "🏆 Trophy" },
            { "horse_racing", "🏇 Horse racing" },
            { "football", "🏈 American football" },
            { "rugby_football", "🏉 Rugby football" },
            { "woman-swimming", "🏊‍♀️ Woman swimming" },
            { "man-swimming", "🏊‍♂️ Man swimming" },
            { "swimmer", "🏊 Swimmer" },
            { "woman-lifting-weights", "🏋️‍♀️ Woman lifting weights" },
            { "man-lifting-weights", "🏋️‍♂️ Man lifting weights" },
            { "weight_lifter", "🏋️ Person lifting weights" },
            { "woman-golfing", "🏌️‍♀️ Woman golfing" },
            { "man-golfing", "🏌️‍♂️ Man golfing" },
            { "golfer", "🏌️ Person golfing" },
            { "racing_motorcycle", "🏍️ Motorcycle" },
            { "racing_car", "🏎️ Racing car" },
            { "cricket_bat_and_ball", "🏏 Cricket bat and ball" },
            { "volleyball", "🏐 Volleyball" },
            { "field_hockey_stick_and_ball", "🏑 Field hockey stick and ball" },
            { "ice_hockey_stick_and_puck", "🏒 Ice hockey stick and puck" },
            { "table_tennis_paddle_and_ball", "🏓 Table tennis paddle and ball" },
            { "snow_capped_mountain", "🏔️ Snow-capped mountain" },
            { "camping", "🏕️ Camping" },
            { "beach_with_umbrella", "🏖️ Beach with umbrella" },
            { "building_construction", "🏗️ Building construction" },
            { "house_buildings", "🏘️ Houses" },
            { "cityscape", "🏙️ Cityscape" },
            { "derelict_house_building", "🏚️ Derelict house" },
            { "classical_building", "🏛️ Classical building" },
            { "desert", "🏜️ Desert" },
            { "desert_island", "🏝️ Desert island" },
            { "national_park", "🏞️ National park" },
            { "stadium", "🏟️ Stadium" },
            { "house", "🏠 House building" },
            { "house_with_garden", "🏡 House with garden" },
            { "office", "🏢 Office building" },
            { "post_office", "🏣 Japanese post office" },
            { "european_post_office", "🏤 European post office" },
            { "hospital", "🏥 Hospital" },
            { "bank", "🏦 Bank" },
            { "atm", "🏧 Automated teller machine" },
            { "hotel", "🏨 Hotel" },
            { "love_hotel", "🏩 Love hotel" },
            { "convenience_store", "🏪 Convenience store" },
            { "school", "🏫 School" },
            { "department_store", "🏬 Department store" },
            { "factory", "🏭 Factory" },
            { "izakaya_lantern", "🏮 Izakaya lantern" },
            { "japanese_castle", "🏯 Japanese castle" },
            { "european_castle", "🏰 European castle" },
            { "rainbow-flag", "🏳️‍🌈 Rainbow flag" },
            { "transgender_flag", "🏳️‍⚧️ Transgender flag" },
            { "waving_white_flag", "🏳️ White flag" },
            { "pirate_flag", "🏴‍☠️ Pirate flag" },
            { "flag-england", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England flag" },
            { "flag-scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland flag" },
            { "flag-wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales flag" },
            { "waving_black_flag", "🏴 Waving black flag" },
            { "rosette", "🏵️ Rosette" },
            { "label", "🏷️ Label" },
            { "badminton_racquet_and_shuttlecock", "🏸 Badminton racquet and shuttlecock" },
            { "bow_and_arrow", "🏹 Bow and arrow" },
            { "amphora", "🏺 Amphora" },
            { "skin-tone-2", "🏻 Emoji modifier fitzpatrick type-1-2" },
            { "skin-tone-3", "🏼 Emoji modifier fitzpatrick type-3" },
            { "skin-tone-4", "🏽 Emoji modifier fitzpatrick type-4" },
            { "skin-tone-5", "🏾 Emoji modifier fitzpatrick type-5" },
            { "skin-tone-6", "🏿 Emoji modifier fitzpatrick type-6" },
            { "rat", "🐀 Rat" },
            { "mouse2", "🐁 Mouse" },
            { "ox", "🐂 Ox" },
            { "water_buffalo", "🐃 Water buffalo" },
            { "cow2", "🐄 Cow" },
            { "tiger2", "🐅 Tiger" },
            { "leopard", "🐆 Leopard" },
            { "rabbit2", "🐇 Rabbit" },
            { "black_cat", "🐈‍⬛ Black cat" },
            { "cat2", "🐈 Cat" },
            { "dragon", "🐉 Dragon" },
            { "crocodile", "🐊 Crocodile" },
            { "whale2", "🐋 Whale" },
            { "snail", "🐌 Snail" },
            { "snake", "🐍 Snake" },
            { "racehorse", "🐎 Horse" },
            { "ram", "🐏 Ram" },
            { "goat", "🐐 Goat" },
            { "sheep", "🐑 Sheep" },
            { "monkey", "🐒 Monkey" },
            { "black_bird", "🐦‍⬛ Black bird" },
            { "rooster", "🐓 Rooster" },
            { "chicken", "🐔 Chicken" },
            { "service_dog", "🐕‍🦺 Service dog" },
            { "dog2", "🐕 Dog" },
            { "pig2", "🐖 Pig" },
            { "boar", "🐗 Boar" },
            { "elephant", "🐘 Elephant" },
            { "octopus", "🐙 Octopus" },
            { "shell", "🐚 Spiral shell" },
            { "bug", "🐛 Bug" },
            { "ant", "🐜 Ant" },
            { "bee", "🐝 Honeybee" },
            { "ladybug", "🐞 Lady beetle" },
            { "fish", "🐟 Fish" },
            { "tropical_fish", "🐠 Tropical fish" },
            { "blowfish", "🐡 Blowfish" },
            { "turtle", "🐢 Turtle" },
            { "hatching_chick", "🐣 Hatching chick" },
            { "baby_chick", "🐤 Baby chick" },
            { "hatched_chick", "🐥 Front-facing baby chick" },
            { "penguin", "🐧 Penguin" },
            { "koala", "🐨 Koala" },
            { "poodle", "🐩 Poodle" },
            { "dromedary_camel", "🐪 Dromedary camel" },
            { "camel", "🐫 Bactrian camel" },
            { "dolphin", "🐬 Dolphin" },
            { "mouse", "🐭 Mouse face" },
            { "cow", "🐮 Cow face" },
            { "tiger", "🐯 Tiger face" },
            { "rabbit", "🐰 Rabbit face" },
            { "cat", "🐱 Cat face" },
            { "dragon_face", "🐲 Dragon face" },
            { "whale", "🐳 Spouting whale" },
            { "horse", "🐴 Horse face" },
            { "monkey_face", "🐵 Monkey face" },
            { "dog", "🐶 Dog face" },
            { "pig", "🐷 Pig face" },
            { "frog", "🐸 Frog face" },
            { "hamster", "🐹 Hamster face" },
            { "wolf", "🐺 Wolf face" },
            { "polar_bear", "🐻‍❄️ Polar bear" },
            { "bear", "🐻 Bear face" },
            { "panda_face", "🐼 Panda face" },
            { "pig_nose", "🐽 Pig nose" },
            { "feet", "🐾 Paw prints" },
            { "chipmunk", "🐿️ Chipmunk" },            
            { "eye-in-speech-bubble", "👁️‍🗨️ Eye in speech bubble" },
            { "eye", "👁️ Eye" },
            { "ear", "👂 Ear" },
            { "nose", "👃 Nose" },
            { "lips", "👄 Mouth" },
            { "tongue", "👅 Tongue" },
            { "point_up_2", "👆 White up pointing backhand index" },
            { "point_down", "👇 White down pointing backhand index" },
            { "point_left", "👈 White left pointing backhand index" },
            { "point_right", "👉 White right pointing backhand index" },
            { "facepunch", "👊 Fisted hand sign" },
            { "open_hands", "👐 Open hands sign" },
            { "crown", "👑 Crown" },
            { "womans_hat", "👒 Womans hat" },
            { "eyeglasses", "👓 Eyeglasses" },
            { "necktie", "👔 Necktie" },
            { "shirt", "👕 T-shirt" },
            { "jeans", "👖 Jeans" },
            { "dress", "👗 Dress" },
            { "kimono", "👘 Kimono" },
            { "bikini", "👙 Bikini" },
            { "womans_clothes", "👚 Womans clothes" },
            { "purse", "👛 Purse" },
            { "handbag", "👜 Handbag" },
            { "pouch", "👝 Pouch" },
            { "mans_shoe", "👞 Mans shoe" },
            { "athletic_shoe", "👟 Athletic shoe" },
            { "high_heel", "👠 High-heeled shoe" },
            { "sandal", "👡 Womans sandal" },
            { "boot", "👢 Womans boots" },
            { "footprints", "👣 Footprints" },
            { "bust_in_silhouette", "👤 Bust in silhouette" },
            { "busts_in_silhouette", "👥 Busts in silhouette" },
            { "boy", "👦 Boy" },
            { "girl", "👧 Girl" },
            { "male-farmer", "👨‍🌾 Man farmer" },
            { "male-cook", "👨‍🍳 Man cook" },
            { "man_feeding_baby", "👨‍🍼 Man feeding baby" },
            { "male-student", "👨‍🎓 Man student" },
            { "male-singer", "👨‍🎤 Man singer" },
            { "male-artist", "👨‍🎨 Man artist" },
            { "male-teacher", "👨‍🏫 Man teacher" },
            { "male-factory-worker", "👨‍🏭 Man factory worker" },
            { "man-boy-boy", "👨‍👦‍👦 Family: man, boy, boy" },
            { "man-boy", "👨‍👦 Family: man, boy" },
            { "man-girl-boy", "👨‍👧‍👦 Family: man, girl, boy" },
            { "man-girl-girl", "👨‍👧‍👧 Family: man, girl, girl" },
            { "man-girl", "👨‍👧 Family: man, girl" },
            { "man-man-boy", "👨‍👨‍👦 Family: man, man, boy" },
            { "man-man-boy-boy", "👨‍👨‍👦‍👦 Family: man, man, boy, boy" },
            { "man-man-girl", "👨‍👨‍👧 Family: man, man, girl" },
            { "man-man-girl-boy", "👨‍👨‍👧‍👦 Family: man, man, girl, boy" },
            { "man-man-girl-girl", "👨‍👨‍👧‍👧 Family: man, man, girl, girl" },
            { "man-woman-boy", "👨‍👩‍👦 Family: man, woman, boy" },
            { "man-woman-boy-boy", "👨‍👩‍👦‍👦 Family: man, woman, boy, boy" },
            { "man-woman-girl", "👨‍👩‍👧 Family: man, woman, girl" },
            { "man-woman-girl-boy", "👨‍👩‍👧‍👦 Family: man, woman, girl, boy" },
            { "man-woman-girl-girl", "👨‍👩‍👧‍👧 Family: man, woman, girl, girl" },
            { "male-technologist", "👨‍💻 Man technologist" },
            { "male-office-worker", "👨‍💼 Man office worker" },
            { "male-mechanic", "👨‍🔧 Man mechanic" },
            { "male-scientist", "👨‍🔬 Man scientist" },
            { "male-astronaut", "👨‍🚀 Man astronaut" },
            { "male-firefighter", "👨‍🚒 Man firefighter" },
            { "man_with_probing_cane", "👨‍🦯 Man with white cane" },
            { "red_haired_man", "👨‍🦰 Man: red hair" },
            { "curly_haired_man", "👨‍🦱 Man: curly hair" },
            { "bald_man", "👨‍🦲 Man: bald" },
            { "white_haired_man", "👨‍🦳 Man: white hair" },
            { "man_in_motorized_wheelchair", "👨‍🦼 Man in motorized wheelchair" },
            { "man_in_manual_wheelchair", "👨‍🦽 Man in manual wheelchair" },
            { "male-doctor", "👨‍⚕️ Man health worker" },
            { "male-judge", "👨‍⚖️ Man judge" },
            { "male-pilot", "👨‍✈️ Man pilot" },
            { "man-heart-man", "👨‍❤️‍👨 Couple with heart: man, man" },
            { "man-kiss-man", "👨‍❤️‍💋‍👨 Kiss: man, man" },
            { "man", "👨 Man" },
            { "female-farmer", "👩‍🌾 Woman farmer" },
            { "female-cook", "👩‍🍳 Woman cook" },
            { "woman_feeding_baby", "👩‍🍼 Woman feeding baby" },
            { "female-student", "👩‍🎓 Woman student" },
            { "female-singer", "👩‍🎤 Woman singer" },
            { "female-artist", "👩‍🎨 Woman artist" },
            { "female-teacher", "👩‍🏫 Woman teacher" },
            { "female-factory-worker", "👩‍🏭 Woman factory worker" },
            { "woman-boy-boy", "👩‍👦‍👦 Family: woman, boy, boy" },
            { "woman-boy", "👩‍👦 Family: woman, boy" },
            { "woman-girl-boy", "👩‍👧‍👦 Family: woman, girl, boy" },
            { "woman-girl-girl", "👩‍👧‍👧 Family: woman, girl, girl" },
            { "woman-girl", "👩‍👧 Family: woman, girl" },
            { "woman-woman-boy", "👩‍👩‍👦 Family: woman, woman, boy" },
            { "woman-woman-boy-boy", "👩‍👩‍👦‍👦 Family: woman, woman, boy, boy" },
            { "woman-woman-girl", "👩‍👩‍👧 Family: woman, woman, girl" },
            { "woman-woman-girl-boy", "👩‍👩‍👧‍👦 Family: woman, woman, girl, boy" },
            { "woman-woman-girl-girl", "👩‍👩‍👧‍👧 Family: woman, woman, girl, girl" },
            { "female-technologist", "👩‍💻 Woman technologist" },
            { "female-office-worker", "👩‍💼 Woman office worker" },
            { "female-mechanic", "👩‍🔧 Woman mechanic" },
            { "female-scientist", "👩‍🔬 Woman scientist" },
            { "female-astronaut", "👩‍🚀 Woman astronaut" },
            { "female-firefighter", "👩‍🚒 Woman firefighter" },
            { "woman_with_probing_cane", "👩‍🦯 Woman with white cane" },
            { "red_haired_woman", "👩‍🦰 Woman: red hair" },
            { "curly_haired_woman", "👩‍🦱 Woman: curly hair" },
            { "bald_woman", "👩‍🦲 Woman: bald" },
            { "white_haired_woman", "👩‍🦳 Woman: white hair" },
            { "woman_in_motorized_wheelchair", "👩‍🦼 Woman in motorized wheelchair" },
            { "woman_in_manual_wheelchair", "👩‍🦽 Woman in manual wheelchair" },
            { "female-doctor", "👩‍⚕️ Woman health worker" },
            { "female-judge", "👩‍⚖️ Woman judge" },
            { "female-pilot", "👩‍✈️ Woman pilot" },
            { "woman-heart-man", "👩‍❤️‍👨 Couple with heart: woman, man" },
            { "woman-heart-woman", "👩‍❤️‍👩 Couple with heart: woman, woman" },
            { "woman-kiss-man", "👩‍❤️‍💋‍👨 Kiss: woman, man" },
            { "woman-kiss-woman", "👩‍❤️‍💋‍👩 Kiss: woman, woman" },
            { "woman", "👩 Woman" },
            { "family", "👪 Family" },
            { "man_and_woman_holding_hands", "👫 Man and woman holding hands" },
            { "two_men_holding_hands", "👬 Two men holding hands" },
            { "two_women_holding_hands", "👭 Two women holding hands" },
            { "female-police-officer", "👮‍♀️ Woman police officer" },
            { "male-police-officer", "👮‍♂️ Man police officer" },
            { "cop", "👮 Police officer" },
            { "women-with-bunny-ears-partying", "👯‍♀️ Women with bunny ears" },
            { "men-with-bunny-ears-partying", "👯‍♂️ Men with bunny ears" },
            { "dancers", "👯 Woman with bunny ears" },
            { "woman_with_veil", "👰‍♀️ Woman with veil" },
            { "man_with_veil", "👰‍♂️ Man with veil" },
            { "bride_with_veil", "👰 Bride with veil" },
            { "blond-haired-woman", "👱‍♀️ Woman: blond hair" },
            { "blond-haired-man", "👱‍♂️ Man: blond hair" },
            { "person_with_blond_hair", "👱 Person with blond hair" },
            { "man_with_gua_pi_mao", "👲 Man with gua pi mao" },
            { "woman-wearing-turban", "👳‍♀️ Woman wearing turban" },
            { "man-wearing-turban", "👳‍♂️ Man wearing turban" },
            { "man_with_turban", "👳 Man with turban" },
            { "older_man", "👴 Older man" },
            { "older_woman", "👵 Older woman" },
            { "baby", "👶 Baby" },
            { "female-construction-worker", "👷‍♀️ Woman construction worker" },
            { "male-construction-worker", "👷‍♂️ Man construction worker" },
            { "construction_worker", "👷 Construction worker" },
            { "princess", "👸 Princess" },
            { "japanese_ogre", "👹 Japanese ogre" },
            { "japanese_goblin", "👺 Japanese goblin" },
            { "ghost", "👻 Ghost" },
            { "angel", "👼 Baby angel" },
            { "alien", "👽 Extraterrestrial alien" },
            { "space_invader", "👾 Alien monster" },
            { "imp", "👿 Imp" },
            { "skull", "💀 Skull" },
            { "woman-tipping-hand", "💁‍♀️ Woman tipping hand" },
            { "man-tipping-hand", "💁‍♂️ Man tipping hand" },
            { "information_desk_person", "💁 Information desk person" },
            { "female-guard", "💂‍♀️ Woman guard" },
            { "male-guard", "💂‍♂️ Man guard" },
            { "guardsman", "💂 Guardsman" },
            { "dancer", "💃 Dancer" },
            { "lipstick", "💄 Lipstick" },
            { "nail_care", "💅 Nail polish" },
            { "woman-getting-massage", "💆‍♀️ Woman getting massage" },
            { "man-getting-massage", "💆‍♂️ Man getting massage" },
            { "massage", "💆 Face massage" },
            { "woman-getting-haircut", "💇‍♀️ Woman getting haircut" },
            { "man-getting-haircut", "💇‍♂️ Man getting haircut" },
            { "haircut", "💇 Haircut" },
            { "barber", "💈 Barber pole" },
            { "syringe", "💉 Syringe" },
            { "pill", "💊 Pill" },
            { "kiss", "💋 Kiss mark" },
            { "love_letter", "💌 Love letter" },
            { "ring", "💍 Ring" },
            { "gem", "💎 Gem stone" },
            { "couplekiss", "💏 Kiss" },
            { "bouquet", "💐 Bouquet" },
            { "couple_with_heart", "💑 Couple with heart" },
            { "wedding", "💒 Wedding" },
            { "heartbeat", "💓 Beating heart" },
            { "broken_heart", "💔 Broken heart" },
            { "two_hearts", "💕 Two hearts" },
            { "sparkling_heart", "💖 Sparkling heart" },
            { "heartpulse", "💗 Growing heart" },
            { "cupid", "💘 Heart with arrow" },
            { "blue_heart", "💙 Blue heart" },
            { "green_heart", "💚 Green heart" },
            { "yellow_heart", "💛 Yellow heart" },
            { "purple_heart", "💜 Purple heart" },
            { "gift_heart", "💝 Heart with ribbon" },
            { "revolving_hearts", "💞 Revolving hearts" },
            { "heart_decoration", "💟 Heart decoration" },
            { "diamond_shape_with_a_dot_inside", "💠 Diamond shape with a dot inside" },
            { "bulb", "💡 Electric light bulb" },
            { "anger", "💢 Anger symbol" },
            { "bomb", "💣 Bomb" },
            { "zzz", "💤 Sleeping symbol" },
            { "boom", "💥 Collision symbol" },
            { "sweat_drops", "💦 Splashing sweat symbol" },
            { "droplet", "💧 Droplet" },
            { "dash", "💨 Dash symbol" },
            { "hankey", "💩 Pile of poo" },
            { "muscle", "💪 Flexed biceps" },
            { "dizzy", "💫 Dizzy symbol" },
            { "speech_balloon", "💬 Speech balloon" },
            { "thought_balloon", "💭 Thought balloon" },
            { "white_flower", "💮 White flower" },
            { "100", "💯 Hundred points symbol" },
            { "moneybag", "💰 Money bag" },
            { "currency_exchange", "💱 Currency exchange" },
            { "heavy_dollar_sign", "💲 Heavy dollar sign" },
            { "credit_card", "💳 Credit card" },
            { "yen", "💴 Banknote with yen sign" },
            { "dollar", "💵 Banknote with dollar sign" },
            { "euro", "💶 Banknote with euro sign" },
            { "pound", "💷 Banknote with pound sign" },
            { "money_with_wings", "💸 Money with wings" },
            { "chart", "💹 Chart with upwards trend and yen sign" },
            { "seat", "💺 Seat" },
            { "computer", "💻 Personal computer" },
            { "briefcase", "💼 Briefcase" },
            { "minidisc", "💽 Minidisc" },
            { "floppy_disk", "💾 Floppy disk" },
            { "cd", "💿 Optical disc" },
            { "dvd", "📀 Dvd" },
            { "file_folder", "📁 File folder" },
            { "open_file_folder", "📂 Open file folder" },
            { "page_with_curl", "📃 Page with curl" },
            { "page_facing_up", "📄 Page facing up" },
            { "date", "📅 Calendar" },
            { "calendar", "📆 Tear-off calendar" },
            { "card_index", "📇 Card index" },
            { "chart_with_upwards_trend", "📈 Chart with upwards trend" },
            { "chart_with_downwards_trend", "📉 Chart with downwards trend" },
            { "bar_chart", "📊 Bar chart" },
            { "clipboard", "📋 Clipboard" },
            { "pushpin", "📌 Pushpin" },
            { "round_pushpin", "📍 Round pushpin" },
            { "paperclip", "📎 Paperclip" },
            { "straight_ruler", "📏 Straight ruler" },
            { "triangular_ruler", "📐 Triangular ruler" },
            { "bookmark_tabs", "📑 Bookmark tabs" },
            { "ledger", "📒 Ledger" },
            { "notebook", "📓 Notebook" },
            { "notebook_with_decorative_cover", "📔 Notebook with decorative cover" },
            { "closed_book", "📕 Closed book" },
            { "book", "📖 Open book" },
            { "green_book", "📗 Green book" },
            { "blue_book", "📘 Blue book" },
            { "orange_book", "📙 Orange book" },
            { "books", "📚 Books" },
            { "name_badge", "📛 Name badge" },
            { "scroll", "📜 Scroll" },
            { "memo", "📝 Memo" },
            { "telephone_receiver", "📞 Telephone receiver" },
            { "pager", "📟 Pager" },
            { "fax", "📠 Fax machine" },
            { "satellite_antenna", "📡 Satellite antenna" },
            { "loudspeaker", "📢 Public address loudspeaker" },
            { "mega", "📣 Cheering megaphone" },
            { "outbox_tray", "📤 Outbox tray" },
            { "inbox_tray", "📥 Inbox tray" },
            { "package", "📦 Package" },
            { "e-mail", "📧 E-mail symbol" },
            { "incoming_envelope", "📨 Incoming envelope" },
            { "envelope_with_arrow", "📩 Envelope with downwards arrow above" },
            { "mailbox_closed", "📪 Closed mailbox with lowered flag" },
            { "mailbox", "📫 Closed mailbox with raised flag" },
            { "mailbox_with_mail", "📬 Open mailbox with raised flag" },
            { "mailbox_with_no_mail", "📭 Open mailbox with lowered flag" },
            { "postbox", "📮 Postbox" },
            { "postal_horn", "📯 Postal horn" },
            { "newspaper", "📰 Newspaper" },
            { "iphone", "📱 Mobile phone" },
            { "calling", "📲 Mobile phone with rightwards arrow at left" },
            { "vibration_mode", "📳 Vibration mode" },
            { "mobile_phone_off", "📴 Mobile phone off" },
            { "no_mobile_phones", "📵 No mobile phones" },
            { "signal_strength", "📶 Antenna with bars" },
            { "camera", "📷 Camera" },
            { "camera_with_flash", "📸 Camera with flash" },
            { "video_camera", "📹 Video camera" },
            { "tv", "📺 Television" },
            { "radio", "📻 Radio" },
            { "vhs", "📼 Videocassette" },
            { "film_projector", "📽️ Film projector" },
            { "prayer_beads", "📿 Prayer beads" },
            { "twisted_rightwards_arrows", "🔀 Twisted rightwards arrows" },
            { "repeat", "🔁 Clockwise rightwards and leftwards open circle arrows" },
            { "repeat_one", "🔂 Clockwise rightwards and leftwards open circle arrows with circled one overlay" },
            { "arrows_clockwise", "🔃 Clockwise downwards and upwards open circle arrows" },
            { "arrows_counterclockwise", "🔄 Anticlockwise downwards and upwards open circle arrows" },
            { "low_brightness", "🔅 Low brightness symbol" },
            { "high_brightness", "🔆 High brightness symbol" },
            { "mute", "🔇 Speaker with cancellation stroke" },
            { "speaker", "🔈 Speaker" },
            { "sound", "🔉 Speaker with one sound wave" },
            { "loud_sound", "🔊 Speaker with three sound waves" },
            { "battery", "🔋 Battery" },
            { "electric_plug", "🔌 Electric plug" },
            { "mag", "🔍 Left-pointing magnifying glass" },
            { "mag_right", "🔎 Right-pointing magnifying glass" },
            { "lock_with_ink_pen", "🔏 Lock with ink pen" },
            { "closed_lock_with_key", "🔐 Closed lock with key" },
            { "key", "🔑 Key" },
            { "lock", "🔒 Lock" },
            { "unlock", "🔓 Open lock" },
            { "bell", "🔔 Bell" },
            { "no_bell", "🔕 Bell with cancellation stroke" },
            { "bookmark", "🔖 Bookmark" },
            { "link", "🔗 Link symbol" },
            { "radio_button", "🔘 Radio button" },
            { "back", "🔙 Back with leftwards arrow above" },
            { "end", "🔚 End with leftwards arrow above" },
            { "on", "🔛 On with exclamation mark with left right arrow above" },
            { "soon", "🔜 Soon with rightwards arrow above" },
            { "top", "🔝 Top with upwards arrow above" },
            { "underage", "🔞 No one under eighteen symbol" },
            { "keycap_ten", "🔟 Keycap ten" },
            { "capital_abcd", "🔠 Input symbol for latin capital letters" },
            { "abcd", "🔡 Input symbol for latin small letters" },
            { "1234", "🔢 Input symbol for numbers" },
            { "symbols", "🔣 Input symbol for symbols" },
            { "abc", "🔤 Input symbol for latin letters" },
            { "fire", "🔥 Fire" },
            { "flashlight", "🔦 Electric torch" },
            { "wrench", "🔧 Wrench" },
            { "hammer", "🔨 Hammer" },
            { "nut_and_bolt", "🔩 Nut and bolt" },
            { "hocho", "🔪 Hocho" },
            { "gun", "🔫 Pistol" },
            { "microscope", "🔬 Microscope" },
            { "telescope", "🔭 Telescope" },
            { "crystal_ball", "🔮 Crystal ball" },
            { "six_pointed_star", "🔯 Six pointed star with middle dot" },
            { "beginner", "🔰 Japanese symbol for beginner" },
            { "trident", "🔱 Trident emblem" },
            { "black_square_button", "🔲 Black square button" },
            { "white_square_button", "🔳 White square button" },
            { "red_circle", "🔴 Large red circle" },
            { "large_blue_circle", "🔵 Large blue circle" },
            { "large_orange_diamond", "🔶 Large orange diamond" },
            { "large_blue_diamond", "🔷 Large blue diamond" },
            { "small_orange_diamond", "🔸 Small orange diamond" },
            { "small_blue_diamond", "🔹 Small blue diamond" },
            { "small_red_triangle", "🔺 Up-pointing red triangle" },
            { "small_red_triangle_down", "🔻 Down-pointing red triangle" },
            { "arrow_up_small", "🔼 Up-pointing small red triangle" },
            { "arrow_down_small", "🔽 Down-pointing small red triangle" },
            { "om_symbol", "🕉️ Om" },
            { "dove_of_peace", "🕊️ Dove" },
            { "kaaba", "🕋 Kaaba" },
            { "mosque", "🕌 Mosque" },
            { "synagogue", "🕍 Synagogue" },
            { "menorah_with_nine_branches", "🕎 Menorah with nine branches" },
            { "clock1", "🕐 Clock face one oclock" },
            { "clock2", "🕑 Clock face two oclock" },
            { "clock3", "🕒 Clock face three oclock" },
            { "clock4", "🕓 Clock face four oclock" },
            { "clock5", "🕔 Clock face five oclock" },
            { "clock6", "🕕 Clock face six oclock" },
            { "clock7", "🕖 Clock face seven oclock" },
            { "clock8", "🕗 Clock face eight oclock" },
            { "clock9", "🕘 Clock face nine oclock" },
            { "clock10", "🕙 Clock face ten oclock" },
            { "clock11", "🕚 Clock face eleven oclock" },
            { "clock12", "🕛 Clock face twelve oclock" },
            { "clock130", "🕜 Clock face one-thirty" },
            { "clock230", "🕝 Clock face two-thirty" },
            { "clock330", "🕞 Clock face three-thirty" },
            { "clock430", "🕟 Clock face four-thirty" },
            { "clock530", "🕠 Clock face five-thirty" },
            { "clock630", "🕡 Clock face six-thirty" },
            { "clock730", "🕢 Clock face seven-thirty" },
            { "clock830", "🕣 Clock face eight-thirty" },
            { "clock930", "🕤 Clock face nine-thirty" },
            { "clock1030", "🕥 Clock face ten-thirty" },
            { "clock1130", "🕦 Clock face eleven-thirty" },
            { "clock1230", "🕧 Clock face twelve-thirty" },
            { "candle", "🕯️ Candle" },
            { "mantelpiece_clock", "🕰️ Mantelpiece clock" },
            { "hole", "🕳️ Hole" },
            { "man_in_business_suit_levitating", "🕴️ Person in suit levitating" },
            { "female-detective", "🕵️‍♀️ Woman detective" },
            { "male-detective", "🕵️‍♂️ Man detective" },
            { "sleuth_or_spy", "🕵️ Detective" },
            { "dark_sunglasses", "🕶️ Sunglasses" },
            { "spider", "🕷️ Spider" },
            { "spider_web", "🕸️ Spider web" },
            { "joystick", "🕹️ Joystick" },
            { "man_dancing", "🕺 Man dancing" },
            { "linked_paperclips", "🖇️ Linked paperclips" },
            { "lower_left_ballpoint_pen", "🖊️ Pen" },
            { "lower_left_fountain_pen", "🖋️ Fountain pen" },
            { "lower_left_paintbrush", "🖌️ Paintbrush" },
            { "lower_left_crayon", "🖍️ Crayon" },
            { "raised_hand_with_fingers_splayed", "🖐️ Hand with fingers splayed" },
            { "middle_finger", "🖕 Reversed hand with middle finger extended" },
            { "spock-hand", "🖖 Raised hand with part between middle and ring fingers" },
            { "black_heart", "🖤 Black heart" },
            { "desktop_computer", "🖥️ Desktop computer" },
            { "printer", "🖨️ Printer" },
            { "three_button_mouse", "🖱️ Computer mouse" },
            { "trackball", "🖲️ Trackball" },
            { "frame_with_picture", "🖼️ Framed picture" },
            { "card_index_dividers", "🗂️ Card index dividers" },
            { "card_file_box", "🗃️ Card file box" },
            { "file_cabinet", "🗄️ File cabinet" },
            { "wastebasket", "🗑️ Wastebasket" },
            { "spiral_note_pad", "🗒️ Spiral notepad" },
            { "spiral_calendar_pad", "🗓️ Spiral calendar" },
            { "compression", "🗜️ Clamp" },
            { "old_key", "🗝️ Old key" },
            { "rolled_up_newspaper", "🗞️ Rolled-up newspaper" },
            { "dagger_knife", "🗡️ Dagger" },
            { "speaking_head_in_silhouette", "🗣️ Speaking head" },
            { "left_speech_bubble", "🗨️ Left speech bubble" },
            { "right_anger_bubble", "🗯️ Right anger bubble" },
            { "ballot_box_with_ballot", "🗳️ Ballot box with ballot" },
            { "world_map", "🗺️ World map" },
            { "mount_fuji", "🗻 Mount fuji" },
            { "tokyo_tower", "🗼 Tokyo tower" },
            { "statue_of_liberty", "🗽 Statue of liberty" },
            { "japan", "🗾 Silhouette of japan" },
            { "moyai", "🗿 Moyai" },
            { "grinning", "😀 Grinning face" },
            { "grin", "😁 Grinning face with smiling eyes" },
            { "smile", "😄 Smiling face with open mouth and smiling eyes" },
            { "sweat_smile", "😅 Smiling face with open mouth and cold sweat" },
            { "laughing", "😆 Smiling face with open mouth and tightly-closed eyes" },
            { "innocent", "😇 Smiling face with halo" },
            { "smiling_imp", "😈 Smiling face with horns" },
            { "wink", "😉 Winking face" },
            { "blush", "😊 Smiling face with smiling eyes" },
            { "yum", "😋 Face savouring delicious food" },
            { "relieved", "😌 Relieved face" },
            { "heart_eyes", "😍 Smiling face with heart-shaped eyes" },
            { "sunglasses", "😎 Smiling face with sunglasses" },
            { "smirk", "😏 Smirking face" },
            { "neutral_face", "😐 Neutral face" },
            { "expressionless", "😑 Expressionless face" },
            { "unamused", "😒 Unamused face" },
            { "sweat", "😓 Face with cold sweat" },
            { "pensive", "😔 Pensive face" },
            { "confused", "😕 Confused face" },
            { "confounded", "😖 Confounded face" },
            { "kissing", "😗 Kissing face" },
            { "kissing_heart", "😘 Face throwing a kiss" },
            { "kissing_smiling_eyes", "😙 Kissing face with smiling eyes" },
            { "kissing_closed_eyes", "😚 Kissing face with closed eyes" },
            { "stuck_out_tongue", "😛 Face with stuck-out tongue" },
            { "stuck_out_tongue_winking_eye", "😜 Face with stuck-out tongue and winking eye" },
            { "stuck_out_tongue_closed_eyes", "😝 Face with stuck-out tongue and tightly-closed eyes" },
            { "disappointed", "😞 Disappointed face" },
            { "worried", "😟 Worried face" },
            { "angry", "😠 Angry face" },
            { "rage", "😡 Pouting face" },
            { "cry", "😢 Crying face" },
            { "persevere", "😣 Persevering face" },
            { "triumph", "😤 Face with look of triumph" },
            { "disappointed_relieved", "😥 Disappointed but relieved face" },
            { "frowning", "😦 Frowning face with open mouth" },
            { "anguished", "😧 Anguished face" },
            { "fearful", "😨 Fearful face" },
            { "weary", "😩 Weary face" },
            { "sleepy", "😪 Sleepy face" },
            { "tired_face", "😫 Tired face" },
            { "grimacing", "😬 Grimacing face" },
            { "sob", "😭 Loudly crying face" },
            { "face_exhaling", "😮‍💨 Face exhaling" },
            { "open_mouth", "😮 Face with open mouth" },
            { "hushed", "😯 Hushed face" },
            { "cold_sweat", "😰 Face with open mouth and cold sweat" },
            { "scream", "😱 Face screaming in fear" },
            { "astonished", "😲 Astonished face" },
            { "flushed", "😳 Flushed face" },
            { "sleeping", "😴 Sleeping face" },
            { "face_with_spiral_eyes", "😵‍💫 Face with spiral eyes" },
            { "dizzy_face", "😵 Dizzy face" },
            { "face_in_clouds", "😶‍🌫️ Face in clouds" },
            { "no_mouth", "😶 Face without mouth" },
            { "mask", "😷 Face with medical mask" },
            { "smile_cat", "😸 Grinning cat face with smiling eyes" },
            { "joy_cat", "😹 Cat face with tears of joy" },
            { "smiley_cat", "😺 Smiling cat face with open mouth" },
            { "heart_eyes_cat", "😻 Smiling cat face with heart-shaped eyes" },
            { "smirk_cat", "😼 Cat face with wry smile" },
            { "kissing_cat", "😽 Kissing cat face with closed eyes" },
            { "pouting_cat", "😾 Pouting cat face" },
            { "crying_cat_face", "😿 Crying cat face" },
            { "scream_cat", "🙀 Weary cat face" },
            { "slightly_frowning_face", "🙁 Slightly frowning face" },
            { "upside_down_face", "🙃 Upside-down face" },
            { "face_with_rolling_eyes", "🙄 Face with rolling eyes" },
            { "woman-gesturing-no", "🙅‍♀️ Woman gesturing no" },
            { "man-gesturing-no", "🙅‍♂️ Man gesturing no" },
            { "no_good", "🙅 Face with no good gesture" },
            { "woman-gesturing-ok", "🙆‍♀️ Woman gesturing ok" },
            { "man-gesturing-ok", "🙆‍♂️ Man gesturing ok" },
            { "ok_woman", "🙆 Face with ok gesture" },
            { "woman-bowing", "🙇‍♀️ Woman bowing" },
            { "man-bowing", "🙇‍♂️ Man bowing" },
            { "bow", "🙇 Person bowing deeply" },
            { "see_no_evil", "🙈 See-no-evil monkey" },
            { "hear_no_evil", "🙉 Hear-no-evil monkey" },
            { "speak_no_evil", "🙊 Speak-no-evil monkey" },
            { "woman-raising-hand", "🙋‍♀️ Woman raising hand" },
            { "man-raising-hand", "🙋‍♂️ Man raising hand" },
            { "raising_hand", "🙋 Happy person raising one hand" },            
            { "woman-frowning", "🙍‍♀️ Woman frowning" },
            { "man-frowning", "🙍‍♂️ Man frowning" },
            { "person_frowning", "🙍 Person frowning" },
            { "woman-pouting", "🙎‍♀️ Woman pouting" },
            { "man-pouting", "🙎‍♂️ Man pouting" },
            { "person_with_pouting_face", "🙎 Person with pouting face" },
            { "pray", "🙏 Person with folded hands" },
            { "rocket", "🚀 Rocket" },
            { "helicopter", "🚁 Helicopter" },
            { "steam_locomotive", "🚂 Steam locomotive" },
            { "railway_car", "🚃 Railway car" },
            { "bullettrain_side", "🚄 High-speed train" },
            { "bullettrain_front", "🚅 High-speed train with bullet nose" },
            { "train2", "🚆 Train" },
            { "metro", "🚇 Metro" },
            { "light_rail", "🚈 Light rail" },
            { "station", "🚉 Station" },
            { "tram", "🚊 Tram" },
            { "train", "🚋 Tram car" },
            { "bus", "🚌 Bus" },
            { "oncoming_bus", "🚍 Oncoming bus" },
            { "trolleybus", "🚎 Trolleybus" },
            { "busstop", "🚏 Bus stop" },
            { "minibus", "🚐 Minibus" },
            { "ambulance", "🚑 Ambulance" },
            { "fire_engine", "🚒 Fire engine" },
            { "police_car", "🚓 Police car" },
            { "oncoming_police_car", "🚔 Oncoming police car" },
            { "taxi", "🚕 Taxi" },
            { "oncoming_taxi", "🚖 Oncoming taxi" },
            { "car", "🚗 Automobile" },
            { "oncoming_automobile", "🚘 Oncoming automobile" },
            { "blue_car", "🚙 Recreational vehicle" },
            { "truck", "🚚 Delivery truck" },
            { "articulated_lorry", "🚛 Articulated lorry" },
            { "tractor", "🚜 Tractor" },
            { "monorail", "🚝 Monorail" },
            { "mountain_railway", "🚞 Mountain railway" },
            { "suspension_railway", "🚟 Suspension railway" },
            { "mountain_cableway", "🚠 Mountain cableway" },
            { "aerial_tramway", "🚡 Aerial tramway" },
            { "ship", "🚢 Ship" },
            { "woman-rowing-boat", "🚣‍♀️ Woman rowing boat" },
            { "man-rowing-boat", "🚣‍♂️ Man rowing boat" },
            { "rowboat", "🚣 Rowboat" },
            { "speedboat", "🚤 Speedboat" },
            { "traffic_light", "🚥 Horizontal traffic light" },
            { "vertical_traffic_light", "🚦 Vertical traffic light" },
            { "construction", "🚧 Construction sign" },
            { "rotating_light", "🚨 Police cars revolving light" },
            { "triangular_flag_on_post", "🚩 Triangular flag on post" },
            { "door", "🚪 Door" },
            { "no_entry_sign", "🚫 No entry sign" },
            { "smoking", "🚬 Smoking symbol" },
            { "no_smoking", "🚭 No smoking symbol" },
            { "put_litter_in_its_place", "🚮 Put litter in its place symbol" },
            { "do_not_litter", "🚯 Do not litter symbol" },
            { "potable_water", "🚰 Potable water symbol" },
            { "non-potable_water", "🚱 Non-potable water symbol" },
            { "bike", "🚲 Bicycle" },
            { "no_bicycles", "🚳 No bicycles" },
            { "woman-biking", "🚴‍♀️ Woman biking" },
            { "man-biking", "🚴‍♂️ Man biking" },
            { "bicyclist", "🚴 Bicyclist" },
            { "woman-mountain-biking", "🚵‍♀️ Woman mountain biking" },
            { "man-mountain-biking", "🚵‍♂️ Man mountain biking" },
            { "mountain_bicyclist", "🚵 Mountain bicyclist" },
            { "woman-walking", "🚶‍♀️ Woman walking" },
            { "man-walking", "🚶‍♂️ Man walking" },
            { "walking", "🚶 Pedestrian" },
            { "no_pedestrians", "🚷 No pedestrians" },
            { "children_crossing", "🚸 Children crossing" },
            { "mens", "🚹 Mens symbol" },
            { "womens", "🚺 Womens symbol" },
            { "restroom", "🚻 Restroom" },
            { "baby_symbol", "🚼 Baby symbol" },
            { "toilet", "🚽 Toilet" },
            { "wc", "🚾 Water closet" },
            { "shower", "🚿 Shower" },
            { "bath", "🛀 Bath" },
            { "bathtub", "🛁 Bathtub" },
            { "passport_control", "🛂 Passport control" },
            { "customs", "🛃 Customs" },
            { "baggage_claim", "🛄 Baggage claim" },
            { "left_luggage", "🛅 Left luggage" },
            { "couch_and_lamp", "🛋️ Couch and lamp" },
            { "sleeping_accommodation", "🛌 Sleeping accommodation" },
            { "shopping_bags", "🛍️ Shopping bags" },
            { "bellhop_bell", "🛎️ Bellhop bell" },
            { "bed", "🛏️ Bed" },
            { "place_of_worship", "🛐 Place of worship" },
            { "octagonal_sign", "🛑 Octagonal sign" },
            { "shopping_trolley", "🛒 Shopping trolley" },
            { "hindu_temple", "🛕 Hindu temple" },
            { "hut", "🛖 Hut" },
            { "elevator", "🛗 Elevator" },
            { "wireless", "🛜 Wireless" },
            { "playground_slide", "🛝 Playground slide" },
            { "wheel", "🛞 Wheel" },
            { "ring_buoy", "🛟 Ring buoy" },
            { "hammer_and_wrench", "🛠️ Hammer and wrench" },
            { "shield", "🛡️ Shield" },
            { "oil_drum", "🛢️ Oil drum" },
            { "motorway", "🛣️ Motorway" },
            { "railway_track", "🛤️ Railway track" },
            { "motor_boat", "🛥️ Motor boat" },
            { "small_airplane", "🛩️ Small airplane" },
            { "airplane_departure", "🛫 Airplane departure" },
            { "airplane_arriving", "🛬 Airplane arriving" },
            { "satellite", "🛰️ Satellite" },
            { "passenger_ship", "🛳️ Passenger ship" },
            { "scooter", "🛴 Scooter" },
            { "motor_scooter", "🛵 Motor scooter" },
            { "canoe", "🛶 Canoe" },
            { "sled", "🛷 Sled" },
            { "flying_saucer", "🛸 Flying saucer" },
            { "skateboard", "🛹 Skateboard" },
            { "auto_rickshaw", "🛺 Auto rickshaw" },
            { "pickup_truck", "🛻 Pickup truck" },
            { "roller_skate", "🛼 Roller skate" },
            { "large_orange_circle", "🟠 Large orange circle" },
            { "large_yellow_circle", "🟡 Large yellow circle" },
            { "large_green_circle", "🟢 Large green circle" },
            { "large_purple_circle", "🟣 Large purple circle" },
            { "large_brown_circle", "🟤 Large brown circle" },
            { "large_red_square", "🟥 Large red square" },
            { "large_blue_square", "🟦 Large blue square" },
            { "large_orange_square", "🟧 Large orange square" },
            { "large_yellow_square", "🟨 Large yellow square" },
            { "large_green_square", "🟩 Large green square" },
            { "large_purple_square", "🟪 Large purple square" },
            { "large_brown_square", "🟫 Large brown square" },
            { "heavy_equals_sign", "🟰 Heavy equals sign" },
            { "pinched_fingers", "🤌 Pinched fingers" },
            { "white_heart", "🤍 White heart" },
            { "brown_heart", "🤎 Brown heart" },
            { "pinching_hand", "🤏 Pinching hand" },
            { "zipper_mouth_face", "🤐 Zipper-mouth face" },
            { "money_mouth_face", "🤑 Money-mouth face" },
            { "face_with_thermometer", "🤒 Face with thermometer" },
            { "nerd_face", "🤓 Nerd face" },
            { "thinking_face", "🤔 Thinking face" },
            { "face_with_head_bandage", "🤕 Face with head-bandage" },
            { "robot_face", "🤖 Robot face" },
            { "hugging_face", "🤗 Hugging face" },
            { "the_horns", "🤘 Sign of the horns" },
            { "call_me_hand", "🤙 Call me hand" },
            { "raised_back_of_hand", "🤚 Raised back of hand" },
            { "left-facing_fist", "🤛 Left-facing fist" },
            { "right-facing_fist", "🤜 Right-facing fist" },
            { "handshake", "🤝 Handshake" },
            { "crossed_fingers", "🤞 Hand with index and middle fingers crossed" },
            { "i_love_you_hand_sign", "🤟 I love you hand sign" },
            { "face_with_cowboy_hat", "🤠 Face with cowboy hat" },
            { "clown_face", "🤡 Clown face" },
            { "nauseated_face", "🤢 Nauseated face" },
            { "rolling_on_the_floor_laughing", "🤣 Rolling on the floor laughing" },
            { "drooling_face", "🤤 Drooling face" },
            { "lying_face", "🤥 Lying face" },
            { "woman-facepalming", "🤦‍♀️ Woman facepalming" },
            { "man-facepalming", "🤦‍♂️ Man facepalming" },
            { "face_palm", "🤦 Face palm" },
            { "sneezing_face", "🤧 Sneezing face" },
            { "face_with_raised_eyebrow", "🤨 Face with one eyebrow raised" },
            { "star-struck", "🤩 Grinning face with star eyes" },
            { "zany_face", "🤪 Grinning face with one large and one small eye" },
            { "shushing_face", "🤫 Face with finger covering closed lips" },
            { "face_with_symbols_on_mouth", "🤬 Serious face with symbols covering mouth" },
            { "face_with_hand_over_mouth", "🤭 Smiling face with smiling eyes and hand covering mouth" },
            { "face_vomiting", "🤮 Face with open mouth vomiting" },
            { "exploding_head", "🤯 Shocked face with exploding head" },
            { "pregnant_woman", "🤰 Pregnant woman" },
            { "breast-feeding", "🤱 Breast-feeding" },
            { "palms_up_together", "🤲 Palms up together" },
            { "selfie", "🤳 Selfie" },
            { "prince", "🤴 Prince" },
            { "woman_in_tuxedo", "🤵‍♀️ Woman in tuxedo" },
            { "man_in_tuxedo", "🤵‍♂️ Man in tuxedo" },
            { "person_in_tuxedo", "🤵 Man in tuxedo" },
            { "mrs_claus", "🤶 Mother christmas" },
            { "woman-shrugging", "🤷‍♀️ Woman shrugging" },
            { "man-shrugging", "🤷‍♂️ Man shrugging" },
            { "shrug", "🤷 Shrug" },
            { "woman-cartwheeling", "🤸‍♀️ Woman cartwheeling" },
            { "man-cartwheeling", "🤸‍♂️ Man cartwheeling" },
            { "person_doing_cartwheel", "🤸 Person doing cartwheel" },
            { "woman-juggling", "🤹‍♀️ Woman juggling" },
            { "man-juggling", "🤹‍♂️ Man juggling" },
            { "juggling", "🤹 Juggling" },
            { "fencer", "🤺 Fencer" },
            { "woman-wrestling", "🤼‍♀️ Women wrestling" },
            { "man-wrestling", "🤼‍♂️ Men wrestling" },
            { "wrestlers", "🤼 Wrestlers" },
            { "woman-playing-water-polo", "🤽‍♀️ Woman playing water polo" },
            { "man-playing-water-polo", "🤽‍♂️ Man playing water polo" },
            { "water_polo", "🤽 Water polo" },
            { "woman-playing-handball", "🤾‍♀️ Woman playing handball" },
            { "man-playing-handball", "🤾‍♂️ Man playing handball" },
            { "handball", "🤾 Handball" },
            { "diving_mask", "🤿 Diving mask" },
            { "wilted_flower", "🥀 Wilted flower" },
            { "drum_with_drumsticks", "🥁 Drum with drumsticks" },
            { "clinking_glasses", "🥂 Clinking glasses" },
            { "tumbler_glass", "🥃 Tumbler glass" },
            { "spoon", "🥄 Spoon" },
            { "goal_net", "🥅 Goal net" },
            { "first_place_medal", "🥇 First place medal" },
            { "second_place_medal", "🥈 Second place medal" },
            { "third_place_medal", "🥉 Third place medal" },
            { "boxing_glove", "🥊 Boxing glove" },
            { "martial_arts_uniform", "🥋 Martial arts uniform" },
            { "curling_stone", "🥌 Curling stone" },
            { "lacrosse", "🥍 Lacrosse stick and ball" },
            { "softball", "🥎 Softball" },
            { "flying_disc", "🥏 Flying disc" },
            { "croissant", "🥐 Croissant" },
            { "avocado", "🥑 Avocado" },
            { "cucumber", "🥒 Cucumber" },
            { "bacon", "🥓 Bacon" },
            { "potato", "🥔 Potato" },
            { "carrot", "🥕 Carrot" },
            { "baguette_bread", "🥖 Baguette bread" },
            { "green_salad", "🥗 Green salad" },
            { "shallow_pan_of_food", "🥘 Shallow pan of food" },
            { "stuffed_flatbread", "🥙 Stuffed flatbread" },
            { "egg", "🥚 Egg" },
            { "glass_of_milk", "🥛 Glass of milk" },
            { "peanuts", "🥜 Peanuts" },
            { "kiwifruit", "🥝 Kiwifruit" },
            { "pancakes", "🥞 Pancakes" },
            { "dumpling", "🥟 Dumpling" },
            { "fortune_cookie", "🥠 Fortune cookie" },
            { "takeout_box", "🥡 Takeout box" },
            { "chopsticks", "🥢 Chopsticks" },
            { "bowl_with_spoon", "🥣 Bowl with spoon" },
            { "cup_with_straw", "🥤 Cup with straw" },
            { "coconut", "🥥 Coconut" },
            { "broccoli", "🥦 Broccoli" },
            { "pie", "🥧 Pie" },
            { "pretzel", "🥨 Pretzel" },
            { "cut_of_meat", "🥩 Cut of meat" },
            { "sandwich", "🥪 Sandwich" },
            { "canned_food", "🥫 Canned food" },
            { "leafy_green", "🥬 Leafy green" },
            { "mango", "🥭 Mango" },
            { "moon_cake", "🥮 Moon cake" },
            { "bagel", "🥯 Bagel" },
            { "smiling_face_with_3_hearts", "🥰 Smiling face with smiling eyes and three hearts" },
            { "yawning_face", "🥱 Yawning face" },
            { "smiling_face_with_tear", "🥲 Smiling face with tear" },
            { "partying_face", "🥳 Face with party horn and party hat" },
            { "woozy_face", "🥴 Face with uneven eyes and wavy mouth" },
            { "hot_face", "🥵 Overheated face" },
            { "cold_face", "🥶 Freezing face" },
            { "ninja", "🥷 Ninja" },
            { "disguised_face", "🥸 Disguised face" },
            { "face_holding_back_tears", "🥹 Face holding back tears" },
            { "pleading_face", "🥺 Face with pleading eyes" },
            { "sari", "🥻 Sari" },
            { "lab_coat", "🥼 Lab coat" },
            { "goggles", "🥽 Goggles" },
            { "hiking_boot", "🥾 Hiking boot" },
            { "womans_flat_shoe", "🥿 Flat shoe" },
            { "crab", "🦀 Crab" },
            { "lion_face", "🦁 Lion face" },
            { "scorpion", "🦂 Scorpion" },
            { "turkey", "🦃 Turkey" },
            { "unicorn_face", "🦄 Unicorn face" },
            { "eagle", "🦅 Eagle" },
            { "duck", "🦆 Duck" },
            { "bat", "🦇 Bat" },
            { "shark", "🦈 Shark" },
            { "owl", "🦉 Owl" },
            { "fox_face", "🦊 Fox face" },
            { "butterfly", "🦋 Butterfly" },
            { "deer", "🦌 Deer" },
            { "gorilla", "🦍 Gorilla" },
            { "lizard", "🦎 Lizard" },
            { "rhinoceros", "🦏 Rhinoceros" },
            { "shrimp", "🦐 Shrimp" },
            { "squid", "🦑 Squid" },
            { "giraffe_face", "🦒 Giraffe face" },
            { "zebra_face", "🦓 Zebra face" },
            { "hedgehog", "🦔 Hedgehog" },
            { "sauropod", "🦕 Sauropod" },
            { "t-rex", "🦖 T-rex" },
            { "cricket", "🦗 Cricket" },
            { "kangaroo", "🦘 Kangaroo" },
            { "llama", "🦙 Llama" },
            { "peacock", "🦚 Peacock" },
            { "hippopotamus", "🦛 Hippopotamus" },
            { "parrot", "🦜 Parrot" },
            { "raccoon", "🦝 Raccoon" },
            { "lobster", "🦞 Lobster" },
            { "mosquito", "🦟 Mosquito" },
            { "microbe", "🦠 Microbe" },
            { "badger", "🦡 Badger" },
            { "swan", "🦢 Swan" },
            { "mammoth", "🦣 Mammoth" },
            { "dodo", "🦤 Dodo" },
            { "sloth", "🦥 Sloth" },
            { "otter", "🦦 Otter" },
            { "orangutan", "🦧 Orangutan" },
            { "skunk", "🦨 Skunk" },
            { "flamingo", "🦩 Flamingo" },
            { "oyster", "🦪 Oyster" },
            { "beaver", "🦫 Beaver" },
            { "bison", "🦬 Bison" },
            { "seal", "🦭 Seal" },
            { "guide_dog", "🦮 Guide dog" },
            { "probing_cane", "🦯 Probing cane" },
            { "bone", "🦴 Bone" },
            { "leg", "🦵 Leg" },
            { "foot", "🦶 Foot" },
            { "tooth", "🦷 Tooth" },
            { "female_superhero", "🦸‍♀️ Woman superhero" },
            { "male_superhero", "🦸‍♂️ Man superhero" },
            { "superhero", "🦸 Superhero" },
            { "female_supervillain", "🦹‍♀️ Woman supervillain" },
            { "male_supervillain", "🦹‍♂️ Man supervillain" },
            { "supervillain", "🦹 Supervillain" },
            { "safety_vest", "🦺 Safety vest" },
            { "ear_with_hearing_aid", "🦻 Ear with hearing aid" },
            { "motorized_wheelchair", "🦼 Motorized wheelchair" },
            { "manual_wheelchair", "🦽 Manual wheelchair" },
            { "mechanical_arm", "🦾 Mechanical arm" },
            { "mechanical_leg", "🦿 Mechanical leg" },
            { "cheese_wedge", "🧀 Cheese wedge" },
            { "cupcake", "🧁 Cupcake" },
            { "salt", "🧂 Salt shaker" },
            { "beverage_box", "🧃 Beverage box" },
            { "garlic", "🧄 Garlic" },
            { "onion", "🧅 Onion" },
            { "falafel", "🧆 Falafel" },
            { "waffle", "🧇 Waffle" },
            { "butter", "🧈 Butter" },
            { "mate_drink", "🧉 Mate drink" },
            { "ice_cube", "🧊 Ice cube" },
            { "bubble_tea", "🧋 Bubble tea" },
            { "troll", "🧌 Troll" },
            { "woman_standing", "🧍‍♀️ Woman standing" },
            { "man_standing", "🧍‍♂️ Man standing" },
            { "standing_person", "🧍 Standing person" },
            { "woman_kneeling", "🧎‍♀️ Woman kneeling" },
            { "man_kneeling", "🧎‍♂️ Man kneeling" },
            { "kneeling_person", "🧎 Kneeling person" },
            { "deaf_woman", "🧏‍♀️ Deaf woman" },
            { "deaf_man", "🧏‍♂️ Deaf man" },
            { "deaf_person", "🧏 Deaf person" },
            { "face_with_monocle", "🧐 Face with monocle" },
            { "farmer", "🧑‍🌾 Farmer" },
            { "cook", "🧑‍🍳 Cook" },
            { "person_feeding_baby", "🧑‍🍼 Person feeding baby" },
            { "mx_claus", "🧑‍🎄 Mx claus" },
            { "student", "🧑‍🎓 Student" },
            { "singer", "🧑‍🎤 Singer" },
            { "artist", "🧑‍🎨 Artist" },
            { "teacher", "🧑‍🏫 Teacher" },
            { "factory_worker", "🧑‍🏭 Factory worker" },
            { "technologist", "🧑‍💻 Technologist" },
            { "office_worker", "🧑‍💼 Office worker" },
            { "mechanic", "🧑‍🔧 Mechanic" },
            { "scientist", "🧑‍🔬 Scientist" },
            { "astronaut", "🧑‍🚀 Astronaut" },
            { "firefighter", "🧑‍🚒 Firefighter" },
            { "people_holding_hands", "🧑‍🤝‍🧑 People holding hands" },
            { "person_with_probing_cane", "🧑‍🦯 Person with white cane" },
            { "red_haired_person", "🧑‍🦰 Person: red hair" },
            { "curly_haired_person", "🧑‍🦱 Person: curly hair" },
            { "bald_person", "🧑‍🦲 Person: bald" },
            { "white_haired_person", "🧑‍🦳 Person: white hair" },
            { "person_in_motorized_wheelchair", "🧑‍🦼 Person in motorized wheelchair" },
            { "person_in_manual_wheelchair", "🧑‍🦽 Person in manual wheelchair" },
            { "health_worker", "🧑‍⚕️ Health worker" },
            { "judge", "🧑‍⚖️ Judge" },
            { "pilot", "🧑‍✈️ Pilot" },
            { "adult", "🧑 Adult" },
            { "child", "🧒 Child" },
            { "older_adult", "🧓 Older adult" },
            { "woman_with_beard", "🧔‍♀️ Woman: beard" },
            { "man_with_beard", "🧔‍♂️ Man: beard" },
            { "bearded_person", "🧔 Bearded person" },
            { "person_with_headscarf", "🧕 Person with headscarf" },
            { "woman_in_steamy_room", "🧖‍♀️ Woman in steamy room" },
            { "man_in_steamy_room", "🧖‍♂️ Man in steamy room" },
            { "person_in_steamy_room", "🧖 Person in steamy room" },
            { "woman_climbing", "🧗‍♀️ Woman climbing" },
            { "man_climbing", "🧗‍♂️ Man climbing" },
            { "person_climbing", "🧗 Person climbing" },
            { "woman_in_lotus_position", "🧘‍♀️ Woman in lotus position" },
            { "man_in_lotus_position", "🧘‍♂️ Man in lotus position" },
            { "person_in_lotus_position", "🧘 Person in lotus position" },
            { "female_mage", "🧙‍♀️ Woman mage" },
            { "male_mage", "🧙‍♂️ Man mage" },
            { "mage", "🧙 Mage" },
            { "female_fairy", "🧚‍♀️ Woman fairy" },
            { "male_fairy", "🧚‍♂️ Man fairy" },
            { "fairy", "🧚 Fairy" },
            { "female_vampire", "🧛‍♀️ Woman vampire" },
            { "male_vampire", "🧛‍♂️ Man vampire" },
            { "vampire", "🧛 Vampire" },
            { "mermaid", "🧜‍♀️ Mermaid" },
            { "merman", "🧜‍♂️ Merman" },
            { "merperson", "🧜 Merperson" },
            { "female_elf", "🧝‍♀️ Woman elf" },
            { "male_elf", "🧝‍♂️ Man elf" },
            { "elf", "🧝 Elf" },
            { "female_genie", "🧞‍♀️ Woman genie" },
            { "male_genie", "🧞‍♂️ Man genie" },
            { "genie", "🧞 Genie" },
            { "female_zombie", "🧟‍♀️ Woman zombie" },
            { "male_zombie", "🧟‍♂️ Man zombie" },
            { "zombie", "🧟 Zombie" },
            { "brain", "🧠 Brain" },
            { "orange_heart", "🧡 Orange heart" },
            { "billed_cap", "🧢 Billed cap" },
            { "scarf", "🧣 Scarf" },
            { "gloves", "🧤 Gloves" },
            { "coat", "🧥 Coat" },
            { "socks", "🧦 Socks" },
            { "red_envelope", "🧧 Red gift envelope" },
            { "firecracker", "🧨 Firecracker" },
            { "jigsaw", "🧩 Jigsaw puzzle piece" },
            { "test_tube", "🧪 Test tube" },
            { "petri_dish", "🧫 Petri dish" },
            { "dna", "🧬 Dna double helix" },
            { "compass", "🧭 Compass" },
            { "abacus", "🧮 Abacus" },
            { "fire_extinguisher", "🧯 Fire extinguisher" },
            { "toolbox", "🧰 Toolbox" },
            { "bricks", "🧱 Brick" },
            { "magnet", "🧲 Magnet" },
            { "luggage", "🧳 Luggage" },
            { "lotion_bottle", "🧴 Lotion bottle" },
            { "thread", "🧵 Spool of thread" },
            { "yarn", "🧶 Ball of yarn" },
            { "safety_pin", "🧷 Safety pin" },
            { "teddy_bear", "🧸 Teddy bear" },
            { "broom", "🧹 Broom" },
            { "basket", "🧺 Basket" },
            { "roll_of_paper", "🧻 Roll of paper" },
            { "soap", "🧼 Bar of soap" },
            { "sponge", "🧽 Sponge" },
            { "receipt", "🧾 Receipt" },
            { "nazar_amulet", "🧿 Nazar amulet" },
            { "ballet_shoes", "🩰 Ballet shoes" },
            { "one-piece_swimsuit", "🩱 One-piece swimsuit" },
            { "briefs", "🩲 Briefs" },
            { "shorts", "🩳 Shorts" },
            { "thong_sandal", "🩴 Thong sandal" },
            { "light_blue_heart", "🩵 Light blue heart" },
            { "grey_heart", "🩶 Grey heart" },
            { "pink_heart", "🩷 Pink heart" },
            { "drop_of_blood", "🩸 Drop of blood" },
            { "adhesive_bandage", "🩹 Adhesive bandage" },
            { "stethoscope", "🩺 Stethoscope" },
            { "x-ray", "🩻 X-ray" },
            { "crutch", "🩼 Crutch" },
            { "yo-yo", "🪀 Yo-yo" },
            { "kite", "🪁 Kite" },
            { "parachute", "🪂 Parachute" },
            { "boomerang", "🪃 Boomerang" },
            { "magic_wand", "🪄 Magic wand" },
            { "pinata", "🪅 Pinata" },
            { "nesting_dolls", "🪆 Nesting dolls" },
            { "maracas", "🪇 Maracas" },
            { "flute", "🪈 Flute" },
            { "ringed_planet", "🪐 Ringed planet" },
            { "chair", "🪑 Chair" },
            { "razor", "🪒 Razor" },
            { "axe", "🪓 Axe" },
            { "diya_lamp", "🪔 Diya lamp" },
            { "banjo", "🪕 Banjo" },
            { "military_helmet", "🪖 Military helmet" },
            { "accordion", "🪗 Accordion" },
            { "long_drum", "🪘 Long drum" },
            { "coin", "🪙 Coin" },
            { "carpentry_saw", "🪚 Carpentry saw" },
            { "screwdriver", "🪛 Screwdriver" },
            { "ladder", "🪜 Ladder" },
            { "hook", "🪝 Hook" },
            { "mirror", "🪞 Mirror" },
            { "window", "🪟 Window" },
            { "plunger", "🪠 Plunger" },
            { "sewing_needle", "🪡 Sewing needle" },
            { "knot", "🪢 Knot" },
            { "bucket", "🪣 Bucket" },
            { "mouse_trap", "🪤 Mouse trap" },
            { "toothbrush", "🪥 Toothbrush" },
            { "headstone", "🪦 Headstone" },
            { "placard", "🪧 Placard" },
            { "rock", "🪨 Rock" },
            { "mirror_ball", "🪩 Mirror ball" },
            { "identification_card", "🪪 Identification card" },
            { "low_battery", "🪫 Low battery" },
            { "hamsa", "🪬 Hamsa" },
            { "folding_hand_fan", "🪭 Folding hand fan" },
            { "hair_pick", "🪮 Hair pick" },
            { "khanda", "🪯 Khanda" },
            { "fly", "🪰 Fly" },
            { "worm", "🪱 Worm" },
            { "beetle", "🪲 Beetle" },
            { "cockroach", "🪳 Cockroach" },
            { "potted_plant", "🪴 Potted plant" },
            { "wood", "🪵 Wood" },
            { "feather", "🪶 Feather" },
            { "lotus", "🪷 Lotus" },
            { "coral", "🪸 Coral" },
            { "empty_nest", "🪹 Empty nest" },
            { "nest_with_eggs", "🪺 Nest with eggs" },
            { "hyacinth", "🪻 Hyacinth" },
            { "jellyfish", "🪼 Jellyfish" },
            { "wing", "🪽 Wing" },
            { "goose", "🪿 Goose" },
            { "anatomical_heart", "🫀 Anatomical heart" },
            { "lungs", "🫁 Lungs" },
            { "people_hugging", "🫂 People hugging" },
            { "pregnant_man", "🫃 Pregnant man" },
            { "pregnant_person", "🫄 Pregnant person" },
            { "person_with_crown", "🫅 Person with crown" },
            { "moose", "🫎 Moose" },
            { "donkey", "🫏 Donkey" },
            { "blueberries", "🫐 Blueberries" },
            { "bell_pepper", "🫑 Bell pepper" },
            { "olive", "🫒 Olive" },
            { "flatbread", "🫓 Flatbread" },
            { "tamale", "🫔 Tamale" },
            { "fondue", "🫕 Fondue" },
            { "teapot", "🫖 Teapot" },
            { "pouring_liquid", "🫗 Pouring liquid" },
            { "beans", "🫘 Beans" },
            { "jar", "🫙 Jar" },
            { "ginger_root", "🫚 Ginger root" },
            { "pea_pod", "🫛 Pea pod" },
            { "melting_face", "🫠 Melting face" },
            { "saluting_face", "🫡 Saluting face" },
            { "face_with_open_eyes_and_hand_over_mouth", "🫢 Face with open eyes and hand over mouth" },
            { "face_with_peeking_eye", "🫣 Face with peeking eye" },
            { "face_with_diagonal_mouth", "🫤 Face with diagonal mouth" },
            { "dotted_line_face", "🫥 Dotted line face" },
            { "biting_lip", "🫦 Biting lip" },
            { "bubbles", "🫧 Bubbles" },
            { "shaking_face", "🫨 Shaking face" },
            { "hand_with_index_finger_and_thumb_crossed", "🫰 Hand with index finger and thumb crossed" },
            { "rightwards_hand", "🫱 Rightwards hand" },
            { "leftwards_hand", "🫲 Leftwards hand" },
            { "palm_down_hand", "🫳 Palm down hand" },
            { "palm_up_hand", "🫴 Palm up hand" },
            { "index_pointing_at_the_viewer", "🫵 Index pointing at the viewer" },
            { "heart_hands", "🫶 Heart hands" },
            { "leftwards_pushing_hand", "🫷 Leftwards pushing hand" },
            { "rightwards_pushing_hand", "🫸 Rightwards pushing hand" },
            { "bangbang", "‼️ Double exclamation mark" },
            { "interrobang", "⁉️ Exclamation question mark" },
            { "tm", "™️ Trade mark sign" },
            { "information_source", "ℹ️ Information source" },
            { "left_right_arrow", "↔️ Left right arrow" },
            { "arrow_up_down", "↕️ Up down arrow" },
            { "arrow_upper_left", "↖️ North west arrow" },
            { "arrow_upper_right", "↗️ North east arrow" },
            { "arrow_lower_right", "↘️ South east arrow" },
            { "arrow_lower_left", "↙️ South west arrow" },
            { "leftwards_arrow_with_hook", "↩️ Leftwards arrow with hook" },
            { "arrow_right_hook", "↪️ Rightwards arrow with hook" },
            { "watch", "⌚ Watch" },
            { "hourglass", "⌛ Hourglass" },
            { "keyboard", "⌨️ Keyboard" },
            { "eject", "⏏️ Eject button" },
            { "fast_forward", "⏩ Black right-pointing double triangle" },
            { "rewind", "⏪ Black left-pointing double triangle" },
            { "arrow_double_up", "⏫ Black up-pointing double triangle" },
            { "arrow_double_down", "⏬ Black down-pointing double triangle" },
            { "black_right_pointing_double_triangle_with_vertical_bar", "⏭️ Next track button" },
            { "black_left_pointing_double_triangle_with_vertical_bar", "⏮️ Last track button" },
            { "black_right_pointing_triangle_with_double_vertical_bar", "⏯️ Play or pause button" },
            { "alarm_clock", "⏰ Alarm clock" },
            { "stopwatch", "⏱️ Stopwatch" },
            { "timer_clock", "⏲️ Timer clock" },
            { "hourglass_flowing_sand", "⏳ Hourglass with flowing sand" },
            { "double_vertical_bar", "⏸️ Pause button" },
            { "black_square_for_stop", "⏹️ Stop button" },
            { "black_circle_for_record", "⏺️ Record button" },
            { "m", "Ⓜ️ Circled latin capital letter m" },
            { "black_small_square", "▪️ Black small square" },
            { "white_small_square", "▫️ White small square" },
            { "arrow_forward", "▶️ Black right-pointing triangle" },
            { "arrow_backward", "◀️ Black left-pointing triangle" },
            { "white_medium_square", "◻️ White medium square" },
            { "black_medium_square", "◼️ Black medium square" },
            { "white_medium_small_square", "◽ White medium small square" },
            { "black_medium_small_square", "◾ Black medium small square" },
            { "sunny", "☀️ Black sun with rays" },
            { "cloud", "☁️ Cloud" },
            { "umbrella", "☂️ Umbrella" },
            { "snowman", "☃️ Snowman" },
            { "comet", "☄️ Comet" },
            { "phone", "☎️ Black telephone" },
            { "ballot_box_with_check", "☑️ Ballot box with check" },
            { "umbrella_with_rain_drops", "☔ Umbrella with rain drops" },
            { "coffee", "☕ Hot beverage" },
            { "shamrock", "☘️ Shamrock" },
            { "point_up", "☝️ White up pointing index" },
            { "skull_and_crossbones", "☠️ Skull and crossbones" },
            { "radioactive_sign", "☢️ Radioactive" },
            { "biohazard_sign", "☣️ Biohazard" },
            { "orthodox_cross", "☦️ Orthodox cross" },
            { "star_and_crescent", "☪️ Star and crescent" },
            { "peace_symbol", "☮️ Peace symbol" },
            { "yin_yang", "☯️ Yin yang" },
            { "wheel_of_dharma", "☸️ Wheel of dharma" },
            { "white_frowning_face", "☹️ Frowning face" },
            { "relaxed", "☺️ White smiling face" },
            { "female_sign", "♀️ Female sign" },
            { "male_sign", "♂️ Male sign" },
            { "aries", "♈ Aries" },
            { "taurus", "♉ Taurus" },
            { "gemini", "♊ Gemini" },
            { "cancer", "♋ Cancer" },
            { "leo", "♌ Leo" },
            { "virgo", "♍ Virgo" },
            { "libra", "♎ Libra" },
            { "scorpius", "♏ Scorpius" },
            { "sagittarius", "♐ Sagittarius" },
            { "capricorn", "♑ Capricorn" },
            { "aquarius", "♒ Aquarius" },
            { "pisces", "♓ Pisces" },
            { "chess_pawn", "♟️ Chess pawn" },
            { "spades", "♠️ Black spade suit" },
            { "clubs", "♣️ Black club suit" },
            { "hearts", "♥️ Black heart suit" },
            { "diamonds", "♦️ Black diamond suit" },
            { "hotsprings", "♨️ Hot springs" },
            { "recycle", "♻️ Black universal recycling symbol" },
            { "infinity", "♾️ Infinity" },
            { "wheelchair", "♿ Wheelchair symbol" },
            { "hammer_and_pick", "⚒️ Hammer and pick" },
            { "anchor", "⚓ Anchor" },
            { "crossed_swords", "⚔️ Crossed swords" },
            { "medical_symbol", "⚕️ Medical symbol" },
            { "scales", "⚖️ Balance scale" },
            { "alembic", "⚗️ Alembic" },
            { "gear", "⚙️ Gear" },
            { "atom_symbol", "⚛️ Atom symbol" },
            { "fleur_de_lis", "⚜️ Fleur-de-lis" },
            { "warning", "⚠️ Warning sign" },
            { "zap", "⚡ High voltage sign" },
            { "transgender_symbol", "⚧️ Transgender symbol" },
            { "white_circle", "⚪ Medium white circle" },
            { "black_circle", "⚫ Medium black circle" },
            { "coffin", "⚰️ Coffin" },
            { "funeral_urn", "⚱️ Funeral urn" },
            { "soccer", "⚽ Soccer ball" },
            { "baseball", "⚾ Baseball" },
            { "snowman_without_snow", "⛄ Snowman without snow" },
            { "partly_sunny", "⛅ Sun behind cloud" },
            { "thunder_cloud_and_rain", "⛈️ Cloud with lightning and rain" },
            { "ophiuchus", "⛎ Ophiuchus" },
            { "pick", "⛏️ Pick" },
            { "helmet_with_white_cross", "⛑️ Rescue worker’s helmet" },
            { "chains", "⛓️ Chains" },
            { "no_entry", "⛔ No entry" },
            { "shinto_shrine", "⛩️ Shinto shrine" },
            { "church", "⛪ Church" },
            { "mountain", "⛰️ Mountain" },
            { "umbrella_on_ground", "⛱️ Umbrella on ground" },
            { "fountain", "⛲ Fountain" },
            { "golf", "⛳ Flag in hole" },
            { "ferry", "⛴️ Ferry" },
            { "boat", "⛵ Sailboat" },
            { "skier", "⛷️ Skier" },
            { "ice_skate", "⛸️ Ice skate" },
            { "woman-bouncing-ball", "⛹️‍♀️ Woman bouncing ball" },
            { "man-bouncing-ball", "⛹️‍♂️ Man bouncing ball" },
            { "person_with_ball", "⛹️ Person bouncing ball" },
            { "tent", "⛺ Tent" },
            { "fuelpump", "⛽ Fuel pump" },
            { "scissors", "✂️ Black scissors" },            
            { "airplane", "✈️ Airplane" },
            { "email", "✉️ Envelope" },
            { "fist", "✊ Raised fist" },
            { "hand", "✋ Raised hand" },
            { "v", "✌️ Victory hand" },
            { "writing_hand", "✍️ Writing hand" },
            { "pencil2", "✏️ Pencil" },
            { "black_nib", "✒️ Black nib" },
            { "heavy_check_mark", "✔️ Heavy check mark" },
            { "heavy_multiplication_x", "✖️ Heavy multiplication x" },
            { "latin_cross", "✝️ Latin cross" },
            { "star_of_david", "✡️ Star of david" },
            { "sparkles", "✨ Sparkles" },
            { "eight_spoked_asterisk", "✳️ Eight spoked asterisk" },
            { "eight_pointed_black_star", "✴️ Eight pointed black star" },
            { "snowflake", "❄️ Snowflake" },
            { "sparkle", "❇️ Sparkle" },
            { "x", "❌ Cross mark" },
            { "negative_squared_cross_mark", "❎ Negative squared cross mark" },
            { "question", "❓ Black question mark ornament" },
            { "grey_question", "❔ White question mark ornament" },
            { "grey_exclamation", "❕ White exclamation mark ornament" },
            { "exclamation", "❗ Heavy exclamation mark symbol" },
            { "heavy_heart_exclamation_mark_ornament", "❣️ Heart exclamation" },
            { "heart_on_fire", "❤️‍🔥 Heart on fire" },
            { "mending_heart", "❤️‍🩹 Mending heart" },
            { "heart", "❤️ Heavy black heart" },
            { "heavy_plus_sign", "➕ Heavy plus sign" },
            { "heavy_minus_sign", "➖ Heavy minus sign" },
            { "heavy_division_sign", "➗ Heavy division sign" },
            { "arrow_right", "➡️ Black rightwards arrow" },
            { "curly_loop", "➰ Curly loop" },
            { "loop", "➿ Double curly loop" },
            { "arrow_heading_up", "⤴️ Arrow pointing rightwards then curving upwards" },
            { "arrow_heading_down", "⤵️ Arrow pointing rightwards then curving downwards" },
            { "arrow_left", "⬅️ Leftwards black arrow" },
            { "arrow_up", "⬆️ Upwards black arrow" },
            { "arrow_down", "⬇️ Downwards black arrow" },
            { "black_large_square", "⬛ Black large square" },
            { "white_large_square", "⬜ White large square" },
            { "star", "⭐ White medium star" },
            { "o", "⭕ Heavy large circle" },
            { "wavy_dash", "〰️ Wavy dash" },
            { "part_alternation_mark", "〽️ Part alternation mark" },
            { "congratulations", "㊗️ Circled ideograph congratulation" },
            { "secret", "㊙️ Circled ideograph secret" },
        };

        return data.Where(x => context.SearchString == null || x.Value.Contains(context.SearchString, StringComparison.OrdinalIgnoreCase)).Take(12).ToDictionary(x => x.Key, x => x.Value); ;
    }
}